### ISSUE TITLE
Should SelectUncontrolled be removed completely ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1001]
@hamed-musallam you removed 2 instances of SelectUncontrolled.

Based on the firefox problems, should this be removed everywhere and the dependency removed from package.json ?

**Comment by hamed-musallam** [comment]
@lpatiny 
this component done by @michaelwenk  base on the Select component so it's not external library but first i need to check where he use this component then i can remove it if we do not need it anymore.
