### ISSUE TITLE
package-lock.json version change

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1003]
If I remove node_modules and redo a `npm i` we have the following change for package-lock.json:

```
-  "lockfileVersion": 1,
+  "lockfileVersion": 2,
```

Is this normal ?

```
nmrium [master●] % node --version
v15.5.1
nmrium [master●] % npm --version
7.3.0
```

**Comment by targos** [comment]
that's because you use npm 7. this project is setup for npm 6

**Comment by targos** [comment]
I'm okay for moving to npm 7, but everyone has to do it at the same time.

**Comment by hamed-musallam** [comment]
@lpatiny 
but why we have to move to npm version 7? as I remember that last stable version of Node  is 14 and npm  6

**Comment by targos** [comment]
the last stable version of Node is 16 and npm 7

**Comment by hamed-musallam** [comment]
@lpatiny @targos 
Are we going to move to node 16 and npm 7 because we have  to use the same version ?

**Comment by targos** [comment]
My setup switches to the right version automatically so I personally don't care.
