### ISSUE TITLE
histogram display nothing

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1006]
if you check the XTC, Coffe, and the 1h in cosy examples you will find that the outcome from the histogram function in 1d is NaN in all values in x and most of the values in y is 0.
![image](https://user-images.githubusercontent.com/35760236/116663788-deea8780-a997-11eb-9b60-40b330a02c19.png)
![image](https://user-images.githubusercontent.com/35760236/116664131-54565800-a998-11eb-95bc-0651e5fd5f15.png)

**For 2d we have a different problem most of the y values is -Infinity** 

![image](https://user-images.githubusercontent.com/35760236/116664696-19a0ef80-a999-11eb-9cda-61be90b8e8c3.png)

**Comment by lpatiny** [comment]
I hope it is now fixed. It was related to log of 0 and log of negative numbers
