### ISSUE TITLE
Peak picking labels problem on www.nmrium.org

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1008]
Not sure you have this problem on windows but on mac the digits are truncated. I tested with the 13C spectra of cytisine.
![image](https://user-images.githubusercontent.com/1484241/116752981-a766f400-aa06-11eb-979c-59452fc6e434.png)

**Comment by lpatiny** [comment]
This problem is only observed on nmrium.org

https://www.nmrium.org/nmrium#?toc=https://cheminfo.github.io/nmr-dataset-demo/samples.json. You should click on 'Processed 13C Spectrum' to see the problem.

There is much more space on the left of the label.

Checking the CSS there is a padding of 12px that is added in nmrium.org

![image](https://user-images.githubusercontent.com/1484241/116772391-05b7c500-aa4f-11eb-8e2f-370adbf66487.png)

@targos How should this be solved ? Should Nmrium component enforce the padding:0 or is is a problem in the CSS of nmrium.org ?

**Comment by targos** [comment]
I can think of two options:
- override the style it in the component
- use a shadow DOM so that the style of the site has no effect on the component

**Comment by lpatiny** [comment]
I think if the NMRium is immune from the site style it would solve the problem once for ever. At least we would know that if there is some layout problem it is in the component.

How we can have this shadow DOM ? Using a project like https://www.npmjs.com/package/react-shadow ?

**Comment by targos** [comment]
You can try with react-shadow, yes.

**Comment by hamed-musallam** [comment]
I think shadow dom is better option in this case.


I think  we  can use ***@***.***/css#custom-instances
to achieve this.


في السبت، ١ مايو ٢٠٢١ ٢:١٨ م Michaël Zasso ***@***.***> كتب:

**Comment by targos** [comment]
It's done in https://github.com/cheminfo/nmrium/commit/fd7b803a4a567797caf258c2fee1210655f4fd00 but I keep this issue open because there are some broken things now. For example the "empty" message:

![Uploading image.png…]()

**Comment by targos** [comment]
Actually I had to revert it. The OpenChemLib editor doesn't work with shadow dom. I'm not sure we can do anything about it from the Java side...

**Comment by lpatiny** [comment]
@hamed-musallam in the mean time please override the style in the component so that it works correctly on nmrium.org. Hopefully there is a solution for the shadow dom that seems to be the best long term solution.

**Comment by hamed-musallam** [comment]
@lpatiny 
i think the problem related to https://github.com/cheminfo/nmrium/issues/1009 so how I can be sure that the problem is gone because I remove the public style and use style directly on the peak component.

**Comment by lpatiny** [comment]
@targos How to test the last version of the NMRium component in nmrium.org without creating a release ? I tried 
```bash
npm build
npm link
```
But this did work.

**Comment by targos** [comment]
npm link should work but you need to run the `compile` script, not the build one.

**Comment by hamed-musallam** [comment]
it's solved in release 0.12
