### ISSUE TITLE
Advanced save in .nmrium data

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1010]
We need different options when saving .nmrium data
- filename
- compressed (true / false)
- pretty (JSON.stringify(xx) or JSON.stringify(xx, undefined, 2)
- If there is a 'source' of data add an option (default to false):
  - data: true / false. If we don't want the data we should also not save the meta and info
  - If there is no source we should disable this option and the data is always saved

Add a menu item in Export: 'Save data as ... (SHIFT + CTRL + Save)

**Comment by hamed-musallam** [comment]
@lpatiny 
we already did the first the 3 options. do you mean we have to open a dialog box and the user can change the options?
