### ISSUE TITLE
nmredata format should not contain molecule SVG

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1016]
@targos Does it make sense in react to use non-enumerable properties ? We have here a molecule and there is the property SVG that we don't want to export. Currently we do a 'toJSON()' of molecules and of course the svg prop is there as well.

In react + immer are we allowed to use non-enumerable properties ?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties

![image](https://user-images.githubusercontent.com/1484241/116967099-dd7bd080-acb1-11eb-9113-d9545c9b6c34.png)

**Comment by targos** [comment]
I don't know if immer supports that

**Comment by lpatiny** [comment]
@hamed-musallam You may anyway create your own exportation procedure. Only molfile prop should be exported for molecules.
