### ISSUE TITLE
Sanplot

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1018]
How to calculate it ?

Check how we could plot it there:

![image](https://user-images.githubusercontent.com/1484241/116968531-f76ae280-acb4-11eb-8b6a-7360163f1a68.png)

**Comment by targos** [comment]
I guess a link wouldn't hurt: https://doi.org/10.1002/mrc.4882

**Comment by lpatiny** [comment]
Also this one https://github.com/mljs/spectra-processing/blob/master/src/x/xNoiseSanPlot.js ;)

**Comment by jobo322** [comment]
it works and parse the molfile too. [0aa42b1](https://github.com/cheminfo/nmrium/commit/0aa42b1d492f518f77c944f64585899ab00cee60)
