### ISSUE TITLE
Peak picking and stack (s)

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1026]
If you have only one spectrum and add peak picking

If you press 's' for `stack` the label will move and they are not expected to.

![image](https://user-images.githubusercontent.com/1484241/117308164-8d536880-ae81-11eb-8bc6-ca47fd7c56bf.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
we should not display the peaks if it's stacked because we only display the peaks for the selected spectrum.
