### ISSUE TITLE
Help dialog box should be centered and bigger

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1030]
When you click on the help button

![image](https://user-images.githubusercontent.com/1484241/117464364-de7e5d80-af50-11eb-85eb-ee33ad6d2bb8.png)

The dialog box should be bigger and vertically centered (depending the size of the component of course).

**Comment by hamed-musallam** [comment]
@lpatiny  this is what happens,  
![image](https://user-images.githubusercontent.com/35760236/117637981-ac544200-b182-11eb-8162-33e4055277e4.png)
can you send me an image if you do not have something like in the above image?

**Comment by lpatiny** [comment]
Yes you are right. @targos Could this be a problem in a PWA local application install ?

**Comment by targos** [comment]
In that case, it opens the page in the web browser.

**Comment by lpatiny** [comment]
@hamed-musallam Please implement the idea of targos and open the help in a new page. It will be easier to manage than trying to fit the help in a dialog box.
