### ISSUE TITLE
Store used colors in the state

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#1035]
https://github.com/cheminfo/nmrium/blob/990eb54b96130a740b26bd4a12104ba5abddfcf8/src/data/data1d/Datum1D.ts#L14

This line is problematic because it's a global variable and if we reload the component with other data, new colors will be used each time.

**Comment by targos** [comment]
There's no magic solution to this. Sometimes you have to pass a value through a series of functions.
What we do in other projects is we pass the entire state object (or a big part of it) and the the function gets what it needs from it.

**Comment by hamed-musallam** [comment]
it's done, 0d8951821a69511c978eb1bcb1bef5bcf4ed300f
