### ISSUE TITLE
Non constant constants

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1036]
In the code there are several places where const are assigned but they are actually non constant.

It is therefore a problem when many instances of the NMRium component are in the same page. It also have an impact when we don't remove from the dom NMRium component because there is a 'memory' effect.

Please search in the project for `export const` and check that all the const are really constants. If it is not the case it should be in the state.

For example

https://github.com/cheminfo/nmrium/blob/9198300a43cd43eb3bdd1912e4623e9cb8494b70/src/data/data2d/Datum2D.ts#L13-L14

**Comment by hamed-musallam** [comment]
@lpatiny 
actually, we are not assigned a new array in any place, we are either push or pull from the array, so we use the const keyword, but you are right if I assign a new array.
