### ISSUE TITLE
drag a region and peak all peaks within the area

### ISSUE THREAD

**Issue by djeanner** [cheminfo/nmrium#104]
currently - if I got it right - one can only pick on peak at a time.
It would be nice to be able to pick peaks in a region defined with a click-drag-release.
An nice addition could be to pick all the peaks above a mouse threshold - maby with a shift+click?

**Comment by nes-cgn** [comment]
That would be a really useful feature. Also, for 'multiplets', it would be great if there could be a way to define the 'peak' as the center of region.

**Comment by lpatiny** [comment]
Peak picking is now done on the part that is displayed (and therefore depends of the zoom level).
