### ISSUE TITLE
actions help

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1043]
@targos 
I going to add these line of code into the release action to update the version number, can you check if it is going to work without a problem 

>       - uses: actions/checkout@v2
        # These if statements ensure that a publication only occurs when a new release is created
        if: ${{ steps.release.outputs.release_created }}
        with:
          path: './'
      - name: "update version"
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs'); 
            const filepath = 'src/versionInfo.js';
            fs.writeFileSync(filepath,`export default { version : 'V${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}};`);    
      - run: |
          git config user.email admin@cheminfo.org
          git config user.name "Cheminfo Bot"
          git add  src/versionInfo.js
          git commit -m "update version"

**Comment by hamed-musallam** [comment]
@targos 
can you check this?

**Comment by targos** [comment]
can you please do it as a pull request?

**Comment by targos** [comment]
done
