### ISSUE TITLE
Hide button if not many 1D spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1047]
This button should not be available if we have only one 1D spectrum.

![image](https://user-images.githubusercontent.com/1484241/118102429-0fd7ad00-b3d9-11eb-873f-af45cd11f508.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
is it for fd and fid?

**Comment by lpatiny** [comment]
For FID we should never display the multiple spectra analysis tool
