### ISSUE TITLE
Cancel does not cancel

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1049]
I you change the preferences and then cancel the changes are still saved.

It looks like the global state is changed continuously.

This is at least the case for ranges and multiple spectra analysis preferences

![image](https://user-images.githubusercontent.com/1484241/118138639-db7ae580-b406-11eb-9968-0223df6a2710.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
X button only for close the window and does not reset the settings.

**Comment by lpatiny** [comment]
I think it should reset the settings as well. Seems more logical to me.

**Comment by targos** [comment]
It's not really that it should reset the settings. The settings should only be applied when the ✔️ button is clicked.
