### ISSUE TITLE
remove class from ZoomHistory

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1051]
Could zoom history be simply an array of objects in the state rather than a structure that look like a singleton (not sure it does not have side effects if many instances of NMRium).

**Comment by hamed-musallam** [comment]
@lpatiny 
it's must be an object, its key is the nucleus and the values is an array because we have a history per tab.

**Comment by lpatiny** [comment]
But it could not be an object of array in the state ? I would expect that this singleton is shared between all the instances of NMRium and this is not something we would like.
