### ISSUE TITLE
Assignment is weird

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1056]
For the 1H of cytisine, load and make an autorange picking

Assign one range to an atom

If you try after to make a SHIFT + CLICK on an atom in order to expand an atom, the 2 protons will be automatically assigned. This is not the expected behaviour. Only if no modifiers key are pressed we should assign the atom (add a link)

**Comment by hamed-musallam** [comment]
@targos @lpatiny 
we need some changes to be done on OCLnmr when trigger setSelectedAtom to return event object so i can check if a modifiers key are pressed or  not
