### ISSUE TITLE
Make added structure more obvious

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmrium#1059]
When a second structure is added, e.g. by dropping a molfile, the hints for the user that there is a second structure could be more obvious. The arrows should be bigger and maybe the view could switch to the new molecule.

![grafik](https://user-images.githubusercontent.com/40795855/118299296-dbe7af00-b4e0-11eb-861a-896523c58ad0.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
What you are suggest?

**Comment by lpatiny** [comment]
After dropping a structure (like you did when pasting a structure) we could focus on the new uploaded structure.

Those arrows could also be larger maybe (and in grey in the background).
