### ISSUE TITLE
Integral sum popup breaks when more than one compound is present

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmrium#1062]
Steps to reproduce:
- Load 1H of cytisine example
- Add another structure (e. g., attached molfile)
- Change integration sum.

![grafik](https://user-images.githubusercontent.com/40795855/118300971-cf645600-b4e2-11eb-8978-38f40079dd33.png)

[acetophenone.zip](https://github.com/cheminfo/nmrium/files/6480038/acetophenone.zip)

**Comment by lpatiny** [comment]
We should indeed have the next / previous button to select the molecule and be able to enter a molecular formula manually as it is the case when we have only one structure

![image](https://user-images.githubusercontent.com/1484241/118509198-21e68200-b730-11eb-9987-49054ebb7012.png)
