### ISSUE TITLE
Disable filter and position of peak labels

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1063]
If you take the 'processed' example and disable the line broadening filter the position of the peak labels is not correct.

![image](https://user-images.githubusercontent.com/1484241/118353837-7e974080-b568-11eb-9a80-3bf0d4846176.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
the problem is in the intensity we define it after broadening.

**Comment by hamed-musallam** [comment]
@lpatiny 
what do you think we have to do? are you need t to recalculate the intensity of the peaks?

**Comment by lpatiny** [comment]
I'm wondering if we should even keep the peak intensity or if we should just recalculate it each time we need it based on the currently displayed spectrum.
