### ISSUE TITLE
Polynomial baseline correction seems weird

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1073]
Trying to select zones (shift + draw) for manual baseline correction

![image](https://user-images.githubusercontent.com/1484241/118366202-0ea4ac80-b5a0-11eb-9f4c-ce5728a80582.png)

I obtain the following baseline correction

![image](https://user-images.githubusercontent.com/1484241/118366376-3e53b480-b5a0-11eb-88bb-50eeb9029900.png)

That seems weird. @jobo322 any idea where could be the problem.

**Comment by jobo322** [comment]
Is it ok to set up a match criterium to apply or not the "correction"? This is the worst case for baseline correction based on polynomial regression because we are trying to match a polynomial of degree 3 to more or less flat data.

**Comment by lpatiny** [comment]
Is a straight line better than the degree 3 ? Because even if we specify degree 3 the x^3 and x^2 parameter may be 0. Are you able to extract this as a testcase for the polynomial package to check if the result is really correct ? I don't think we should add this match criterium.
