### ISSUE TITLE
Adding new custom signal in range edition

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1078]
I'm not able to add a new signal in the range edition dialog box.

We should display under the input field the range of values that is allowed (and also validate this value). It has to be between the from and to of the range.

I think the input field is defined as number but the `step` should be defined as `any`. Currently only integer values can be entered. 

![image](https://user-images.githubusercontent.com/1484241/118373971-d27e4580-b5b9-11eb-95e7-c3dca1e4f8d3.png)

**Comment by nes-cgn** [comment]
Is this something with respect to the manual selection of new signals? That would be indeed important.

**Comment by lpatiny** [comment]
@nes-cgn Yes but this is not a new feature. It exists for 1 year now.
