### ISSUE TITLE
MacOs and shift + cmd + s

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1081]
You can do cmd + s to save the spectrum but cmd + shift + s does not allow to 'save as'.

You need on OsX to press CTRL + shift + s which is not intuitive. I think both keys should work.

![image](https://user-images.githubusercontent.com/1484241/118376516-ac13d680-b5c8-11eb-9495-1008b5934d3d.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
I already implemented it in this way but I do not know why it's not working, and I don't have a MacBook so o can not know what is the problem can you check these lines
https://github.com/cheminfo/nmrium/blob/b25f7a04e5485c6c8963401aab4cc6e71c5c0338/src/component/EventsTrackers/KeysListenerTracker.jsx#L214-L221

**Comment by targos** [comment]
FWIW it works fine on my mac.

**Comment by lpatiny** [comment]
When I add a debugger point I see that when I press shift + cmd + 's' the 'e.key' value is a lowercase 's'.

So this commit fix the problem:

https://github.com/cheminfo/nmrium/commit/ade53cdde82430ddd1ba0fd4be8d503fa79ed30d

Please could you confirm that on your computer shift + command + s generates an uppercase 'S' ?

**Comment by targos** [comment]
On my computer it generates an uppercase S, yes. I generally recommend to do case-insensitive comparisons, though because it depends on the state of "caps lock"
