### ISSUE TITLE
The button Save should be on the right

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1082]
I have the impression that in all the softwares the validate button is on the right and the cancel button is on the left.

It seems to me that in many dialog boxes it is the opposite, for example in Save as.

Please could you invert those buttons ?

Example from another software:

![image](https://user-images.githubusercontent.com/1484241/118376591-25132e00-b5c9-11eb-97a9-a89b487d6565.png)

Example from NMRium:

![image](https://user-images.githubusercontent.com/1484241/118376628-6b688d00-b5c9-11eb-8e4f-333c8a621deb.png)

**Comment by targos** [comment]
> I have the impression that in all the softwares the validate button is on the right and the cancel button is on the left.

> It seems to me that in many dialog boxes it is the opposite, for example in Save as.

I don't have any opinion on how it should be in nmrium, but this is a system-dependent convention.

On macOS, the validate button is on the right, but on Windows, it's on the left:
![image](https://user-images.githubusercontent.com/2352663/118454429-a61d1300-b6f8-11eb-970e-d1e00f317b70.png)
