### ISSUE TITLE
solid state NMR jcamps

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/nmrium#1097]
I just had with Luc a look at solid state NMR jcamps. You can get the files from https://www.repository.cam.ac.uk/handle/1810/278674. For reuse you would need to attribute the authors. 

Following observations: 

1. ppm is off, probably the frequencies are parsed incorrectly 
2. in the overlay, scroll with the mouse wheel is strange. It suddenly completely changes the scale (in the gif i tried to smoothly scroll, using Brave Version 1.24.82 Chromium: 90.0.4430.93 (Official Build) (x86_64) on MacOS)

![chrome-capture (1)](https://user-images.githubusercontent.com/32935233/118646289-4ef26d80-b7e0-11eb-813d-ec760ab5d18b.gif)

**Comment by lpatiny** [comment]
@hamed-musallam Please could you add this dataset as a testcase ? It would be named 'Solid state'
@jobo322 Could you have a look why those data are not loaded correctly ? I guess the frequency is stored in another parameter.

**Comment by lpatiny** [comment]
At first it looks really weird but I never saw solid state NMR before ... I checked the publication https://doi.org/10.1021/acs.chemmater.8b00747 and apparently it is correct.

**Comment by jobo322** [comment]
I got the same result in topspin, e.g the file "17O_NMR_La2NiO4_broadband-spinecho" seems similar to it in nmrium.

Topspin
![image](https://user-images.githubusercontent.com/12143935/118806729-0a60e380-b86d-11eb-8fa0-15fd3c1cec53.png)

nmrium
![image](https://user-images.githubusercontent.com/12143935/118806838-2b293900-b86d-11eb-9ea2-24891dd770bf.png)
