### ISSUE TITLE
Bug when displaying colors for 2D spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1111]
![image](https://user-images.githubusercontent.com/1484241/119790183-028be980-bed4-11eb-856b-6e32eda1f955.png)

If you click on the icon it crash

**Comment by lpatiny** [comment]
@hamed-musallam Please first make a failing test with Playright https://github.com/cheminfo/nmrium/blob/master/README_DEV.md#end-to-end-tests. This will be a good oportunitiy to continue to test the component and to learn how to write those tests.

**Comment by hamed-musallam** [comment]
@lpatiny 
the problem comes from snaplot function, I contact Alejandro and he is going to check it, once he finished I'm going to make some refactoring in the component to become better.

**Comment by targos** [comment]
@hamed-musallam @jobo322 Please respect the assignment on issues. Sébastien was working on it.

**Comment by jobo322** [comment]
Sorry, my changes were really small, no problem if you reverse it

**Comment by hamed-musallam** [comment]
@targos 
we sorry but it's was assign to me so I already discuss with Alejandro problem and the problem was related to sanplot function and the spectra that do not contain negative signals...

@targos 
he can write a test case for it, and I'm sorry again it is my mistake

**Comment by hamed-musallam** [comment]
@steinbeck 
Sorry for this overlap in tasks, It was not intentional.

**Comment by Sebastien-Ahkrin** [comment]
@hamed-musallam There is no problem don't worry ! 😃

**Comment by hamed-musallam** [comment]
it's done, link to aa90fa0c0e080f2be9190addc3bc745eb432c76f and  627a4821b992f42991cd03a1dfa424dd1b8412e3
