### ISSUE TITLE
Summary table crashes when editing number of protons

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmrium#1112]
In the following example, assignment was possible but once I tried to complete the entries in the summary table, the example crashed:
https://cdn.nmrium.org/v0.12.0/index.html?sampleURL=https://cheminfo.github.io/nmr-dataset1/data/2D-140-67-0-solved.json#/

when I intend to add the number of protons in the fields marked with arrows, the page crashes:
![corrtab_ex7_crash](https://user-images.githubusercontent.com/47237343/120267777-f07bc380-c2a4-11eb-9b6f-6e8fc072aaad.PNG)

**Comment by hamed-musallam** [comment]
@nes-cgn 
I dug into the problem and I found it is may be related to the library that developed by Michael, I will contact him and work together to solve it as soon as possible.

![image](https://user-images.githubusercontent.com/35760236/120294556-9a1f7c80-c2c6-11eb-86e0-e8813d6008e6.png)

**Comment by nes-cgn** [comment]
Thank you Hamed,
this would be great

Quoting hamed-musallam ***@***.***>:

> @nes-cgn
> I dug into the problem and I found it is may be related to the  
> library that developed by Michael, I will contact him and work  
> together to solve it as soon as possible.
>
> ![image](https://user-images.githubusercontent.com/35760236/120294556-9a1f7c80-c2c6-11eb-86e0-e8813d6008e6.png)



-- 
Dr. Nils Schloerer

Department fuer Chemie
der Universitaet zu Koeln
NMR-Abteilung
Greinstr.4
D-50939 Koeln (Germany)

(+49) (0)221 470 3081 (office)
(+49) (0)221 470 1166 (fax)

http://www.nmr.chemie.uni-koeln.de/nmr.html
http://www.nmrshiftdb.org
https://idnmr.uni-koeln.de

**Comment by michaelwenk** [comment]
@nes-cgn I did a pull request for this. After the merge by Hamed,  it should work again.
