### ISSUE TITLE
please check the component after you change it from jsx to tsx especially the default props

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1117]
@Sebastien-Ahkrin 

For example, none of the filters must be selected unless we press on one, I will solve it but I show it to you as an example, so be sure the component still functional.

![image](https://user-images.githubusercontent.com/35760236/121505852-786b7700-c9e3-11eb-859f-4c0d76cf9dd5.png)

**Comment by targos** [comment]
@hamed-musallam The application is quite complex, and it is not possible to check manually every possible case. I did not see the regression myself. The only way to prevent regressions for sure is to add test cases, like this one: https://github.com/cheminfo/nmrium/blob/master/test-e2e/panels/spectra.test.ts
