### ISSUE TITLE
Windows Browser sometimes recognized as touch device

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmrium#1129]
Pavel Kessler from Bruker told me that his Windows computers were not working with NMRium because they were wrongfully considered touch devices. The issue occurred in Firefox and Edge. Please contact him for further details: Pavel.Kessler@bruker.com

**Comment by hamed-musallam** [comment]
@lpatiny 
we need further information and how we can test this issue, Can you contact him?

**Comment by targos** [comment]
It's probably the same issue as https://github.com/cheminfo/nmrium/issues/1033

We are going to let the users bypass the check but it would still be useful to understand why certain computers pretend to be touch devices when they are not.
