### ISSUE TITLE
Prop validation error when closing the panels with double click

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#1141]
![image](https://user-images.githubusercontent.com/2352663/122536043-695c7880-d024-11eb-987c-86380bd251f3.png)

**Comment by hamed-musallam** [comment]
@targos 
I tried your case but I can not reproduce it.

**Comment by targos** [comment]
Maybe it wasn't clear, I mean closing all the panels by double clicking on the vertical separation between the spectrum area and the panels
