### ISSUE TITLE
Wrappers ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1150]
@hamed-musallam Why did you do those wrappers ?

https://github.com/cheminfo/nmrium/blob/fbaec535c2ed6c44be355bc4cc24ac6d52604552/src/component/hoc/ExclusionZonesWrapper.jsx#L5-L10

It would be simpler to directly put this code in the component itself:

https://github.com/cheminfo/nmrium/blob/fbaec535c2ed6c44be355bc4cc24ac6d52604552/src/component/1d/ExclusionZones.tsx#L46-L52

**Comment by targos** [comment]
See https://github.com/cheminfo/nmrium/commit/427fb96b908b67b98dd7d72420194d1977b7ddd3 for an example that simplifies the wrapping and does it all in the same file.

**Comment by hamed-musallam** [comment]
@targos 

First thanks for this commit, it seems like you move the wrapper at the level of the panel to make code simpler and maintainable but what is going to happen if this wrapper I used for more than one component?

**Comment by targos** [comment]
I don't think this kind of wrapper should be used for more than one component. As an optimization technique, they should be specialized to one component.

**Comment by hamed-musallam** [comment]
@targos 

also, you will find those lines of code are repeated in all the wrapper in general but the only difference we destructuring different properties according to what the panel needs, Can we move it to a higher level and Destructuring the props that we need only? 

https://github.com/cheminfo/nmrium/blob/7fa77753f7a3d6c7d79b5370ee7830a0ab5bec7f/src/component/panels/InformationPanel.tsx#L139-L148

**Comment by targos** [comment]
> Can we move it to a higher level and Destructuring the props that we need only?

What do you have in mind?

**Comment by hamed-musallam** [comment]
write a custom hook that takes defaultProps as parameters like this 

const useSpectrum = (defaultProps)=>{
  const { data, activeSpectrum } = useChartData();
  return   useMemo(() => {
    if (data && activeSpectrum && activeSpectrum.id) {
      const datum =
        data.find((datum) => datum.id === activeSpectrum.id) || defaultProps;
      return datum;
    }
    return defaultProps;
  }, [activeSpectrum, data]);
}

and when we call it we only destruct the props that we need and pass it to the panel

**Comment by targos** [comment]
Sure, I'm all for having custom hooks to avoid repetitions.

**Comment by hamed-musallam** [comment]
@targos 

I did the changes, can you take a look at the last two commits?

**Comment by targos** [comment]
LGTM

**Comment by hamed-musallam** [comment]
@lpatiny @targos 
I refactored all the wrappers as @targos  suggested.
