### ISSUE TITLE
i forgot to add memo on the Exclusive zone component

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1151]
@targos 
you removed the wrapper in this commit 40b1cd5d5ecbd168a73825923461a82c1cfee6fb  because I do not use a memo on the component and that is true, it inadvertently omitted, if there is no other reason for removing it, can we keep it and just add a memo.

**Comment by targos** [comment]
Hello @hamed-musallam. I removed the wrapper, but I added a memo on the new `ExclusionZone` component. There is no need for a memo on the `ExclusionZones` component. It doesn't do anything costly.

**Comment by targos** [comment]
@hamed-musallam is it ok with https://github.com/cheminfo/nmrium/blob/7fa77753f7a3d6c7d79b5370ee7830a0ab5bec7f/src/component/1d/ExclusionZone.tsx#L48 ? Can we close this issue?

**Comment by hamed-musallam** [comment]
@targos 
yes for sure
