### ISSUE TITLE
issues with baseline correction "degree" option

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#1155]
- It is possible to enter decimal numbers (for example 3.1), but then it results in a crash when the filter is applied
- It is not clear that the values are restricted between 1 and 6. Maybe put this in the label ? `degree (1-6): `
- If I try to write something that's not in range, the value is always replaced with `3`. Can it instead stay what it is? Ideally, some message would be displayed to help the user.

**Comment by hamed-musallam** [comment]
@lpatiny 
I returned to https://github.com/mljs/baseline-correction-regression/blob/master/src/index.js but I can not find what is the range of values that are allowed.

**Comment by hamed-musallam** [comment]
fixed in defa111d9d4ecbdc893daec0896b6fb22c1e9c5f
