### ISSUE TITLE
access global state for testing purpose 

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1158]
@targos 

in some case we need to access the global state when writing a test case with the playwright library, is there any way to access the global state and be sure that the state is already updated like this example with Redux 

```
 // evaluate in page context to get window.store, and
    // then assert values in nodejs
    console.log(await page.evaluate(() => window.store.getState()));

    // dispatching actions to modify redux store
    await page.evaluate(() => {
        window.store.dispatch({ type: 'ADD_TODO', text: 'Test dispatch' });
    });
    console.log(await page.evaluate(() => window.store.getState()));
```

**Comment by targos** [comment]
If you want to unit test state updates, this shouldn't be done with playwright. Just use simple Jest tests.
Playwright setup is to test user interaction.
