### ISSUE TITLE
Listen to attribute changes 

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1160]
@targos 

is there any way in the playwright to listen for attribute value once it changed instead of use waitForTimeout, for example, once I change the spectrum color I need to check if the stroke value changed from one color to another?

**Comment by targos** [comment]
@hamed-musallam you should be able to use any attribute in a selector. For example, if you want to wait for the new value of `stroke`, add `[stroke="#NEWCOLOR"]` to the selector

**Comment by targos** [comment]
After https://github.com/cheminfo/nmrium/commit/59a1a6c4c5744ba20f342c48ec3b8381bf993680, we should use `expect(locator).toHaveAttribute(name, value)`. This will wait automatically.
