### ISSUE TITLE
test cases

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1168]
@targos 

I know we have to write test cases isolated as much as we can and not depending on each other but in some cases, we need to have a test suite that contains several test cases  that depend on each other and other cases only depend on the first test, for example, 

we have three tests add peak, shift peak on the x-axis and delete peak in this example the add peaks must work successfully and then run the others.

Can we run the test cases in sequential order as listed in the file and Is it's suitable to have a test that depends on another test??

How we can do this in Jest?

In Playwright I have to wait for the displayer until becomes fully visible before we can do any test, in some cases, the displayer takes time more than 3000 ms which makes the test failed is ok if we increase the timeout time?

**Comment by targos** [comment]
The tests are always run in sequential order as in the file.
That said, I still think you should avoid having a test that depends on the result of another one. If you want to test action1, then action1 followed by action2, the solution is to write action1 in a function:

```js
function action1() {
  // code
}

function action2() {
  // code
}

test('action1', () => {
  const result = action1()
  assertSomething()
})

test('action2', () => {
  const result1 = action1();
  const result2 = action2(result1);
  assertSomething()
})
```

**Comment by hamed-musallam** [comment]
@targos 

yes you are right we have to make it isolated as much as we can but what the best strategy to have the cases add/shift/delete??

Also, I have to wait for the displayer until becomes fully visible before we can do any test, in some cases, the displayer takes time more than 3000 ms which makes the test failed is it ok if we increase the timeout time?

**Comment by hamed-musallam** [comment]
@targos 

to be sure from what I understanding from you, all the tests run in sequential order inside the file even if I group it by describe?

**Comment by targos** [comment]
If you want to wait for something to be visible, you need to find a selector for it and use `await page.waitForSelector(selector)`. This avoids to wait arbitrary amount of time.

I didn't know that you were talking about playwright tests in the beginning, sorry. I think for these, it's ok to do everything in one test:

```js
test('add/shift/delete', () => {
  await openPage()
  await addPeak()
  expectSomething()
  await shift()
  expectSomethingElse()
  await delete()
  expectOtherThing()
});
```

Don't hesitate to add common methods to the [https://github.com/cheminfo/nmrium/blob/master/test-e2e/NmriumPage.ts](NmriumPage) class if you think they will be useful in tests (for example `page.waitForVisibleSpectrum()`, things like that)

**Comment by hamed-musallam** [comment]
@targos 
`await page.waitForSelector(selector)` by default have a timeout of 3000 ms so I think it's better if we make it greater?

what about writing it in this way ?

`
describe('test add/shift/delete', () => {
  
  test('add peaks', () => {
      // test add peak
  });

  test('shift peak', () => {
   // test shift peak
  });


  test('delete peak', () => {
   // test delete peak
  });
});

`

**Comment by targos** [comment]
> await page.waitForSelector(selector) by default have a timeout of 3000 ms so I think it's better if we make it greater?

Yes, another reason for putting it in the NmriumPage class :)

If the tests depend on each other, there is no advantage of putting them in different `test()` blocks, because they cannot be run separately anyway.
There's also our beforeEach/afterEach setup that prevents it because it closes the pages between tests: https://github.com/cheminfo/nmrium/blob/2720af2f7ab73f1abf019d030853b1121730a30f/test-e2e/jest.setup.js#L25-L32
