### ISSUE TITLE
Change integrals from table improvements

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1174]
Currently in order to change the integral you need:

1. click twice on the cell
2. click once or twice in order to focus the cell and select all
3. press enter to validate

![2021-07-16 05 32 34](https://user-images.githubusercontent.com/1484241/125887637-20a92bfd-c651-4ed8-b4d9-627632ae9067.gif)

The following improvements should be implemented:

1. click twice focus directly the cell and select all the character
2. in order to cancel the change, press 'ESC' or click anywhere else
3. In order to validate the change, press 'enter', 'return' or 'tab'

**Comment by hamed-musallam** [comment]
fixed in 74bd916ad2e163728fdb220bd540038a631c3a79,4d62beebbf4b2671624c7df8abfd735f87d3e382,503693d95959725d03e647228f5a36b8ad9a82e6
