### ISSUE TITLE
No way to edit chemical shifts from signals

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1175]
Currently it is not possible to edit the chemical shifts from the ranges panel. It shift to edition mode without the possibility to edit.

![2021-07-16 05 36 57](https://user-images.githubusercontent.com/1484241/125888040-4f6ad231-973e-454c-8f98-5ebb92aae12e.gif)

This should be fixed and also we should have the same edition features as described in https://github.com/cheminfo/nmrium/issues/1174 (same is true at the level of all the other table like peak table).

**Comment by hamed-musallam** [comment]
fixed in 74bd916ad2e163728fdb220bd540038a631c3a79,4d62beebbf4b2671624c7df8abfd735f87d3e382,503693d95959725d03e647228f5a36b8ad9a82e6
