### ISSUE TITLE
Range edition not working anymore

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1176]
Click on the range edition button does not open the dialog anymore.

![image](https://user-images.githubusercontent.com/1484241/125890667-8030dc94-7361-4b4c-9348-a938b2f06ac8.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
broke in  https://github.com/cheminfo/nmrium/commit/2720af2f7ab73f1abf019d030853b1121730a30f#diff-f58d3a40abddce296d873ba49637dfbee42eb9df30d1e7800d6d1f67a6422d7eL233

**Comment by targos** [comment]
We can't really blame anyone for this `position: 'none'` is not a valid value. It's weird that it worked with it.

**Comment by hamed-musallam** [comment]
@targos 
actually, the purpose is only to mention where is the problem and yes you are right it's not an acceptable value.
For sure, the purpose of my comment is not to blame anyone..

**Comment by hamed-musallam** [comment]
@targos 
We are in the same boat, I mean we are a team so no place to blame each other.

I'm sorry for the misunderstanding in my comment.
