### ISSUE TITLE
Rename properties

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1181]
This is a breaking change and the JSON format will slightly change but it is a good time to do it

https://github.com/cheminfo/nmrium/blob/985b5830e76bb86a89229a13d4b46b4d170cc5c5/src/component/1d/ranges/Range.tsx#L58-L60

A Range should contain 'signals' (plural and not singular).

Also it is not 'integral' but in should be renamed to 'integration'.

**Comment by targos** [comment]
Should we start to take care about backwards-compatibility with previous nmrium files? meaning doing some conversion of the old format when it's loaded?

**Comment by hamed-musallam** [comment]
@lpatiny @targos 
yes, I think we have to take care of backward compatibility and this means we have extra meta info when export as JSON such as version number but are we going to have a special loader for a specific version the user has to select before loading the file or the system dynamically detect the version and use the loader that compatible with that version.

**Comment by lpatiny** [comment]
@hamed-musallam is Nils using the .nmrium format for his classes ? I don't think that there are .nmrium files around except the one that we have in our testcases.

**Comment by hamed-musallam** [comment]
@lpatiny
I'm not sure but if Nils using it I can reflect the changes manually on the his files.

**Comment by targos** [comment]
Anyone can save and reload `.nmrium` files from nmrium.org, so people who are using the site may rely on it.

**Comment by hamed-musallam** [comment]
@lpatiny @targos  
i think we have to include meta data in .nmrium file so what is the info that we can rely on it, and we have to do the same also in nmredata.

**Comment by lpatiny** [comment]
@hamed-musallam You can plan a migration code for the old to new format.
If the property 'version' does not exists it means it has to migrate.
During migration you need to append the current version of the file format (will be '1'). Related to ticket https://github.com/cheminfo/nmrium/issues/1184

**Comment by hamed-musallam** [comment]
done in  eb507532f3846ce6ab5316460b5eedddc5a9b9be and 44e3fffe803ee6209bee2f239eefc4fa9961567c
