### ISSUE TITLE
Add version in .nmrium file format

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1184]
I don't think that currently the .nmrium format has a version.

At the first level we should add a property 'version' .

I think the content should be the same that the one displayed in the 'about'

![image](https://user-images.githubusercontent.com/1484241/127171691-e96bc55f-7e53-4c12-bffa-554348013008.png)

**Comment by targos** [comment]
I think the `.nmrium` version should be different than the version of the component. Otherwise there is nothing to put unless you are in a release.

I suggest to just use an incremental number, unless more complexity is necessary.

**Comment by lpatiny** [comment]
Yes you are right. Current version should be version '1'.

**Comment by hamed-musallam** [comment]
done in eb50753 and 44e3fff
