### ISSUE TITLE
Problem after update to the last version of Vite and Node 

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1188]
@targos 

After we updated to the last version of  Vite and Node a problem raise in the development mode when making any changes the compiler works and generates a dist folder that contains a compiled version of the file that we work on it.

**Comment by targos** [comment]
@hamed-musallam I cannot reproduce... I updated the dependencies again. Can you retry with the latest master, and after running `npm ci` ?
If it still happens, please give me a more detailed explanation on how to reproduce.

**Comment by hamed-musallam** [comment]
@targos 
yes, I reinstalled dependencies using npm ci but I still get the same problem once I run the project, for example as you can see below there is a dist folder that contains a compiled file of the component that I make changes to on.
![image](https://user-images.githubusercontent.com/35760236/127497249-3769ad8a-6fa7-4541-88d9-bb6037730e8e.png)

**Comment by targos** [comment]
Please give me steps to reproduce.
Also what does `node -v` and `npm -v` print for you?

**Comment by hamed-musallam** [comment]
what I did as follow,
1- update to the last version of node and vite
2- npm start 
3- make any change on any file 
you will see a dist folder is generated at the same level where you making the changes, this folder contains   .js files that you changed.

![image](https://user-images.githubusercontent.com/35760236/127499847-b1fd2592-8a27-4c74-9d89-57f590bb1cc9.png)

**Comment by targos** [comment]
@stropitek Could you try on your Windows machine? It doesn't happen on my Mac.

**Comment by stropitek** [comment]
No I can't reproduce this on my Windows machine. I edited the exact same file but it doesn't generate any additional file

**Comment by hamed-musallam** [comment]
@targos @targos 

thanks for your help, i found the problem it comes from an extension that I installed on VS code https://github.com/Wscats/compile-hero
