### ISSUE TITLE
Add jsdoc

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1189]
@hamed-musallam Please could you add some jsdoc above all the properties with `@default` if there is a default value.

https://github.com/cheminfo/nmrium/blob/943432ef6dffba3a4c747d7a0d1fb3b6a2a52286/src/component/reducer/Reducer.ts#L128-L188

**Comment by hamed-musallam** [comment]
done in https://github.com/cheminfo/nmrium/commit/c798f9c42b902ce2074950db92de22965323e88b
