### ISSUE TITLE
Could we use only string everywhere ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1190]
Currently there is apparently a mix between string and number.

I think we could enforce it as a string. @hamed-musallam could you have a look at this ? In fact Datum2D.id is only string as I would expect.

https://github.com/cheminfo/nmrium/blob/eb507532f3846ce6ab5316460b5eedddc5a9b9be/src/data/data1d/Spectrum1D.ts#L108-L109

**Comment by targos** [comment]
I removed `number` nothing broke.
