### ISSUE TITLE
Why is 'j' not plural

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1214]
Seems that the 'j' property that is an array is not plural. It should be `js`.

@jobo322 What do you think. Is this correct in NMR-processing (meaning `js`) ? Otherwise it should be changed.

![image](https://user-images.githubusercontent.com/1484241/131131680-483a8ccf-091c-4217-9b89-e0783157bd0d.png)

**Comment by lpatiny** [comment]
https://github.com/cheminfo/nmrium/blob/3002d78cba357697aae2d7b7c79306860b2eae93/src/data/data1d/detectSignal.js#L20-L25

In fact this is a bug. @jobo322 Could you update the project https://github.com/cheminfo/multiplet-analysis so that it uses the new format, publish it as a breaking change and update nmrium ?

**Comment by hamed-musallam** [comment]
@jobo322 
we have to take care of the last changes in data migration

**Comment by jobo322** [comment]
@lpatiny There is a PR for this refactor in [multiplet-analysis](https://github.com/cheminfo/multiplet-analysis/pull/35)

**Comment by jobo322** [comment]
it is fix in eeb68f0
