### ISSUE TITLE
Add a submenu to paste ACS string

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1217]
This feature should be marked 'experimental' and should only appear if in the global preferences we activate the experimental features.

Add a submenu called:

`Import from publication string`

![image](https://user-images.githubusercontent.com/1484241/131243468-c9900294-3164-4957-bd40-4934563b50ea.png)

This will open a dialog box in which there is a textarea and you can paste something like:

```
	1H-NMR (400 MHz, CDCl3) 5.96 (dd, J1 = 10.0 Hz, J2 = 5.4 Hz, 1 H), 5.71 (dd, J1 = 
	10.1 Hz, J2 = 1.1 Hz, 1 H), 5.14 (br. s, 1 H), 4.71 (dd, J1 = 11.1 Hz, J2 = 3.7 Hz, 1 H), 
	4.07 (sept., J = 6.2 Hz, 1 H), 2.41 (dd, J1 = 17.7 Hz, J2 = 11.2 Hz, 1 H), 2.23 (dd, J1 = 
	17.7 Hz, J2 = 4.1 Hz, 1 H), 1.29 (d, J = 6.2 Hz, 3 H), 1.19 (d, J = 6.1 Hz, 3 H), 1.00 (t, 
	J = 7.8 Hz, 9 H), 0.63 (q, J = 7.8 Hz, 6 H).
```

Once the user validates the dialog box we should have an action that will `Resurrect` this string:

1.  In nmr-processing call `resurrect`. This will return an array of ranges
2. Call in nmr-processing: `rangesToXY`
3. Add the spectrum in NMRium

This is something similar to the prediction of a 1D spectrum and will only work on 1D.

@hamed-musallam could you start to add this code but currently `resurrect` and `rangesToXY` do not exist !

**Comment by hamed-musallam** [comment]
@lpatiny 
the first part is done, I'm waiting for the function that you are working on

**Comment by lpatiny** [comment]
For testing purpose please put as default value:
`1H NMR (CDCl3, 400MHz) δ 10.58 (b, 1H), 7.40 (d, 1H, J = 8.0 Hz), 6.19 (d, 1H, J = 7.6 Hz), 4.88 (s, 1H),  2.17 (s, 3H), 1.02 (s, 9H), 1.01 (s, 9H), 0.89 (s, 9H)`

Once the dialog is validate please call from 'nmr-processing'
- https://github.com/cheminfo/nmr-processing/blob/master/src/utilities/resurrect.js to get ranges
- const signals = ranges.map(range => range.signals[0])
- nmr-processing: signalsToXY

It will require some fine tuning after because resurrect provides information about the nucleus, frequency and solvent.

**Comment by hamed-musallam** [comment]
@lpatiny 
what do you mean with " Once the dialog is validate " I only check if the input is empty or not is there special validation I have to do?

**Comment by hamed-musallam** [comment]
@lpatiny 
there are still some keys that are required for signalsToXY function to work like atomIDs.
I get this error when running the function with the current array of signals 
![image](https://user-images.githubusercontent.com/35760236/135460418-097b25d2-2677-498e-9eb2-f894f3d55d51.png)
![image](https://user-images.githubusercontent.com/35760236/135460994-a5d707e3-7538-4d9f-88a4-8aa72d347aa8.png)
