### ISSUE TITLE
Add rangesToXY

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1218]
In nmr-processing we should have a ' rangesToXY' public method

https://github.com/cheminfo/nmr-processing/issues/91

**Comment by jobo322** [comment]
@lpatiny  would it have peaks in the structure of those ranges?

**Comment by lpatiny** [comment]
We will likely not have the peaks.

One of the goal is to be able to display a `resurrected` spectrum

https://github.com/cheminfo/nmr-processing/blob/master/src/utilities/resurrect.js

So to display the corresponding spectrum to something like 

```
H-NMR (CDCl, 300 MHz) 3.68 (s br, 2H), 3.70-3.74 (m, 4H), 3.93 (dd, 1H, J = 9.7, 
J2 = 3.7), 4.49 (d, 2 H, J = 4.1), 4.56-4.61 (m, 1H), 5.12 (s, 2H), 5.81 (d, 1H, J = 7.5), 
7.24-7.37 (m, 10H).
```

and the code that allows to generate the ranges from this string (`resurrect`) is more or less working. 

However when we parse this string we don't have all the signals but sometimes only ranges and also sometimes `broad` signals (`s br`) and `multiplet` (`m`) and somehow we need to represent them correctly in the final spectrum.
