### ISSUE TITLE
Possibility to display the integral for a range

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1225]
Would be nice to have a toggle icon that allows to show / hide the integral directly from the range.

![image](https://user-images.githubusercontent.com/1484241/131793083-e6fc9aef-88c5-4d9e-b47b-7a57c0ee25af.png)

Somehow the integral button becomes useless but useful for education.

**Comment by hamed-musallam** [comment]
@lpatiny 
you mean hide/show Rel.H  column, do you want the same for the label under the green rectangle.

**Comment by lpatiny** [comment]
I mean the possibility to draw on the spectrum the integral

![image](https://user-images.githubusercontent.com/1484241/131966654-32873ca6-e698-4975-a156-a6ae7deb9cbf.png)

Like you would have draw the integral using the tool:

![image](https://user-images.githubusercontent.com/1484241/131966687-730cf86e-1c9e-4696-a625-c8a74bfe86d7.png)

I think in the future we will allow either the integral option or the range option but not both. Displaying the integral is interesting to find out if your baseline is ok and for educational purpose. For educational purpose we may just leave the integral button but for specialist they will always use range button but sometimes would like to see the drawn integral. This is the reason for this toggle option.

If for now adding this feature is a big hack it is better to leave it for later.
