### ISSUE TITLE
Remove completely the help from NMRium

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1226]
@hamed-musallam please could you remove completely the code related to the help ?

![image](https://user-images.githubusercontent.com/1484241/131809827-8b1e6a0e-ab0e-40a9-bce8-315baeff8a0b.png)

We will focus on the help on https://docs.nmrium.org and maybe we will add links that open in a new page to the corresponding tool in the future but will abandon the help in the component itself (at least for now). We may come up with a better idea maybe once (like 'extended' tip information when we stay over a tool).

**Comment by hamed-musallam** [comment]
@lpatiny 
Do you mean when the mouse comes over the tool you need to remove it completely but it works perfectly in all cases, Can I ask why? because it is a hidden feature it's not going to work unless you come over the button for 2 seconds or press CTRL and mouse over the button.

**Comment by hamed-musallam** [comment]
@lpatiny 
what about the short text that appears in the footer?

**Comment by lpatiny** [comment]
To reproduce this you should press CTRL and go over the zoom for example

![2022-01-21 14 10 33](https://user-images.githubusercontent.com/1484241/150532679-61ca2894-add4-43e0-bdb1-85f59c9198c8.gif)

@Sebastien-Ahkrin you may remove all the related code for this help feature. We will reimplement it once in a diferent way.

**Comment by Sebastien-Ahkrin** [comment]
> To reproduce this you should press CTRL and go over the zoom for example
> 
> ![2022-01-21 14 10 33](https://user-images.githubusercontent.com/1484241/150532679-61ca2894-add4-43e0-bdb1-85f59c9198c8.gif)
> 
> @Sebastien-Ahkrin you may remove all the related code for this help feature. We will reimplement it once in a diferent way.

Ok!
