### ISSUE TITLE
Hide button multiple spectra alignment if not more than 1 spectrum

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1227]
If there is not more than 1 (1D) spectrum this button should be hidden:

![image](https://user-images.githubusercontent.com/1484241/131810389-d050d8b9-8396-4069-bcb2-3915037cb91e.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
What is the case that you have because, in this case i have only one spectrum and the button is not shown
![image](https://user-images.githubusercontent.com/35760236/131811610-c94291af-a521-40a1-9f87-bfa6d300b390.png)
