### ISSUE TITLE
Hide multiple spectra analysis button if no spectrum

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1229]
If there is no spectrum  (in fact less than 2) this button should be hidden:

![image](https://user-images.githubusercontent.com/1484241/131810732-173227c3-5c9e-4a96-9c50-1c330c363f9e.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
what is going to happen I we have ft and fid spectra?

**Comment by lpatiny** [comment]
Do we really need an active spectrum ? The ranges defined in multiple spectra are not attached to a spectrum seems to me (or at least should not).
So having more than 1 spectrum (after FT) and being in FT mode should be enough to display the button. No need for a selected spectrum.
