### ISSUE TITLE
Resurrect spectrum : display ranges

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1250]
When resurrecting spectra we calculate internally signals and ranges. They should be displayed as well.

**Comment by hamed-musallam** [comment]
@lpatiny @jobo322 
We have a problem when display ranges
1- The absolute is not exists.
2- from and to keys always have the same value.

**Comment by jobo322** [comment]
let me check if this problem is fixed with the new version of nmr-processing.

**Comment by hamed-musallam** [comment]
fixed with the version 3.2.0 of nmr-processing
