### ISSUE TITLE
Resurrect spectrum: broad and massif problem

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1251]
When trying to resurrect

```
1H NMR (CDCl3, 400 MHz) d: 5.55 (d, J = 8.1 Hz, 1H, H-10 ), 4.72 (br s, 1H),
	4.29 (m, 1H, H-50 ), 3.53 (m, 2H, H-30 , H-40 ), 3.42  
	(m, 1H, H-20 ), 3.15 (dd, J = 6.0 Hz, J = 10.0 Hz, 1H, H-3), 3.00 (td, J = 11.0 Hz,  
	J = 4.5 Hz, 1H, H-19), 1.69 (s, 1H, H-30)
```

The spectrum I obtain does not contain 8 signals as expected and has a signal around 0.3 that should not be there.

@jobo322 Could you investigate and try to find a solution for `m` and `s br`

![image](https://user-images.githubusercontent.com/1484241/135707311-53acc5fe-2e4b-43e4-9e8f-f7e927b1dc18.png)

**Comment by jobo322** [comment]
@lpatiny currently, we deal with `s br` and `m` in the function [rangesToXY](https://github.com/cheminfo/nmr-processing/blob/main/src/ranges/rangesToXY.ts#L88-L112).

**Comment by jobo322** [comment]
the code of resurrect is maybe failing because the result from your ACS string contains 8 ranges, one of them has wrong information: 
```json
[
  {
    "from": 5.536125,
    "to": 5.5638749999999995,
    "signals": [
      {
        "delta": 5.55,
        "js": [{ "coupling": 8.1, "multiplicity": "d" }],
        "multiplicity": "d"
      }
    ],
    "integration": 1
  },
  {
    "from": null,
    "to": null,
    "signals": [{ "delta": null, "js": [] }],
    "integration": 1
  },
  {
    "from": 4.28625,
    "to": 4.29375,
    "signals": [{ "delta": 4.29, "js": [], "multiplicity": "m" }],
    "integration": 1
  },
  {
    "from": 3.5262499999999997,
    "to": 3.53375,
    "signals": [{ "delta": 3.53, "js": [], "multiplicity": "m" }],
    "integration": 2
  },
  {
    "from": 3.41625,
    "to": 3.42375,
    "signals": [{ "delta": 3.42, "js": [], "multiplicity": "m" }],
    "integration": 1
  },
  {
    "from": 3.1262499999999998,
    "to": 3.17375,
    "signals": [
      {
        "delta": 3.15,
        "js": [
          { "coupling": 6, "multiplicity": "d" },
          { "coupling": 10, "multiplicity": "d" }
        ],
        "multiplicity": "dd"
      }
    ],
    "integration": 1
  },
  {
    "from": 2.963125,
    "to": 3.036875,
    "signals": [
      {
        "delta": 3,
        "js": [
          { "coupling": 11, "multiplicity": "t" },
          { "coupling": 4.5, "multiplicity": "d" }
        ],
        "multiplicity": "td"
      }
    ],
    "integration": 1
  },
  {
    "from": 1.68625,
    "to": 1.6937499999999999,
    "signals": [{ "delta": 1.69, "js": [], "multiplicity": "s" }],
    "integration": 1
  }
]
```

**Comment by jobo322** [comment]
the spectrum of the last ranges (ignoring the wrong range) 



![Image](https://user-images.githubusercontent.com/12143935/217143199-bec88f23-aaab-47ea-8a85-0d5c5a7082bc.png)

a zoom up of region 2.5 to 4



![Image](https://user-images.githubusercontent.com/12143935/217143325-d8074f6e-5c17-484f-9682-ef0bcec11731.png)

**Comment by jobo322** [comment]
With the last update of nmr-processing we will obtain

![Image](https://user-images.githubusercontent.com/12143935/217286898-c228c2ed-76b2-4fd7-8ca2-7a7f2b2fe3a9.png)
