### ISSUE TITLE
Opening panel load and display the database

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1254]
When opening the Database panel, load the database:

(call `getDatabase` in the last version or `nmr-processing`)

(we should not make the call before opening the first time this panel)

Please plan directly that there may be many databases !!!

So in the state the database should be an object and this default database could have as key `Solvent`.

I would directly plan a more complex structure like (not sure about the names ...)

```json
databases: {
  data: {
     solvent: { // when we load a database we should specify a name
        description: 'Solvent database',
        value: getReference()
    }
  }
}
```

**Comment by hamed-musallam** [comment]
@lpatiny 
I can not find getDatabase function from the last published nmr-processing, Does it exported?

**Comment by targos** [comment]
Nite that it should be "solvent".
Solvant is French

**Comment by lpatiny** [comment]
> Note that it should be "solvent". Solvant is French

Thanks I corrected my issue description.

**Comment by hamed-musallam** [comment]
@lpatiny 
I confused about the structure that you suggested, how it linked with the 2 solvents database is it going to be under data object

**Comment by hamed-musallam** [comment]
@lpatiny 
Also what I see solvent, names, and ranges but I can not find meta and smiles, what I have to do with it?

**Comment by hamed-musallam** [comment]
@lpatiny 
why did it suppose to be in the main state if we only need it for display in the table?

**Comment by lpatiny** [comment]
for now you can join those 2 database:

database = [...carbonImpurities, ...protonImpurities]

You are right there are currently no smiles. I will add some.

I don't remember to have say it should be main state.  Local state should be suitable for this project.

**Comment by hamed-musallam** [comment]
@lpatiny 
you request to have two dropdown lists the first one is for the database for now we have only solvent and the other works as a filter by solvents for know I see that we have one common value is it going to be changed? or just we can have an input field that we can search inside all the values not for solvent only
