### ISSUE TITLE
Is it normal to have 'y' in the exportation file ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1261]
![image](https://user-images.githubusercontent.com/1484241/136027461-12b1ab0a-bc79-4778-aa8a-c1fbba0399db.png)

I thought we would have only `x`, `re`  and `im`. `im` being null if we have only the `re` part.

**Comment by hamed-musallam** [comment]
@lpatiny 
yes you are right ,it is suppose to have only x, re, and im but I use y internally to switch between re and im and it not suppose to be exported, what is the case that you have y when export?

**Comment by targos** [comment]
Yes, it doesn't seem to be necessary to have this `y` in the main state.

**Comment by hamed-musallam** [comment]
@lpatiny 
The main reason that I have y is to switch between imaginary and real spectrum from one place and always work with y instead of having a function that always check if it's imaginary or real.

**Comment by hamed-musallam** [comment]
close b3a187585e2db0ff191e43c25d0c408e9f967087
