### ISSUE TITLE
Minimal .nmrium file

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1262]
I would like that the following .nmrium could be loaded:

```json
{
  "spectra": [
    {
      "id": "abc",
      "data": {
        "x": [1, 2, 3, 4, 5, 6],
        "re": [2, 3, 4, 3, 2, 1]
      }
    }
  ]
}
```

**Comment by lpatiny** [comment]
In this extreme case we should consider that it is a spectrum after FT (not FID)

**Comment by hamed-musallam** [comment]
@lpatiny 
it would be more suitable if we handle this case as a migration  case with special version number. what do you think ?

**Comment by hamed-musallam** [comment]
@lpatiny 
Based on what have, We need one more piece of information {dimension:1}

**Comment by hamed-musallam** [comment]
@lpatiny what about this issue?

**Comment by lpatiny** [comment]
We can check if 'x' and 're' and it is 1D. 

Please have a look for 2D what are the required properties.

**Comment by hamed-musallam** [comment]
@lpatiny 
This is the minimum object that you can use to load spectrum 

{
  "spectra": [
    {
      "data": {
        "x": [1, 2, 3, 4, 5, 6],
        "re": [2, 3, 4, 3, 2, 1]
      },
       "info": {
        "dimension":1
       }
    }
  ]
}
