### ISSUE TITLE
Flip bug

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1265]
When you flip the preferences you have this bug in google chrome

![image](https://user-images.githubusercontent.com/1484241/136933566-5239ccd3-a5aa-4d8a-99f2-2aaf3a366a53.png)

this bug is not present in firefox

![image](https://user-images.githubusercontent.com/1484241/136933769-12dfc5fc-7350-4192-81b3-1e2fb192303d.png)

And actually the same bug is present on www.chemcalc.org when you flip the chart to display the values instead of the chart

![image](https://user-images.githubusercontent.com/1484241/136933891-3883368e-8471-4fc7-b5be-260358412cae.png)

This bug could be related to a Chrome update.

@hamed-musallam could you try to determine what is the problem and how to solve it ?

**Comment by hamed-musallam** [comment]
@lpatiny 
yes, it's a bug in chrome and to be specific when using CSS attribute backface-visibility: hidden not working in a proper way so for now we can just hide the front card once the card flip.

**Comment by hamed-musallam** [comment]
https://github.com/AaronCCWong/react-card-flip/issues/76
