### ISSUE TITLE
Speed for database display

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1275]
![image](https://user-images.githubusercontent.com/1484241/138472447-c25ea3be-af9e-4485-8c41-53d7ddf77906.png)

I think that currently when we display the solvents panel it will render all the SVG at once. This is quite problematic because it is a very consuming task. Only the currently displayed molecules should be actually rendered. I guess this is easy to implement but I have no idea how to do.

If you don't know how to do you may ask Michael for advice.

**Comment by hamed-musallam** [comment]
closed by 9548d62253b24e85243e587e389882fd962c81cb ,
f7392cc42c48b0f14515c3d602527de6284e038a
