### ISSUE TITLE
Columns size change

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1278]
When scrolling the solvent database the column change continuously.

I think the width should stay constant. Maybe based on the first display.

![2021-10-29 07 32 54](https://user-images.githubusercontent.com/1484241/139381274-b2333ed4-1a5c-4054-98cb-1b99d612a9d0.gif)

**Comment by hamed-musallam** [comment]
done in 8991368fc4fe4d6edf0b576fc24aa40f2c959024
