### ISSUE TITLE
Preferences superimposition in database lookup

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1287]
![image](https://user-images.githubusercontent.com/1484241/139804310-03fd8ac1-511a-4929-9c59-5accf1290e2c.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
this problem is not exists in the current version, can you check again but before that refresh the browser

![image](https://user-images.githubusercontent.com/35760236/139818132-124d0170-28cf-4eb4-93d0-9f5db54f2ac6.png)
