### ISSUE TITLE
Why THF is singulet ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1288]
In database lookup why THF is singulet ?

![image](https://user-images.githubusercontent.com/1484241/139804584-36043adb-fadd-4e50-90b2-f75e24e51053.png)

**Comment by jobo322** [comment]
@lpatiny THF appear as `singulet` because the signals in the database has not J-coupling information.

![image](https://user-images.githubusercontent.com/12143935/139863667-007f0372-1b05-4802-9545-898214d52026.png)

**Comment by lpatiny** [comment]
It has no Js because it is a mess. It should actually be a 'm' (multiplet). I guess at the level of the signal we could add a multiplicity 'm'.

We should try to make the distinction between 'massif' and 'multiplet'. And we need to resurrect them differently as well.

I think 'multiplet' should have a `multiplicity` property at the level of the signal while for 'massif' we should have a `multiplicity` property at the level of the range.

What is the current status for this ? There could be some other solutions.



![image](https://user-images.githubusercontent.com/1484241/139874884-7fb77d59-a1c1-41d5-a1ef-e05d5dd387b4.png)

**Comment by jobo322** [comment]
it is related with at the level of resurrection with:

- https://github.com/cheminfo/nmrium/issues/1251

currently, it does not appear as a `s`  but not appear as `m`



![Image](https://user-images.githubusercontent.com/12143935/217143713-21f1a815-bcf9-4060-a909-7399aa017aeb.png)

**Comment by jobo322** [comment]
it was fixed in c92b135e46a747a0c5ccb47f934d2e9d112ac932 and the version 9.7.0 of nmr-processing contain the correct multiplicity
