### ISSUE TITLE
Add experimental feature to auto assign spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1290]
Small icon with 'automatic assignment'

This button should only be available if 
- there is a structure
- there are some ranges

On click we need to call a method 
`getAssignments({ spectra: SpectraData[], molecule: Molecule }, options)`

[Options structure](https://github.com/cheminfo/nmr-processing/blob/getAssignment/src/assignment/getAssignments.ts#L44-L88)

SpectraData structure is `SpectraData1D | SpectraData2D`

```
interface SpectraData1D {
  id?: string;
  ranges: NMRRange[];
  info: any;
}

interface SpectraData2D {
  id?: string;
  zones: NMRZone[];
  info: any;
}
```

This method will return an array of:
```
{
  score: number,
  assignments: SpectraData[]
}
```

We add a drop down menu in the Range Panel header with:
- `Original ranges`
- `Proposal score: 0.96`
- ...

**Comment by hamed-musallam** [comment]
@lpatiny 

I found that the molecule atoms diaIDs not registered in the Highlights once we create it but it registered once we assign it to a signal so based on what you need this can not be work in the auto Assignment.

**Comment by hamed-musallam** [comment]
@lpatiny @jobo322 

it seems that the assign1DSpectrum function is not exported from nmr-processing package.

**Comment by jobo322** [comment]
There is a PR in [nmr-processing](https://github.com/cheminfo/nmr-processing/pull/148)
