### ISSUE TITLE
Failed to compile when adding the component to a new project

### ISSUE THREAD

**Issue by redhaam** [cheminfo/nmrium#1300]
When trying to use NMRium with the version 0.18.3 on a new React project I got this error on the build phase :

Node version : 16.11.0
React v: 17.0.2

```./node_modules/nmrium/lib/component/NMRium.js 149:19
Module parse failed: Unexpected token (149:19)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   useEffect(() => {
|     if (checkActionType(state.actionType)) {
>       onDataChange?.(state);
|     }
|   }, [onDataChange, state]);```

**Comment by hamed-musallam** [comment]
@lpatiny 
i think we should change the ts compiler target from es2020 to ES2019, which transpile ?. and ??.

**Comment by hamed-musallam** [comment]
@lpatiny 
or we can get rid of these operators but I think we use it in different places not in this spot only

**Comment by targos** [comment]
Ultimately, I think this is an issue with the React project, which should be setup to transpile these. the nmrium component is not the only project which uses optional chaining on npm.
