### ISSUE TITLE
Range settings for J Graph

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1302]
In the range preferences we could add a new option

J Graph tolerance for: 
- 1H: 0.2Hz
- 13C: 2Hz

If the difference between couplings constants are less than 0.2Hz (or 2Hz) we should add the dotted lines

**Comment by hamed-musallam** [comment]
@lpatiny 
What about the path? it is not going to be straight.

Do want to have a straight line based on the first value and the last value if we have more than 2 couplings related to each others and in this case some of the points the line will not cross from the center

**Comment by lpatiny** [comment]
Seems to me that the path should always be straight. You may take the average value for now.
