### ISSUE TITLE
J Graph: Icon is inverted compared to integral 

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1306]
![image](https://user-images.githubusercontent.com/1484241/144098743-c110adb3-bf65-46ca-b4c9-c3508bfcd9c2.png)

The icon should be black to display the JGraph. Currently it is the opposite.

By default the JGraph should not be displayed.

**Comment by hamed-musallam** [comment]
@lpatiny 
this is the case for me, by default, the J Graph is not displayed and once you toggle the button it's become with gray background.

it's strange you have different behavior!!

**Comment by lpatiny** [comment]
I don't know but indeed it is correct. Thanks.
