### ISSUE TITLE
set MF automatically for automatic ranges/zones peaking

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#1312]
the idea is to have the relative integration based in MF if a molecule exists when we run automatic ranges/zones picking either one by one or all spectra at once

**Comment by hamed-musallam** [comment]
@jobo322 can you give me more details, what is the formula that we based on it I'm going to calculate the relative value and what is going to happen if we change the relative integration manually because currently, we rely on the absolute to calculate the relative as I remember.

**Comment by lpatiny** [comment]
When we click on auto range picking or if we click on the multiple spectra autorange picking (the icon in the spectra panel) we should set automatically the total integration sum if it was not yet set (meaning I guess the value is 100).

This means that if we have a drawn molecule it would have the same effect as clicking on 'Set' 

![image](https://user-images.githubusercontent.com/1484241/145081734-d68e0d6a-b41f-4d39-ae19-c2ef80362329.png)

We should only do this for 1D spectra !!!

We should also take care about the nucleus and do it for the correct nucleus based on the spectrum information.

**Comment by hamed-musallam** [comment]
@lpatiny 

but I things it is not good practice because how the user can decide if he has more than one molecule in the structure panel.

**Comment by hamed-musallam** [comment]
@hamed-musallam 

wireframe of the new component

![image](https://user-images.githubusercontent.com/35760236/145184034-4a662ca4-4d6f-4e85-8af4-f6db8cb82bea.png)

**Comment by hamed-musallam** [comment]
close 3d0ffd13d1bdffb2d15019b7a1f4d15a04ac6db9
