### ISSUE TITLE
Wrong highlight position

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1313]
@hamed-musallam please could you check why with ehtylvinylether example the highlight of the range is completely out of range

![image](https://user-images.githubusercontent.com/1484241/145080810-78a76e31-1bdf-4bb8-ac20-acefca2f15a0.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
I can not reproduce it

![image](https://user-images.githubusercontent.com/35760236/145090577-e2eb7b1e-4636-4d99-a876-6215999aa666.png)

**Comment by lpatiny** [comment]
Better I took a screen snapshot ... but I can not reproduce it neither. No idea what happened but I close the ticket for now.
