### ISSUE TITLE
Duplicate info in ranges

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1315]
In ranges we have a property that seems useless:
```
 "tableMetaInfo": {
    "isConstantlyHighlighted": true,
    "signal": {
      "kind": "signal",
      "id": "W1aeeaR1",
      "originDelta": 3.026922690934219,
```
Please remove this tableMetaInfo.

**Comment by michaelwenk** [comment]
I checked the tableMetaInfo property which we use for the range and zone table rowspan, signal info etc. and neither in data  itself nor in the exported file is that tableMetaInfo findable. 

It exists as additional data for the two tables mentioned above. And it includes additional data only. 

@targos What do you think?

**Comment by targos** [comment]
I don't know what this is about

**Comment by lpatiny** [comment]
This property in indeed not in the global state so no problems. Thanks !
