### ISSUE TITLE
Processed file can not be loaded on dev.nmrium.org

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1316]
![image](https://user-images.githubusercontent.com/1484241/145858381-85f3b8bc-7b6b-41f9-89a8-032da4846829.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
The Jcamp file does not exist anymore at this URL https://cheminfo.github.io/nmr-dataset-demo/cytisine/13C_Cytisin_600_fid.dx
and in the same time we have the row data inside the JSON so What do you want to have The jcamp Url or Row Data

**Comment by lpatiny** [comment]
@hamed-musallam Thanks my fault indeed.

Please replace it with:

https://cheminfo.github.io/nmr-dataset-demo/cytisine/13c.fid.jdx
