### ISSUE TITLE
Why nH ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1318]
https://github.com/cheminfo/nmrium/blob/a46d63ceb7ad1008b07dac13b84c57246851fd4c/src/data/data1d/Spectrum1D/ranges/detectRanges.ts#L14-L15

I think this auto range picking also works with carbon and other elements.

It seems also that we need to know BEFORE calling the method the total number of elements.

@jobo322 Could you check why we call this nH and rename it to integration ? (better name ?)

@hamed-musallam Can we get the number of atoms before calling the peak picking ?

**Comment by jobo322** [comment]
@lpatiny I think a better name would `totalIntegration` I think `nH` is focussing only in proton spectra.

**Comment by lpatiny** [comment]
@jobo322 Please change this property name and check if it has any impact in nmr-processing.

**Comment by hamed-musallam** [comment]
@lpatiny 
you mean the number of atoms of the selected nucleus from the molecule, but which of the molecules I will take the number of atoms from it, I mean based on what? the first one or selected molecule on Ranges options?

**Comment by jobo322** [comment]
Should [this interface](https://github.com/cheminfo/nmrium/blob/master/src/data/data1d/Spectrum1D/ranges/detectRanges.ts#L8-L23) use the types from mljs/ml-gsd or cheminfo/nmr-processing
