### ISSUE TITLE
panel preference changes are not saved to local storage

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#1325]
According to @Sebastien-Ahkrin analysis, there are multiple issues with these, one of them being that the state is duplicated and not updated everywhere. We need to redesign this so that there is only one source of truth for this state.

**Comment by Sebastien-Ahkrin** [comment]
To me: the useEffect isn't updated and the value returned by the useStateWithLocalStorage isn't used anymore.
Inside the hook i should remove the useEffect to update the state in the "setData" callback (should be better)

The context is updated by "SET_PANELS_PREFERENCES" in RangedPreferences
The bug may be in every panel

**Comment by lpatiny** [comment]
I try other panels and indeed the bug is there as well.

**Comment by hamed-musallam** [comment]
Today I pulled the last changes I can not see the preferences reducer it's totally removed !!!

**Comment by hamed-musallam** [comment]
@lpatiny can I follow up with you and @Sebastien-Ahkrin  to see the process of refactoring or what is the plan?

**Comment by hamed-musallam** [comment]
@Sebastien-Ahkrin I use useStateWithLocalStorage hook to save directly to the local storage but we read it once in the context INIT_PREFERENCES.
