### ISSUE TITLE
Manual range picking can crash

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1328]
If the selected range is too big the system can crash.

Should we use the simple algorithm in those cases ?

**Comment by targos** [comment]
@lpatiny will explain what to do

**Comment by lpatiny** [comment]
@Sebastien-Ahkrin I create a branch to work on this topic

https://github.com/cheminfo/nmrium/pull/1356

Currently I added the code that prevents the system to crash but we should also display the a message. No idea how to do this especially that the data folder is not aware of react and contains only code for processing of data. I guess throwing an error that would be cactch in the react part of the application could help. Anyway this is the code to change: 

https://github.com/cheminfo/nmrium/blob/0c80cfbd5ebf1c5482edf464997ab6019815c61b/src/data/data1d/Spectrum1D/ranges/detectSignal.ts#L36-L40
