### ISSUE TITLE
Zone picking and column label

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1334]
In the column of zones there should be the information about F1 and F2. Currently for COSY it appears as 1H, 1H

![image](https://user-images.githubusercontent.com/1484241/150771356-12d1bdb9-f600-483b-9d26-8b6ee4bd1166.png)

**Comment by lpatiny** [comment]
It could be something like:

![image](https://user-images.githubusercontent.com/1484241/151030598-646ddcbf-b7b4-4d0b-8ca4-795596c901dd.png)

The text for F1, F2 could be smaller, top left and dark grey for example.

**Comment by targos** [comment]
Closed by fbcad4791ede14db2937684f1e04f098c37e7c07
