### ISSUE TITLE
Can not change 2D references

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1338]
Changing the value would not shift the spectrum but change the position of the zones.

![image](https://user-images.githubusercontent.com/1484241/150773342-476da18a-8aa7-4ca4-b6df-81cb7562ffe6.png)

**Comment by lpatiny** [comment]
I can not reproduce this problem. @ReinerD could you test and reopen this issue if it does not work ?

When changing the values in the zones table the filters are being added correctly

![image](https://user-images.githubusercontent.com/1484241/151119381-8719ca14-f8a7-4365-bfc2-e7e9c2399085.png)

**Comment by ReinerD** [comment]
https://user-images.githubusercontent.com/10863233/151121055-660a8429-9614-4583-b25d-4a7ea953e677.mov

I can reproduce it (see recording)

**Comment by targos** [comment]
The recording corresponds to what we experienced yesterday with @Sebastien-Ahkrin

**Comment by lpatiny** [comment]
Quick way to reproduce:

1. Load ethylbenzene
2. Make automatic peak picking on all the spectra at once
3. You can change a range value in 1D, you see all the annotations move AND the spectrum
4. you can change a zone value in 2D, you see all the annotations move but NOT the spectrum

When we change a range or zone value the system will add the corresponding filter. This is a filter than can be present only once so if you change again the value will be updated.

So it seems that when calculating the SVG containing the path of the contour plots of the 2D the shiftX and shiftY are not taken into account

![2022-01-26 11 13 36](https://user-images.githubusercontent.com/1484241/151145634-191a9264-2e65-4199-ba99-f69f34a5b51a.gif)
.
