### ISSUE TITLE
Add the possibility to 'label' the molecule

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1342]
It is possible to draw many molecules and sometimes we would like to assign them separately and mainly to integrate them separately.

In a first step it would be nice if we can label the molecule

![image](https://user-images.githubusercontent.com/1484241/151120341-2fa94c28-1f12-4c24-ab51-142849fbff7f.png)

- Add a text input 'label' on the same line of the molecular formula. Default value is 'P#' where '#' is the molecule index + 1.
- Save this in the state with the property 'label'
- Add also in the state a unique identifier like it is done for all the other properties

Currently we have:
![image](https://user-images.githubusercontent.com/1484241/151121016-29e2eadd-ece5-45fd-8b03-a13de4fac124.png)

But normally we have an ID
![image](https://user-images.githubusercontent.com/1484241/151121078-9c16c5fe-be02-4ede-94e3-6e5e3e9b2ab4.png)

**Comment by hamed-musallam** [comment]
@lpatiny 

When triggering save label? what bout adding a label input field in the structure modal instead of adding it the same line of the molecular formula? 

is the new molecules structure will look like 
```json
  "molecules":[
      {
        "id":"",
        "label":"P1",
         "molfile":""
      },
     // .....etc
  ]
```

**Comment by lpatiny** [comment]
We still need to define what is the default label ? 

Label should be P1, P2, P3, etc. If we had a new molecule we should the first non used P'x' label.

This default label can then be edited when you click on preset label. A label has to be unique and not empty !
