### ISSUE TITLE
Creating an empty molecule throws an error

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#1379]
Just open the molecule modal and click save:

![image](https://user-images.githubusercontent.com/2352663/154803569-ccb87cf8-4366-4a04-b03d-660d1aa997c9.png)

**Comment by targos** [comment]
The same happens if you click on the "Paste molfile" button.

**Comment by targos** [comment]
@lpatiny I think this should be fixed before the release.

**Comment by lpatiny** [comment]
@hamed-musallam Could you have a look on this. From the empty molecule just open the editor and save without drawing anything. You will get this error.

**Comment by hamed-musallam** [comment]
close a99d95c03c95aeaf7d54a3fcd695cd36d3754eea
