### ISSUE TITLE
Prediction panel

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1388]
By default it is hidden

There is a new mode 'Prediction'. In this mode:

- tools: zoom, export
- spectra, zones, ranges and the prediction panel

Prediction panel should allow to click to edit molecule, display preferences:

![image](https://user-images.githubusercontent.com/1484241/156121039-4ac8d001-c4f2-4c09-b201-74a775fa90aa.png)

And a button predict directly from the panel.

**Comment by lpatiny** [comment]
Could the background of the molecule be related to the color of the spectra ?

**Comment by lpatiny** [comment]
Could we do something about the color of the spectra predicted at once ?

We are predicting 5 spectra:
- 1H
- 13C
- COSY
- HSQC
- HMBC

The 4 first spectra should have the same color and the HMBC should have a lighter version of the same color. Like that if we have a light background color for the molecule we know to which spectra it belongs.

We could have a new color property at the level of the molecule state.

**Comment by hamed-musallam** [comment]
@lpatiny 
in Molecules Panel we save molecules at the global state, is it the same case for prediction? (share the same state) or it is going to be saved locally at the level of the component?

**Comment by lpatiny** [comment]
Same state. We could even have both panel (prediction and molecule) active at the same time and the molecule should then change in both panels.

**Comment by hamed-musallam** [comment]
close #1194
