### ISSUE TITLE
Add a new range from the panel menu

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1389]
Add the possibility to add a new range from scratch from the panel menu.

There should be a little '+' in the toolbar

![image](https://user-images.githubusercontent.com/1484241/156145550-3807a5f3-9808-4c9d-86b2-49a7a4f3a112.png)

That opens an empty dialog like the one obtained when editing a value

![image](https://user-images.githubusercontent.com/1484241/156145732-60cd44be-e57d-4c7a-984e-5a95f1223531.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
In the editing modal, it uses an existing range, which means the form, to values already specified. how do you think the user should fill  it? 

Are we have to add two input fields for from and to and what are the default values.

![image](https://user-images.githubusercontent.com/35760236/159232114-c65b91f7-489b-407b-a890-76e1ea2899ca.png)

**Comment by lpatiny** [comment]
Indeed we need to be able to edit the range

![image](https://user-images.githubusercontent.com/1484241/159333294-1c28d837-7f2c-4fce-bda5-2597ee2cccaf.png)

Default value could depend on the currently display screen and we take form 1/3 to 2/3 of the displayed zone. If the resize works well (see https://github.com/cheminfo/nmrium/issues/1441) I think this would be enough to resize the range.
