### ISSUE TITLE
Hide multiple spectra auto range picking

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1396]
If the range button is not active

![image](https://user-images.githubusercontent.com/1484241/156426731-07d43f94-cc74-4b38-bf84-6a81646056ec.png)

Then the multiple spectra analysis tool should also not be active.

![image](https://user-images.githubusercontent.com/1484241/156426666-6280691a-c09e-43cf-89ac-35669b32b57d.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
this button works one more function, it detects not only ranges but also zones

**Comment by hamed-musallam** [comment]
@lpatiny 
I will hide it based on what you proposed but you have to consider what is going to happen if we are in 2d mode
