### ISSUE TITLE
Possible workspaces improvements

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#1400]
Here are some ideas from Photoshop:

![image](https://user-images.githubusercontent.com/2352663/156514917-bc50bfb8-3468-44ed-8694-af40b122462b.png)

- Possibility to change the workspace
- Reset builtin workspace to the default value
- Create and delete custom workspaces
- Customize keyboard shortcuts differently per workspace

**Comment by lpatiny** [comment]
Closed by this huged refactor: https://github.com/cheminfo/nmrium/commit/cd0ccbd3eae286de7f55dd84367b6e39130d9156
