### ISSUE TITLE
Change of state and window size

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1406]
It would be nice that if you change the data property of NMRium the 'split' position between spectrum and panels does not change.

@hamed-musallam tell us if this seems to complex and if would be better to wait for a state rewrite.

![2022-03-03 22 08 10](https://user-images.githubusercontent.com/1484241/156653353-0b06e888-acb8-42c5-bcc9-6a0efdcc540b.gif)

**Comment by hamed-musallam** [comment]
@lpatiny 

because the super parent component will re-render every time you change the data that means no chance to prevent resetting the position of the splitter unless we save the value outside the component

**Comment by targos** [comment]
This is a single-page app, so technically it's possible to prevent unmounting the nmrium component.

**Comment by targos** [comment]
It's not possible to move between orgs. I'll copy the issue
