### ISSUE TITLE
dev.nmrium.org and example URL

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1410]
It would be nice that when you click on an example on https://dev.nmrium.org the URL changes to append the path of the example.

If we are using this changed URL we would directly load this specific example.

Like that we can easily send a link to a specific example on https://dev.nmrium.org, make back in history and we can also easily reload a specific example when we are developing NMRium.

@targos Any suggestions about how to develop this feature ?

**Comment by hamed-musallam** [comment]
@lpatiny 
we use MemoryRoute to keep the URL in the memory to prevent users in exercise or exam mode to reach the source of files

**Comment by lpatiny** [comment]
Good memory ! In the meantime we redirect students to https://www.nmrium.org/teaching so this is not a problem anymore and you may again add the URL on dev.nmrium.org.

**Comment by hamed-musallam** [comment]
closed by e32584f82d606d2c7e94df4063125b52b0b0ce80
