### ISSUE TITLE
simplify vertical zoom wheel behaviour

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1412]
Checking deltaY we can see that the mouse deals with acceleration.

The zoom modification should be directly related to deltaY. We will forget about this slow / fast story.

The behaviour in https://zakodium.github.io/react-plot/?path=/story/experimental-spectra-mass--advanced-mass-example seems more natural

The implementation is here: https://github.com/zakodium/react-plot/blob/main/src/hooks/useAxisWheelZoom.tsx

@hamed-musallam could you try to simplify the code in a new branch ?

**Comment by hamed-musallam** [comment]
closed by #1416
