### ISSUE TITLE
export as Jcamp

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1415]

**Comment by michelgravel** [comment]
That would be a nice feature!
It would allow to process an FID from a proprietary format, then save as JCAMP and use it on any platform, such as cheminfo or c6h6.

**Comment by lpatiny** [comment]
@jobo322 I guess saving the data as JCAMP-DX will also be managed by nmr-load-save ?

We will need to provide options for this feature:
- only FID
- only FT
- both

We we save FID that was processed we should ideally be able to reload it (like PH0, PH1 for example)

**Comment by jobo322** [comment]
@lpatiny, currently, we have the possibility to write an NMR jcamp file, it was tested in m-nova and topspin, I will add this possibility in nmr-load-save. in order to be able of reloading an FID processed in nmrium, we should apply a processing script that would check for PH0-1 in the file and LB too. it is not implemented yet. are you thinking to implement this in nmr-load-save?, I think we could add filters, so nmrium could apply those filters after the importation.

**Comment by michelgravel** [comment]
nmr-load-save is what I had in mind. Thank you!

**Comment by lpatiny** [comment]
@jobo322 It is a good idea to add the filters and apply them automatically but probably too early. We will keep this for later when we will have a simple way to edit the filters.

**Comment by jobo322** [comment]
@michelgravel here is the function in nmr-load-save to create a jcamp file.

**Comment by michelgravel** [comment]
I don't see the option to save as jcamp under 'Export As' in nmrium. Am I missing something?

**Comment by jobo322** [comment]
Hello @michelgravel you can access by right click over the spectrum:
![exportAsJcamp](https://github.com/cheminfo/nmrium/assets/12143935/3b04bdaf-d417-41a1-a54e-81fec2867bd0)

**Comment by michelgravel** [comment]
Thank you! I was not aware of the right-click function.
However, when I import the jcamp spectrum into c6h6.org I noticed the ppm scale is wrong and the spectrum display right-to-left instead of left-to-right. Is that an nmrium problem or a c6h6 problem?

**Comment by jobo322** [comment]
Hello @michelgravel, thank you for the advertisement. I reopen this issue and it is related with: 

- https://github.com/cheminfo/nmr-load-save/issues/222

**Comment by jobo322** [comment]
Hello @michelgravel, could you test please the behavior of exportAs jcamp-dx in the last changes. you can do it in https://dev.nmrium.org

**Comment by michelgravel** [comment]
I just tried it on the development site and it works great. Thank you!
