### ISSUE TITLE
data and onDataChange debug page

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1419]
We use to have a debug page allowing to check the content of data based on onDataChange callback but I can not find it anymore.

We need a way to debug the creation of the component with some data as well as to visualizer the onDataChange.

@hamed-musallam Please create a new page on dev.nmrium.org that allows to paste or drag / drop a .nmrium file and that will create the NMRium component with the `data` prop set to this value.

It seems that currently the behaviour is not the same if you drag / drop data directly in NMRium or if the data are coming from the `data` prop of the component.

@Sebastien-Ahkrin this should allow to check in particular you problem that if the data does not contain a source with jcampURL it fails.

**Comment by hamed-musallam** [comment]
@lpatiny 
process.env.NODE_ENV is not set when it build and publish gh-pages, locally it works even in the development node

https://github.com/cheminfo/nmrium/blob/df4ad3b58ef3a469dcbaedb902fe6258244c8ed2/src/demo/views/View.tsx#L120

**Comment by hamed-musallam** [comment]
@lpatiny 
if you take a look at the demo, In all the examples we use the "data" property to pass the .nmrium file data to the Displayer https://github.com/cheminfo/nmrium/blob/df4ad3b58ef3a469dcbaedb902fe6258244c8ed2/src/demo/views/View.tsx#L118

**Comment by lpatiny** [comment]
But could we have a view on dev.nmrium.org that allows from outside the component to set the data properties (another drag / drop or paste) ?

I would like also to be able to explore part of the data when the component is working. For example I would like when using the component to see data.spectra[0].ranges.

![image](https://user-images.githubusercontent.com/1484241/157627581-0fa3f9cd-ff13-448e-82ee-d567cdc6b9df.png)

**Comment by targos** [comment]
Such a test page would also allow to test what happens when `data` changes. I know there are bugs currently with this.

**Comment by hamed-musallam** [comment]
@lpatiny 
Please use this URL to open the Test Page https://dev.nmrium.org/#/test

**Comment by lpatiny** [comment]
Could you at least add a link to this page from https://dev.nmrium.org ?

Better if it was in the list in the menu on left like Exercises. We may have some other specific debug layout.
