### ISSUE TITLE
Some buttons look strange when importing NMRium component 

### ISSUE THREAD

**Issue by michaelwenk** [cheminfo/nmrium#1424]
@lpatiny @hamed-musallam I upgraded to the last NMRium version and use the component in another project as before. No style or CSS changes were made here.
And from now on the buttons of the "outer" component in NMRium look different.

I also tried a completely new and empty project with a use of NMRium directly (not via fork etc.) and it's the same result.

<img width="1439" alt="Bildschirmfoto 2022-03-10 um 22 27 32" src="https://user-images.githubusercontent.com/30418272/157758689-054b66b4-96c0-4b7a-9658-e3dcee596d73.png">

**Comment by michaelwenk** [comment]
@targos @hamed-musallam Thank you both for your changes but it seems that it had no effect. 

At least in my case I merged with latest changes from this morning ([21ffc50](https://github.com/cheminfo/nmrium/commit/21ffc501a5fb359fde7a0918c5cb4951425898fc)) and still the buttons look like before (see screenshot). 

I am using NMRium directly and tried it in a new and empty project as well. 

<img width="1281" alt="Bildschirmfoto 2022-04-05 um 12 10 30" src="https://user-images.githubusercontent.com/30418272/161732539-e9934af3-0a3b-4303-b2a9-118f00280925.png">

**Comment by targos** [comment]
What did you do exactly to try the latest changes in your project?

**Comment by michaelwenk** [comment]
@targos Attached you can find a zip file containing a small project for demonstration. There the buttons look different when importing the NMRium.
I don't know whether style settings is the missing part here, but in the versions before I created that issue the buttons had the same appearance as when starting the tool from NMRium project directly. 

[test.zip](https://github.com/cheminfo/nmrium/files/8420237/test.zip)

**Comment by targos** [comment]
That's not what I asked.

**Comment by michaelwenk** [comment]
I right now saw that the version 0.24.1 is from last week and not from today. That means the new changes are not included. I am sorry for that confusion.
