### ISSUE TITLE
Allow to define which panels are open on load

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1432]
Add a second column 'Open on load'

![image](https://user-images.githubusercontent.com/1484241/158318393-7b747784-e27b-48ae-9916-3c23ca5f3a21.png)

In 'workspaces' we should also be able to define which panels are open on load.

**Comment by hamed-musallam** [comment]
@lpatiny 

I made changes at the beginning of the refactorPreferences branch on the NMRiumPreferences:
```  
panels: {
    spectraPanel: FeatureStatus;
    informationPanel: FeatureStatus;
    peaksPanel: FeatureStatus;
    integralsPanel: FeatureStatus;
    rangesPanel: FeatureStatus;
.... etc
  } 
```  

  where  FeatureStatus accept 3 files [true,false,'hide'], I propose to add new status call "open" which mean true and open at the same time and for General preferences We have two options:
  1- replace the check box with drop-down menu
  2- what you proposed before, Is to have 2 columns of checkboxes one for visible/invisible and the other one for open by default. in this case, i have to manage the two boxes  value to be one value, which means if check open by default, i will take "open" status and visually set the other checkbox true and if uncheck it, nothing is affected and i look only for the first checkbox to see if its value true or false
