### ISSUE TITLE
Add button component

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1433]
Reuse the same component to always have the same style.

**Comment by targos** [comment]
This clashes with analysis ui components

**Comment by lpatiny** [comment]
I forgot there was already buttons in analysis-ui-components

@targos do you agree that we create some specific buttons for validate, cancel, etc like we do in our components library ?

**Comment by targos** [comment]
yes. the button API is not finished yet because we didn't take time to discuss it

**Comment by hamed-musallam** [comment]
closed this in #1467
