### ISSUE TITLE
Resize range remove the highlight

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1442]
The resize zone should be + / - 5 pixels (seems currently it works outside but not inside) and it would be nice to keep the 'orange' zone displayed during resize.

Currently it becomes white and this is quite confusing.

![2022-03-21 18 53 09](https://user-images.githubusercontent.com/1484241/159334360-d8829bef-6cb0-470a-b555-4dcf8303295b.gif)

@hamed-musallam If you don't manage I guess you could ask an advice to Michael.

**Comment by hamed-musallam** [comment]
@lpatiny 
it works normally on my side, what is the browser you use?

**Comment by hamed-musallam** [comment]
closed by https://github.com/cheminfo/nmrium/commit/21ffc501a5fb359fde7a0918c5cb4951425898fc
