### ISSUE TITLE
Full ethyl benzene crash

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1455]
![image](https://user-images.githubusercontent.com/1484241/161025015-431af578-c123-46f0-8870-aedb660ab990.png)

https://dev.nmrium.org/#/SamplesDashboard/vzrhuq79uu9/Viewdataethylbenzenedataethylbenzenefulljson

**Comment by hamed-musallam** [comment]
closed by b8626de6f96c35874acb2e769620bf94bfb13a39

**Comment by lpatiny** [comment]
Please add a playwright test for the 2D so that it does not happen again.

**Comment by hamed-musallam** [comment]
@lpatiny 
instead of creating a new one we can use the existing open 2d sample test and reproduce the bug.
