### ISSUE TITLE
keep older highlight of assignments

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#1457]
when you pass over a range assigned after checking one assignment before, you will see the highlight (in red) for both assignments. 

https://user-images.githubusercontent.com/12143935/161040926-4d657f38-9501-4f65-8d37-026c66b9614f.mp4

**Comment by hamed-musallam** [comment]
@jobo322 
I have to check the assignment tool to see what is happening

**Comment by hamed-musallam** [comment]
@jobo322 
I guess this bug should not exist anymore, can you test it again on the auto-assignment branch, I completed the assignment tool refactor.

**Comment by hamed-musallam** [comment]
@jobo322 

this is already fixed, can you check it, and if not, please , reopen the ticket
