### ISSUE TITLE
hidden panels when there is not enough space

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#1458]
as an example, the `assignment` panel got hidden when you open the ranges panel

https://user-images.githubusercontent.com/12143935/161041262-bbdafaa2-9257-4da5-89d3-9bb09accdabd.mp4

**Comment by hamed-musallam** [comment]
@jobo322 
when double click we open only that panel and hide the others, but if you click one time it will open that panel without closing the others and share the vertical space equally.

**Comment by jobo322** [comment]
@hamed-musallam, I can not reproduce the issue now. Many thanks
