### ISSUE TITLE
Pressing "Enter" in NMRium triggers the file selector menu

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#1460]

**Comment by lpatiny** [comment]
Apparently the drag / drop component capture the 'Enter' and open the file selector dialog box. This should not be the case seems to me and we should ignore Enter.

**Comment by hamed-musallam** [comment]
@targos 
it is related to react-dropzone, i prevented SPACE/ENTER to open the native file selection dialog by set noKeyboard to true on useDropzone hook.
