### ISSUE TITLE
Load NMRium file and strange appearing spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1469]
[test.nmrium.zip](https://github.com/cheminfo/nmrium/files/8440986/test.nmrium.zip)

More and more spectra are appearing when we change of tab

![2022-04-07 10 25 17](https://user-images.githubusercontent.com/1484241/162155081-c5dcb976-f137-4bdc-b75a-965397663d43.gif)

**Comment by hamed-musallam** [comment]
@lpatiny 
how did you generate this file, can you show me?

**Comment by hamed-musallam** [comment]
@lpatiny 
sorry, I can see the problem now when I export the Full cytisine sample and import it, I will take a look at it.
