### ISSUE TITLE
Ranges / Preview publication string is not working

### ISSUE THREAD

**Issue by tomlebl** [cheminfo/nmrium#1471]
Preview publication string in the ranges panel is not working. It works fine in v0.23.0 
The code fails in function saveAsHTMLHandler in  RangesHeader.tsx because preferences.current.formatting.nucleusByKey is an empty object. 
Workaround: Open and save General Settings that corrects data stored in local storage nmr-general-settings and error disappears 

Likely, initial preferences state is not getting set properly

**Comment by hamed-musallam** [comment]
Hello @tomlebl, it seems that there is a bug when updating the nmr-general-settings when moving from the old to the new version of nmr-general-settings in the local storage, Can you send us the old nmr-general-settings?

**Comment by tomlebl** [comment]
@hamed-musallam I have just tested the current HEAD and all seem to be good.
