### ISSUE TITLE
Difference of assignment with and without 'explode' protons

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1479]
Not sure why we have different results with and without exploding the protons

![2022-04-15 13 28 35](https://user-images.githubusercontent.com/1484241/163565672-d6cd4095-b817-4368-b458-1848e81e4e64.gif)

@jobo322 Any idea ?

**Comment by hamed-musallam** [comment]
I need to check why when you are over carbon you not getting hydrogenOCLIDs and it gets only the ociID
![image](https://user-images.githubusercontent.com/35760236/163940480-32fd6e15-8ede-41e3-8ac2-95f4c3f5dfe5.png)
