### ISSUE TITLE
nmrium does not read the jcamp source property when there is no data available 

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#1481]
I am trying to read a nmrium file that contain the jcamp string on `source.jcamp` property but nmrium throw an error about `data.x.length`. Could you let me know I having any mistake in the file:

[154884.zip](https://github.com/cheminfo/nmrium/files/8507194/154884.zip)

**Comment by lpatiny** [comment]
@hamed-musallam I think we should allow to have inline jcamp file like we allow jcampURL.

**Comment by hamed-musallam** [comment]
@lpatiny 

for which property I should check first jcampURL or jcamp?, the exported data should not include both properties

**Comment by lpatiny** [comment]
We are recovering old data for which we have some assignment and jcamp file. We would like to create a '.nmrium' for those old data.

This means that we will have an inline 'jcamp'.
