### ISSUE TITLE
Autoassignment crash for cytisine

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1491]
If you load the full cytisine, create an auto peak picking and then try to auto assign the system never ends.

![image](https://user-images.githubusercontent.com/1484241/164465634-a649cdeb-d99d-4f4c-8f4b-107070eafe04.png)

@jobo322 can you investigate what is the problem and how to solve it ?

**Comment by jobo322** [comment]
The auto assignment does not crash, it returns a empty array because does not find any solution, I will check why.

**Comment by lpatiny** [comment]
Ok. @hamed-musallam could you add a message in the panel if the returned array is empty:

`Could not assign molecule, please check that all the ranges are defined correctly`.
