### ISSUE TITLE
Small screen

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1494]
Is there a property that allows when you load the component to hide the panel on the right ?

On small screen it can look weird.

![image](https://user-images.githubusercontent.com/1484241/164616754-4e78263d-6b3c-4a11-afd3-eca3f3ee6469.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
we can specify it at component preferences at the level of general object {hidePanels: true} by default it is false.
