### ISSUE TITLE
Database and big list of molecules

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1503]
I think that currently all the components are rendered before displaying the table containing the database.

This will soon be a problem because we plan to have a list of over 20'000 lines in the table and rendering the molecules would take ages. This means that the rendering should only happens when a specific part of the table is displayed based on the position of the scroll bar.

@targos could you advice about the library that could help to achieve this goal ?

**Comment by targos** [comment]
https://github.com/bvaughn/react-window

**Comment by hamed-musallam** [comment]
@lpatiny 
this what we did, we render only the visible rows of the table and not the whole table, and achieve this we use virtual scroll. How did you check that we render the whole table, did you check inspect the table elements by Chrome tool?

**Comment by hamed-musallam** [comment]
@lpatiny 
the initial loading time comes from the prepare data function, which is map the data in a suitable way to be handled by the react-table to be able to deal with row span
https://github.com/cheminfo/nmrium/blob/b451ab973bd1e8c5d2d8947108ed14afcd903afe/src/data/data1d/database.ts#L97-L128

**Comment by lpatiny** [comment]
Ok perfect thanks. We will prepare the file with over 2000 entries then.

**Comment by lpatiny** [comment]
Ok the tests show that with 2000 entries it works perfectly.
