### ISSUE TITLE
Load jcamp if available

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1510]
For some entries in a database we have a 'jcampURL'.

Add in the database panel preferences a new option 'Preview jcamp if available'

If this option is checked the mouse hover will load the jcamp and preview it rather that 'regenerating' a spectrum from the ranges.

In all the cases if we add a spectrum and the jcampURL is available we add the jcamp in the list of spectra.

**Comment by lpatiny** [comment]
Default for this new option should be 'checked' meaning by default even for the preview we will load and display the jcamp.

**Comment by hamed-musallam** [comment]
@lpatiny 

the problem as I mentioned before I could not access the jampURL, can you send a full URL as a sample to know exactly how I should form its base URL + relative path from the database row.

can you send me a sample for the full URL?

and what's going to happen if we failed to load it?

**Comment by lpatiny** [comment]
If it fails we can always display a message. If there is a non empty jcampURL it should not fail !

I'm sorry, there was a permission issue and actually my example was not working.

If we have the following toc URL

https://data.cheminfo.org/nmr/database/toc.json

The first file is ./jcamp/154872.jdx

You may get the URL using

`const jcampURL = new URL('./jcamp/154872.jdx','https://data.cheminfo.org/nmr/database/toc.json')`
