### ISSUE TITLE
Larger structures

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1511]
In the database panel the structures are quite small and I don't know what is the limiting factor.

![image](https://user-images.githubusercontent.com/1484241/165224691-2b9ee924-7c45-4cd0-b1f3-1d18e5e10116.png)

@hamed-musallam could you check how it could be enlarged ?

**Comment by lpatiny** [comment]
It seems that currently the structure is calculated at 100 x 60 size.

The structure could rather be calculated at 300 x 300 and then shrink if there is not enough room.

The minimal height for a row could be 80 (in case there is only 1 or 2 range for example).

**Comment by hamed-musallam** [comment]
solved by @targos https://github.com/cheminfo/nmrium/pull/1505/commits/9bc14c598dfd931badf370cc912c168dea109ac4
