### ISSUE TITLE
Why is the the 13C tab that is selecdted

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1512]
When loading exercises:

https://www.nmrium.org/teaching#%3Ftoc%3Dhttps%3A%2F%2Fcheminfo.github.io%2Fnmr-dataset-jgumainz%2Ftoc.json

The selected default tab selected in the Spectra panel is 13C. I would expect it is 1H.

@hamed-musallam Any idea what it is 13C ? Is it the order of spectra ?

![image](https://user-images.githubusercontent.com/1484241/165237024-b09e97ab-4c1e-4907-8296-3274f3c090a5.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
it is based on the order when we group the spectra by the nucleus, I will order it by the nucleus and pick the first nucleus
