### ISSUE TITLE
Peak width after peak picking is not displayed correctly

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1523]
![image](https://user-images.githubusercontent.com/1484241/166454729-be704801-9ccf-444a-8cd1-61deadd0d0b3.png)

Values should be around 1 Hz. 

I don't know what is currently the unit but it should anyway be displayed in Hz.

**Comment by hamed-musallam** [comment]
@lpatiny 

the value in Hz = delta * spectra frequency 

https://github.com/cheminfo/nmrium/blob/c071f5ad9143be406a8cb19e743e2fb03444a40e/src/component/panels/PeaksPanel/PeaksPanel.tsx#L86-L88
