### ISSUE TITLE
Not able to set the format of delta in peaks preferences

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1524]
In peak panels preferences it is not possible to set the format for delta in ppm

![image](https://user-images.githubusercontent.com/1484241/166455887-3d40081a-0adf-4528-bb4a-50c39e2c1c68.png)

**Comment by hamed-musallam** [comment]
@lpatiny 

we hide it for a purpose, we format the value based on the nucleus from the general setting

https://github.com/cheminfo/nmrium/blob/c071f5ad9143be406a8cb19e743e2fb03444a40e/src/component/panels/PeaksPanel/PeaksPreferences.tsx#L168

https://github.com/cheminfo/nmrium/blob/c071f5ad9143be406a8cb19e743e2fb03444a40e/src/component/panels/PeaksPanel/PeaksTable.tsx#L32
https://github.com/cheminfo/nmrium/blob/c071f5ad9143be406a8cb19e743e2fb03444a40e/src/component/panels/PeaksPanel/PeaksTable.tsx#L81-L92

**Comment by lpatiny** [comment]
Indeed this is an excellent point. Need to think about it if we should keep this feature because in Range it is not used for example.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/1484241/166735875-7b80b712-24a3-4992-bd68-46bd20533525.png">

@hamed-musallam Could you check (without doing any change) what would be the impact of remove this general preference and keep it at the level of each panel ?

**Comment by hamed-musallam** [comment]
We format the number based on Nucleus in different components

Footer for 1d and 2d
![image](https://user-images.githubusercontent.com/35760236/168158560-fa1db06e-538a-4901-8e82-8af538b78895.png)
![image](https://user-images.githubusercontent.com/35760236/168158743-8e0ba5f0-a5a1-4962-95f5-b644c0453813.png)

Multiple spectra analysis table column header
![image](https://user-images.githubusercontent.com/35760236/168159152-bda3b7a4-3da0-4b07-8613-5281e79a17aa.png)

Peaks table and annotations 
![image](https://user-images.githubusercontent.com/35760236/168159479-eabf7b80-07b3-416d-a1c6-145b1195b993.png)

Search input field in database panel 
![image](https://user-images.githubusercontent.com/35760236/168159720-6843e55e-3146-4e1c-b310-e5232a380821.png)

Range  edit modal (delta,coupling)
![image](https://user-images.githubusercontent.com/35760236/168159988-e3ee325c-fbef-420b-8e63-2f09b3437edf.png)
![image](https://user-images.githubusercontent.com/35760236/168160103-5a703012-91ab-4c5a-95aa-d76ba9db8ddd.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
What do you think we should do?

**Comment by lpatiny** [comment]
Thanks Hamed for this exhaustive analysis !!!

I think each panel and kind of annotation should deal with his own preferences:

- peak panel will decide the number of digits in the panel and the peak annotation
- range panel will decide the number of digits in the panel and the range annotation + everything related to the edition of ranges
- zone panel will decide the number of digits for the 2 columns of delta

There are 2 places left:

![image](https://user-images.githubusercontent.com/1484241/168213963-b52041e3-b628-42a2-a846-57007d4a65b6.png)

![image](https://user-images.githubusercontent.com/1484241/168213982-9a8df3e0-0d51-431e-9a1b-89e25a91f84b.png)

and for them we will use the general preferences and rename the header to 'Crosshair and bottom info zone'

![image](https://user-images.githubusercontent.com/1484241/168214152-bcc639b3-e42b-4804-b6be-b069fad072ff.png)

**Comment by hamed-musallam** [comment]
closed by 88eee3c2758b66c0556e52f8933e8f9fa6d5b849
