### ISSUE TITLE
Different background color for molecules

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1526]
When you have more than one molecule the first molecule is on a light grey background and the second one is on a white background. Is this expected ? I would put all of them with the light grey background.

![image](https://user-images.githubusercontent.com/1484241/166497647-f29f95cc-c910-47d4-9080-264a44be239f.png)

![image](https://user-images.githubusercontent.com/1484241/166497736-570352db-bc9b-4c45-8a3e-78fe5de1fa38.png)

**Comment by hamed-musallam** [comment]
yes, this is how it works, to make the animation visible when you slide to left to right

**Comment by lpatiny** [comment]
Ok thanks.
