### ISSUE TITLE
Fid size not correct

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1533]
The default value for the Zero filling in the case of 13C is not correct.

Expect to be 256k so preselect the double ? (512k)

**Comment by lpatiny** [comment]
It is related to:

https://github.com/cheminfo/nmr-parser/issues/54

Waiting for @jwist answer.

**Comment by jobo322** [comment]
In nmrium, we present the Re or Im part of the FID, so the size of the FID is 256k but the real part is 128k

**Comment by jobo322** [comment]
@lpatiny is it the expected behavior?

**Comment by jobo322** [comment]
I think it is correct right now, we could check if it is a power of 2, adapt and select the double of nbPoints in the zeroFilling panel.
