### ISSUE TITLE
firefox test faild

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1541]
@targos 

it seems that the test failed because color picker elements have rounded corners and Firefox looks to the click on the corner (x:0,y:0) that it is outside the border so the firefox does not handle it.

do you have any idea how to keep the same implementation in firefox as the others browsers?

**Comment by targos** [comment]
I would remove the rounded corners on this element.

**Comment by targos** [comment]
Fixed with https://github.com/zakodium-oss/analysis-ui-components/commit/a60cf0a84c40c67edbd87a3a43b4f8a22c783374
