### ISSUE TITLE
testing problem with NMRium

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1542]
@targos 

when i try to test NMRium in another project with https://testing-library.com/, I get this error related to d3 which we imported in different places in nmrium,  https://github.com/cheminfo/nmrium/blob/master/src/component/1d/utilities/scale.ts and there are other places
```
Error: require() of ES Module C:\dev-projects\nmrium-react-wrapper\node_modules\d3\src\index.js from C:\dev-projects\nmrium-react-wrapper\node_modules\nmrium\lib-cjs\component\1d\utilities\scale.js not supported.

Instead change the require of index.js in C:\dev-projects\nmrium-react-wrapper\node_modules\nmrium\lib-cjs\component\1d\utilities\scale.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by targos** [comment]
can you share part of the code that fails? At least the test.

**Comment by hamed-musallam** [comment]
@targos

 it was a mistake from my side, I import a custom function that cause this problem, and now Playwright works as expected locally but the workflow does not, I run the build and run the server locally and it works without any problem, what do you think the problem. The workflow is a clone version of yours

https://github.com/NFDI4Chem/nmrium-react-wrapper/tree/development
