### ISSUE TITLE
Default workspace

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1543]
In the default workspace Matrix generation and Automatic assignment should not be available.

![image](https://user-images.githubusercontent.com/1484241/168163326-b531e00d-393f-45e4-95d7-2873df8bb627.png)

**Comment by hamed-musallam** [comment]
@lpatiny 

by default it does not exist, it exists for you because you enabled the experimental feature, just reset the local preferences, and will disappear.
Matrix generation it still under experiment and does not have it own preferences

**Comment by lpatiny** [comment]
I did the reset but after reset Experimental features is still checked

![image](https://user-images.githubusercontent.com/1484241/168214433-335800b9-e5b9-43c3-9963-e5f2ad7ec5de.png)

Maybe there is a problem at this level.

**Comment by hamed-musallam** [comment]
Closed by 99dfa1b5af2020c3e6773907dc8334624ececb92
