### ISSUE TITLE
Zones and preferences

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1545]
When defining zones we are dealing with 2 nucleus. One for the horizontal axis and one for the vertical axis.

In NMRium we have example spectra that are 1H,1H (cosy) and spectra that are 1H,13C (hsqc, hmbc) (we could have other nucleus as well).

In the preferences of the zones we need to deal with the nucleus separately. This means that we should display the list of all the independent nucleus and set the preferences for each nucleus (and not couple of them). In a cosy there should actually be only 1H.

![image](https://user-images.githubusercontent.com/1484241/168213075-6e4870fe-bb38-418e-911b-1cc8640592ab.png)

For an 1H,13C we should therefore see a first group for 1H and a second group for 13C.

**Comment by hamed-musallam** [comment]
closed by 88eee3c2758b66c0556e52f8933e8f9fa6d5b849
