### ISSUE TITLE
What is peak index ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1549]
After making peak picking there is in the peak panel a way to display the peak index.

But this value is always 0

What is it ? Should this be removed ?

![image](https://user-images.githubusercontent.com/1484241/168375867-f14258a4-203f-45a9-a873-63c4e7088ed8.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
it is an old field that it value was coming from Auto peak picking, I do not know what kind of value is holding or for what we use it?
