### ISSUE TITLE
Generate image of the spectrum from outside component

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1569]
in addition to exporting spectra as SVG, jpeg we need a way to capture and save them directly to the external data service. This has to be done from where our component is imported. for example, in Chemotion ELN they need to be able to capture the Blob of the generated image and store it  as a blob in the database or store the image in the file server and store its path in the database

**Comment by hamed-musallam** [comment]
@lpatiny 

The user can click somewhere outside NMRium or trigger an event in the  NMRium Wrapper to generate an image as a blob to save it somewhere else, maybe in a database or as upload it as a file in another file server.


I will ask Chandu to comment on this ticket

**Comment by CS76** [comment]
Use case: ELNs and repositories would like to create a thumbnail or preview of the spectra for the user to quickly identify the spectra and not have to load the spectra every time. 

Trigger point:
Ideally, this will be triggered behind the scenes by the parent application (via the nmrium wrapper) and NMRium just has to pass back the image/png or image/jpg blob or SVG back as a response. This will then be handled by the parent application (saved to the file system on the server or to a database).
