### ISSUE TITLE
specify the minimum width for SplitPane

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1570]
@lpatiny 
What is the minimum width for SplitPane if there is no room for the panels to close the side panel?

**Comment by lpatiny** [comment]
Not sure I understand the question.

The component that displays the spectrum should be at least 600px and if it is smaller the panels should close.

**Comment by hamed-musallam** [comment]
@lpatiny 

in SplitPane we have to set a value to minimunWidth property to make it work, i mean close dynamically if the panel is less than the specified width, would you like to hardcoded the value or it could be changed by the component preferences

**Comment by lpatiny** [comment]
It is not the panel that should have a minimal size because it has a fixed size.

It is the space left for the spectrum that should have a minimum size of 600px

**Comment by hamed-musallam** [comment]
@lpatiny 

the initialSeparation and minimumSize depend on the sideSeparation in our case the end means the right panel will be closed if it is smaller than 600px, this is the behavior of the SplitPane component, i think we can enhance it by specifying which side to check for minimum width (minimumSizePaneCheck  = "start"| "end")or be default take always the opposite of the sideSeparation (if sideSeparation == end takes the start panel and vice versa ) 

![image](https://user-images.githubusercontent.com/35760236/172398534-d243e9af-947e-4653-9200-df68588a162c.png)

currently if we set minimumSize= 600px will closed the right panel because the initalSpearation is 560px

```ts
    <SplitPane
      initialSeparation={general?.initialPanelWidth || '560px'}
      orientation="horizontal"
      sideSeparation="end"
      initialClosed={general?.hidePanelOnLoad || false}
      minimumSize={600}
    >
      {children}
    </SplitPane>
```

**Comment by lpatiny** [comment]
It does not seems that have any application to check the `minimumSize` of the same size as the `initialSeparation`.

This is a bug in analysis-ui-component and the side that should have the `minimumSize` is the one that is not forced. @hamed-musallam please could you make a PR to fix this problem ?
