### ISSUE TITLE
Pressing 's' with only one spectrum

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1576]
When pressing `s` and only one spectrum is present the icon for baseline center / bottom is changing.

![2022-06-07 11 44 37](https://user-images.githubusercontent.com/1484241/172350014-fe1f14c0-94ff-4ee4-a116-43d8b723f14e.gif)

**Comment by hamed-musallam** [comment]
closed in 6b2792c48474fe447ca22dc7191824276300d9b6
