### ISSUE TITLE
Default color for database spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1579]
You could use this default color when superimposing the spectrum from database:

![image](https://user-images.githubusercontent.com/1484241/172383330-dd96b933-282f-413f-b4ee-8a6568508894.png)

**Comment by hamed-musallam** [comment]
@lpatiny 

when we superimpose the spectrum from the database we treat it in the same way when drag and drop jcamp or any other file format to prevent color repetition.

**Comment by hamed-musallam** [comment]
@lpatiny 
sorry, I did not get it, do you mean use #C0B000 as the default color?
