### ISSUE TITLE
Option to disable drag and drop (manual loading of spectra)

### ISSUE THREAD

**Issue by CS76** [cheminfo/nmrium#1582]
When data is deposited (within a repository), the repository users would like to analyse the spectra using NMRium, within the scope of that particular study/experiment. In that web view, the context is to programmatically load the spectra (from repository storage), let the user analyse the spectral data, and save the changes.

Allowing the user to drag and drop new files will cause discrepancies in the data (spectra will no longer match the original machine output as the user dragged and dropped new files and continued editing).

To avoid this, we would like to disable drag and drop and load the data from the storage (programmatically), let the user edit, analyse manually and save the changes automatically.

Update: When disabled we would also like to disallow the user to be able to delete the spectra

**Comment by lpatiny** [comment]
We could enhance the preferences to be able to add more options like allowing or not the drag / drop of the files. Actually this is related to the presence of the `import` tool.

The advantage is that it can then be saved in a 'workspace' and we can have various `workspaces` with the different preferences.

@hamed-musallam today we can set the property `preference` in the NMRium component. Is the value of this property the same as the preferences of a specific workspace ?

When I see in the documentation there are many options that are not available from the general preferences (show / hide tools) and I wonder if there should not be a new tab in the preferences with the 'Tools'

**Comment by hamed-musallam** [comment]
@lpatiny 

yes we could included it in the general preferences but what the purpose to hide and show the tool from the general preference or it is just to make it systematic.

Currently the workspace  include:
1- All the panels preferences (peaks, ranges, integrals, zones and database) 
2-  Show/Hide/Open On Load panels
3-  Show/Hide tools 
4-  Number formation for Crosshair and info line per nucleus
5- Databases

**Comment by NRayya** [comment]
@hamed-musallam 
Currently, (in nmrXiv dev), when the user drags a file to the NMRium view of another spectrum, a message appears saying "drop your files here", then a loading symbol appears, then nothing happens. Although the intended function works fine, I think it is viewed wrongly to the user and it might be confusing
[screen-capture.webm](https://user-images.githubusercontent.com/82588017/208139633-473fb8ff-5b03-407b-9e0c-e1d666700060.webm)
