### ISSUE TITLE
Mol file (structures are) not loaded when spectra is loaded via URL (.zip) 

### ISSUE THREAD

**Issue by CS76** [cheminfo/nmrium#1583]
If the Bruker folder structure has a .mol file in it, it is loaded when dragged and dropped. While the same folder loaded via .zip URL ignores the mol file. 

Example attached below

[MLM-041_13C.zip](https://github.com/cheminfo/nmrium/files/8890765/MLM-041_13C.zip)

**Comment by hamed-musallam** [comment]
@lpatiny 

I think we need to finalize the  https://github.com/cheminfo/nmr-load-save  package soon, for now i will do it like what I did when importing jcamp,bruker and jeol at the level of the wrapper as phase solution until we finalize the nmr-load-save package

**Comment by hamed-musallam** [comment]
@CS76 

this has been implemented at the side of the wrapper https://github.com/NFDI4Chem/nmrium-react-wrapper/commit/0340db652df0bde5125018a95f91b9a50bab6c95, I will close this issue for now.
