### ISSUE TITLE
data structure from onDatachange should be the same as what we get when export .nmrium 

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1584]
In the onDatachange we get the same data structure as it is in the global state but when exported as a .nmrium file we modify the structure before saving the file.

@lpatiny 
 
i think it should be the same data structure? what do think?

**Comment by lpatiny** [comment]
onDataChange should indeed return the .nmrium format. You may try to convert it systematically ans we will see if there is some performance impact.

**Comment by hamed-musallam** [comment]
@CS76

This just to let you know that the data you will get from onDataChange call-back will change in the next release of NMRium, nmrium@0.28.0, it's structure will be the same as the data that you get export .nmrium file.
