### ISSUE TITLE
add a new panel that allows to toggle on / off tools

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1595]

**Comment by hamed-musallam** [comment]
@lpatiny 

do you think we need the same things as what we did in the panel preferences that we have two cases:
1- hide tools completely and can not show/hide from the general settings 
2- hide/show the tool and allow to show/hide it from the general settings


for example 
```ts
toolBarButtons:{
 exportAS: {hidden:true},
 peakPicking:{active:true}
}
```

**Comment by lpatiny** [comment]
Seems to me that for panels if you have access to general settings you can always activate them.

![image](https://user-images.githubusercontent.com/1484241/177126482-8994f789-fa13-423c-a2af-870866997bfb.png)

How we can prevent a panel to be activate from general preferences ?

**Comment by hamed-musallam** [comment]
@lpatiny 

if the panel is hidden that means it is not visible in the general settings

**Comment by hamed-musallam** [comment]
Do you think it is better visually to have another column for the tool
![image](https://user-images.githubusercontent.com/35760236/177129770-3d701757-4101-4cd2-8e1c-795ff9bf5a64.png)

if you agree with me that it is better to have a separate tab, how we will deal with panels that connect somehow with more than one tool, for example, filter panels, this raises another question, Do we have to control each filter tool, zero-filling, linebroading, phase-correction ...etc or we could refactor it and saying it's a filter tool, i mean just at the level of preferences

**Comment by hamed-musallam** [comment]
closed by https://github.com/cheminfo/nmrium/commit/92d1c938562ba4f5004b6bf41bf62e4216e48079
