### ISSUE TITLE
FID preprocessing

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1617]
Guido is interested in the following window functions:

- EM/LB
- negative LB
- LG with LB/GB

I guess this could be added here:

![image](https://user-images.githubusercontent.com/1484241/178400065-79df676a-f4f5-4f69-9616-447a840648b7.png)

@jobo322 Do you see how to implement this ?

**Comment by lpatiny** [comment]
I got more info from Guido:

The most simplistic approach would be to establish two wdw functions:
- one EM with positive LB
- one LG with negative LB and positive GB value
All values in Hz.
They should be applied before any zero filling.

**Comment by gfpauli** [comment]
Yes, LG is Lorentzian to Gaussian wdw function.
I cannot see the implementation, only FFT and LB, so I can't tell what you have implemented.
There seem to be different ways to implement LG:
- one (Bruker, Jeol, NUTS) uses neg LB and a GB factor that describes the fraction of AQ at which the Gaussian is centered (0...1 = 0...100% of AQ)
- another (MNova, default setting) also uses neg LB plus GB in Hz, which seems to be the target half-height line width
MNova also has a setting for GB=0...1, but it gives different results from other software. In 10+ years, I have not been able to figure out how MNova does it.
Yes, a negative LB alone (when not doing LG, i.e.) does inverse exponential, which typically gives unusable spectra

**Comment by jobo322** [comment]
Many thanks @gfpauli for your explanation, I have an additional question to be sure about how the graphical interface should be generated for those filters. Currently, we're applying `zero filling` and `line broadening` using the same panel (only one click at the end). 

I know that sometimes two/more window functions are applied in the same FID, that is why nmrpipe adds `start` and `size` options for the windows functions. Do you know if someone could need to apply two/more window functions to all the FID, I mean from 0 - AQ

**Comment by gfpauli** [comment]
I would split ZF and wdw function panels completely. ZF could also be LP, and is just separate from any wdw function.
wdw fcts are typically (always?) applied before ZF/LP. 
Yes, there are cases in which multiple wdw fcts are applied, such as trapezoid plus EM or LG. MNova has all of them in one option set, which makes sense. in the pipe world, I guess they are simply chained as they are all multipliers for the FID.

**Comment by jobo322** [comment]
Linear prediction would improve the result of digital filtering, Linear prediction would improve the result of digital filtering. If you know about any reference/algorithm of this method where I can get inspired to implement it on nmrium.

**Comment by lpatiny** [comment]
@gfpauli could you give us a sketch or a screen snapshot of another software that would have the interface you would like ?

**Comment by gfpauli** [comment]
LP really only makes sense for truncated FIDs, such as in 2D; for 1D, ZF is fine. There must be literature galore on LP, such as https://pubs.acs.org/doi/10.1021/cr00007a007; I am unaware of code for such algorithms.

**Comment by gfpauli** [comment]
![image](https://user-images.githubusercontent.com/67487530/179257938-971a2c88-6b6d-4b1b-a5d2-137e8f46026e.png)
This is the MNova interface. Bascially all available wdw functions paired w/their parameters. LG is not expressively designated, one has to chose Exp PLUS Gaussian. The choice of GB in Hz vs. GM from 0...1 is the part I never understood. My sense is that it depends on the implementation of the EM+GM math.
They have an advanced tab that is just more wdw functions.
![image](https://user-images.githubusercontent.com/67487530/179258541-89d554a8-da3a-489d-a16b-1df7cafe6fd6.png)
