### ISSUE TITLE
Preview for apodization filter on the FID

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#1628]
Would be nice to have the possibility to visualize the shape of the window function we will apply as mestre did:

![image](https://user-images.githubusercontent.com/12143935/179540122-f2cccfeb-576f-4bf9-95f6-ed27f6d7745b.png)

It could appear in a floating window or draw this shape on the main panel.

**Comment by jobo322** [comment]
Should be nice to have a similar preview

![testing-2397](https://user-images.githubusercontent.com/12143935/179557948-1009c27a-14e4-410f-b613-2fad5c2dc8fe.GIF)

**Comment by lpatiny** [comment]
This function should always be displayed even if not preview mode.

**Comment by hamed-musallam** [comment]
closed by 16b97b36a3df275ade018f10769a33fc6ea26aa0
