### ISSUE TITLE
Jres should have his own tab

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1634]
It is quite annoying to superimpose COSY and Jresolv.

How we could deal with this to have a different tab ? Any idea @jobo322 

![image](https://user-images.githubusercontent.com/1484241/180173725-1bd2c9bb-7729-4905-bb91-ad035e6faf8f.png)

**Comment by jobo322** [comment]
yes, we should have a tab for DOSY or JRES because the indirect dimension is not in ppm. I think those spectra should not be superimposed with any other.

**Comment by lpatiny** [comment]
We could have as second nucleus 'J' so there will be a tab '1H,J'

**Comment by jobo322** [comment]
it is related with this ticket

-https://github.com/cheminfo/nmr-load-save/issues/54

@lpatiny with this I think it will generate a own tab.

**Comment by jobo322** [comment]
it was done by fb135a7b7c53df58317f6217609bf2319f483f05
