### ISSUE TITLE
Import of JEOL raw data

### ISSUE THREAD

**Issue by ak-jeol** [cheminfo/nmrium#1635]
Loading JEOL raw data files (1D and 2D) results in an error.

1D raw import error
The x and y arrays must have the same length
Error: The x and y arrays must have the same length

2D raw import
It does not load the data, but there is no error

1D processed
No problem

2D processed
Cannot read properties of undefined (reading 'experiment')
TypeError: Cannot read properties of undefined (reading 'experiment')

Attached is ZIP file with 1D, 2D, parameter format, functionalized process lists

[nmrium.zip](https://github.com/cheminfo/nmrium/files/9159472/nmrium.zip)

**Comment by ak-jeol** [comment]
Jose -

The parameter x_points for the data set I sent you was 14993.

The complex array consists of real+imaginary data points that translates to a total of 14993*2 = 29986.

Regards

Ashok

**Comment by jobo322** [comment]
@ak-jeol many thanks I will check why the converter returns 15000 instead of 14993

**Comment by jobo322** [comment]
@ak-jeol, checking the converter I found that we are using dataPoints instead of the parameter 'x_points':

- should those values be the same number? 
- is it ok to read this value as `uint32` as we are doing [here](https://github.com/cheminfo/jeolconverter/blob/master/src/parseJEOL.js#L58)

if you have any documentation about it, I could go further to fix this. many thanks again

**Comment by ak-jeol** [comment]
Jose –

You can find this parameter at byte offset 176 and you read in a 4 byte unsigned integer.

Please refer to the data format document I sent in the previous email.

Regards

Ashok

From: Ashok Krishnaswami
Sent: Friday, July 29, 2022 12:26 PM
To: cheminfo/nmrium ***@***.***>; cheminfo/nmrium ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [cheminfo/nmrium] Import of JEOL raw data (Issue #1635)

Jose –

Yes, x_points would be the parameter to use to extract the number of data points.

Basically, our dimensions are x,y,z,a,b,c,d,e

So, for 2 dimensional spectra you would look at x_points (similar to F2 in BRUKER lingo) and y_points (similar to F1) for the direct and indirect dimension.

In term of reading in values, the fact that you read in our processed 1D data set fine would indicate that unit32 would be ok.

The programmer went out to lunch, so I will ask when he gets back.  He can look at your source code and let me know.

I have attached our data format documents.

Regards

Ashok

**Comment by jobo322** [comment]
@ak-jeol when I'm able to load your 1D data example, I got this spectrum after zero-filling to 16k then FFT

you can test the changes in:

https://deploy-preview-1685--nmrium.netlify.app/#/SamplesDashboard/n06fxa902s7/View

https://user-images.githubusercontent.com/12143935/183866295-28149325-4cfc-4a47-881b-b6a0e67b3efd.mp4

**Comment by ak-jeol** [comment]
Jose –

I tried it and it does display the FID, so that is good.  The next question is – is there a plan to implement a Fourier Transform routine to convert from the time domain to frequency domain?

Regards

Ashok

**Comment by lpatiny** [comment]
@ak-jeol Is the existing FFT button as show by Alejandro in the video what you mean ?

**Comment by ak-jeol** [comment]
Luc –

Sorry, didn’t realize it was a video.  Figured out how to perform the FFT and phase.

What apodization function do you use; I didn’t see a way to change the line broadening.

Our data files have a large P1 phase correction ~ 2400 degrees.  When I enter the value in the P1 box it accepts it, but when I use the mouse after that, it always resets the manually entered value to 0.  Can the code be changed to start from the entered value?

One suggestion – if the data is not a power of 2 and I fft the data, it results in a “Something went wrong” message.

If the data is not a power of 2, could you automatically ZF it before FFT if the data si not a power of 2?

Regards

Ashok

**Comment by lpatiny** [comment]
you have the 'A' and '0' buttons to make apodization and zero filling

![2022-08-11 14 48 01](https://user-images.githubusercontent.com/1484241/184136851-9479cb5e-faba-4d3a-a359-c4940a9c0183.gif)

Concerning the phase correction can we guess from the file what would be a good starting point ?

**Comment by lpatiny** [comment]
I added a new issue for the power of 2 problem: https://github.com/cheminfo/nmrium/issues/1688

**Comment by lpatiny** [comment]
I create a new issue for the phase correction problem: https://github.com/cheminfo/nmrium/issues/1689

**Comment by lpatiny** [comment]
There is a new issue concerning the first guess for PH0: https://github.com/cheminfo/nmrium/issues/1690

**Comment by ak-jeol** [comment]
Jose –

Yes, x_points would be the parameter to use to extract the number of data points.

Basically, our dimensions are x,y,z,a,b,c,d,e

So, for 2 dimensional spectra you would look at x_points (similar to F2 in BRUKER lingo) and y_points (similar to F1) for the direct and indirect dimension.

In term of reading in values, the fact that you read in our processed 1D data set fine would indicate that unit32 would be ok.

The programmer went out to lunch, so I will ask when he gets back.  He can look at your source code and let me know.

I have attached our data format documents.

Regards

Ashok
