### ISSUE TITLE
Migration of `master` to `main`

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#1643]
In the last couple of years, many projects on GitHub have done the move of the branch name from `master` to `main`. We already did it in a lot of our own projects.

@cheminfo/nmr If that's fine with you, I'm going to update the project and rename the branch sometime this week.

After that's done, GitHub should show you the commands to run in order to update your local setup.

**Comment by hamed-musallam** [comment]
@targos  

No problem, you can migrate from ```master``` to ```main```  and we should announce that before we start

**Comment by targos** [comment]
@hamed-musallam Announce where? I can do the migration at the end of the day.

**Comment by hamed-musallam** [comment]
@targos 

maybe the best place is the ```NMRium React component``` group on Telegram

**Comment by hamed-musallam** [comment]
Thanks, Michael for the migration 
closed by 37f8fe7b5d758931929f02e4f88ecee29114c3c2 , 7f65645557edb7b8312469eacabdac3fb4a34e75
