### ISSUE TITLE
Suggested behaviour change: click-and-drag for changing integrals/ranges

### ISSUE THREAD

**Issue by jschneidewind** [cheminfo/nmrium#1648]
# Current behaviour

Currently, the range of integrals or ranges can be changed using click-and-drag when any one of the NMRium tools is selected. This can lead to undesired changes to the integrals/ranges, for example when trying to zoom in with the `Zoom` tool: the user tries to zoom into a target region but accidentally clicks on the edge of an integral/range, changing the integral/range instead of zooming in (see video below). This is especially pronounced when trying to zoom into a region with many different integrals/ranges.

https://user-images.githubusercontent.com/41544471/181267025-c507c69f-636e-44e7-9206-940780cec178.mov

# Suggested behaviour

1. The range of integrals/ranges can only be changed by click-and-drag when the corresponding tool (`Integral Tool` or `Ranges Picking` is selected.

or alternatively:

2. When the `Zoom` tool is selected, changing of integrals/ranges by click-and-drag is deactivated.

Happy to hear your thoughts on whether this would a sensible/practical change!

**Comment by lpatiny** [comment]
Thanks for the suggestion. Indeed your first options seems the best

@hamed-musallam Please could you change the behaviour so that :

1. Integral tool as to be selected in order to resize integrals
2. Range tool as to be selected in order to resize ranges
