### ISSUE TITLE
Improve peak picking and add top, bottom, both

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1651]
Currently when trying to make a peak picking there is no way to select 'negative'

![image](https://user-images.githubusercontent.com/1484241/181436354-54c495a1-0f78-4c94-b3fa-06cee0eb0c60.png)

But I think we could directly improve this code and add a select drop down menu with 3 possibilities:
- positive (default)
- negative
- both

**Comment by hamed-musallam** [comment]
@lpatiny 

But that xyAutoPeaksPicking function provides, is positive or both, how we could return the negative values or we should pick the negative values?

**Comment by lpatiny** [comment]
@jobo322 Could you add this feature in nmr-processing ?

**Comment by jobo322** [comment]
yes

**Comment by jobo322** [comment]
currently, the checkbox for autoRangePicking n autoPeakPicking is not working.

![image](https://user-images.githubusercontent.com/12143935/181747178-56a69908-7f42-41f1-86d8-a410866c9a9d.png)

**Comment by jobo322** [comment]
nmr-processing 8.4.0 has an additional options `lookPositive`. To get both (negative n positive peaks),  both `lookPositive` n `lookNegative` should be set as true, by default `lookPositive` is true n `lookNegative` is false to don't introduce a breaking change

**Comment by hamed-musallam** [comment]
@lpatiny @jobo322 
why not create one parameter which takes three values "positive" | "negative" | "both", you can call it for example "detectionOption" or detectionSign or anything similar

**Comment by jobo322** [comment]
yes, I think it could be something like `lookFor` @lpatiny  what do you think?

**Comment by jobo322** [comment]
I did add the lookFor options in nmr-processing and remove lookNegative and positive

https://github.com/cheminfo/nmr-processing/pull/184

**Comment by lpatiny** [comment]
The new release of nmr-processing was done: https://github.com/cheminfo/nmr-processing/releases/tag/v8.5.0

You can now use the option 'direction' that is 'positive' 'negative' or 'both'

@hamed-musallam could you update the package and finalize this feature ?
