### ISSUE TITLE
Why do we have hideSetSumFromMolecule ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1665]
Seems to me it is too granular to have this option and it will not be maintainable.

@hamed-musallam if you agree please remove it.

https://github.com/cheminfo/nmrium/blob/c465e9482d96e3aa74997e0bb477c48609d0e50d/src/component/workspaces/exercise.ts#L8

**Comment by hamed-musallam** [comment]
@lpatiny 

as I remember we set this option because you request to hide the "set sum from molecule" button from the students in the exercise mode.

if you see that it is no longer needed I can remove this option completely.

**Comment by lpatiny** [comment]
@hamed-musallam Thanks you have a good memory !

I think we can completely remove it because in the current approach of exercises the answer is not in the '.nmrium' file as before but only in the 'toc'
