### ISSUE TITLE
Removing exclusion zones on all spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1667]
When we are using the exclusion zones tool we can apply the exclusions zones either on all the spectra (none is selected) or the currently selected one.

We can also delete a zone using Backspace / Delete on the zone. However even we have no spectrum selected we can not delete the exclusion zone in all the spectra at once.

![2022-07-30 09 23 22](https://user-images.githubusercontent.com/1484241/181879793-11403221-ce6b-4e0e-9281-ede762446fc8.gif)

**Comment by hamed-musallam** [comment]
@lpatiny 
do you think is enough to look for the same range (from, to values) as a condition for the deletion, or we should set a shared id between them and use it in the deletion, I think the first option is enough, if you see that there are cases will not work let me knows
