### ISSUE TITLE
Add button in peak panel

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1668]
This feature is hidden behind the 'Experimental' falg !

Next to trash, at the level of each peak, there should be a button for peak shape edition

![image](https://user-images.githubusercontent.com/1484241/181880357-d0e9849e-772a-42b7-8e73-623b074c0068.png)

The logo can be the same that the one for range edition.

This should open a dialog with:

Information about the peak (the position in ppm)

A drop down menu allowing to select:
- Gaussian
- Lorentzian
- Pseudovoigt

https://github.com/mljs/peak-shape-generator/blob/main/src/index.ts#L1-L3

Depending the option:
For Gaussian and Lorentzian:
- FHWM:  An input field that allows to enter a number

For Pseudovoigt:
- FHWM:  An input field that allows to enter a number
- mu: An input field with a number between 0 and 1

A from / to value that can be filled automatically with SHIFT + draw a zone.

A button 'Optimize'. When clicking on optimize the system will try to optimize the various parameters.

There will be a new property at the level of peak in which we will save the 'kind' and 'fwhm' (and 'mu' for pseudovoigt)
```
 shape: { kind: 'gaussian', fwhm: 0.35 },
```

The TS type of Shape is exported here: https://github.com/mljs/ml-peak-shape-generator/blob/d7da8457f9d3521e1a2671b69a1ab7f2da3c40ce/src/index.ts#L9

**Comment by lpatiny** [comment]
The values could as well be edited directly in the table.

**Comment by hamed-musallam** [comment]
closed by #1683

**Comment by hamed-musallam** [comment]
closed by #1683
