### ISSUE TITLE
Peak shape highlight

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1673]
Peaks are characterised by shapes but based on their parameter it would be nice to display the shape. Something like:

![image](https://user-images.githubusercontent.com/1484241/182014672-16a01801-f092-40d3-b3d0-95abf982b671.png)

There should be a new component that accepts a 'peak' and a color to display the peak.

Like in range we should add in the Peak Panel a toggle button that allows to see / hide those shapes.

**Comment by lpatiny** [comment]
@jobo322 Hamed need that from a peak you generate the corresponding {x:[], y:[]}

@hamed-musallam From those {x: [], y:[]} you need to draw a polygon. Please take care to create an array os string that you join at the end to create the path.

For the color you may for now use whatever but it should have a low filled opacity, like 0.3, while keeping the counter with an opacity of 1.

**Comment by hamed-musallam** [comment]
closed by #1683
