### ISSUE TITLE
CSS Broken after the last upgrade of the emotion-react version 11.10.0

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1677]
@targos  can you check this?

![image](https://user-images.githubusercontent.com/35760236/182799391-6b91ad80-e1e2-4495-800a-388d7aece0ed.png)

**Comment by targos** [comment]
This was introduced by https://github.com/emotion-js/emotion/commit/bbad8c79937f8dfd5d93bf485c1e9ec44124d228
I fixed the problem in analysis-ui-components with a rewrite of the `react-shadow` import to force the ESM version.
