### ISSUE TITLE
2D phase correction in first dimension

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1680]
Get inspired by this video https://www.ccpn.ac.uk/manual/v3/Phasing.html

**Comment by jobo322** [comment]
looks like a great feature

**Comment by jobo322** [comment]
first of this, we should be able to make a FFT over a SER data.

**Comment by jobo322** [comment]
There is code for FFT 2D. to phase the 2D spectrum we should be able to extract traces. 

https://youtube.com/clip/UgkxWivtm5TTwIkxAoaZTD2NVn3QmHf3Cz2f
