### ISSUE TITLE
Add Shape in automatic peak picking

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1681]
Automatic peak picking should add a 'gaussian' shape by default using after GSD:

https://github.com/mljs/global-spectral-deconvolution/blob/master/src/utils/appendShapeAndFWHM.ts

**Comment by jobo322** [comment]
it is done https://github.com/mljs/global-spectral-deconvolution/commit/505121d79a32fafa6fd49ab633556983b1cef24c
