### ISSUE TITLE
Copy to clipboard in safari

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1682]
Copy to clipboard on Safari does not work. I have a message in the console "NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission." and this should be displayed to the end-user.

![image](https://user-images.githubusercontent.com/1484241/183293537-783e3cf2-aaf9-4e5b-bc5f-65e179ce1cfb.png)

I also don't know how to prompt the user to accept the copy to clipboard

**Comment by lpatiny** [comment]
There is a specific message speaking about safari on https://web.dev/async-clipboard/


> Safari (WebKit) treats user activation differently than Chromium (Blink) (see [WebKit bug #222262](https://bugs.webkit.org/show_bug.cgi?id=222262)). For Safari, run all asynchronous operations in a promise whose result you assign to the ClipboardItem: js new ClipboardItem({ 'foo/bar': new Promise(async (resolve) => { // Prepare `blobValue` of type `foo/bar` resolve(new Blob([blobValue], { type: 'foo/bar' })); }), })

**Comment by hamed-musallam** [comment]
closed by a6b54c956a7b3c8b860ecd346174879d91df769c

**Comment by targos** [comment]
I'm afraid this moved the problem from Safari to Firefox, as `navigator.clipboard.write` and `ClipboardItem` don't exist in Firefox.

**Comment by hamed-musallam** [comment]
@targos 

actually the copy and paste not working in firefox, there is no safe way to do it in firefox.

@lpatiny 

would you prefer to show a message that this feature is not supported in Firefox?

**Comment by lpatiny** [comment]
Indeed a message showing it is not supported is ok.

**Comment by hamed-musallam** [comment]
@lpatiny @targos 

What about injecting an HTML element into the document and use the execCommand("copy") function to copy the selection to clipboard and once it is done we can then remove it from the document   

```ts

  const inputElement= document.createElement('input');
  inputElement.value = 'Test Text';

  inputElement.style.position = 'fixed';
  inputElement.style.pointerEvents = 'none';
  inputElement.style.opacity = '0';
  document.body.appendChild(inputElement);
  img.select();
  document.execCommand('Copy');
  document.body.removeChild(inputElement);

```

**Comment by lpatiny** [comment]
This feature while currently supported is deprecated: https://caniuse.com/mdn-api_document_execcommand_copy

So I would rather display a message that using old technologies especially an alternative exists today.

Did you also follow this repository https://github.com/zakodium-oss/dom-to-html ? We also had the issue for Safari and I wonder if it was solved. https://github.com/zakodium-oss/dom-to-html/blob/main/src/copyToClipboard.ts

**Comment by lpatiny** [comment]
The 'copy' trick will only copy pure text anyway. No images, no html.

However there is a flag in firefox:

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

So once it should be compatible ... But it is useless to implement 'copy' in the meantime because it is useless.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1619947

**Comment by hamed-musallam** [comment]
@lpatiny 

Actually, I already implemented it to copy an image but in any way, we can wait until they implement ClipboardItem in firefox 

```ts
  const img = document.createElement('img');
  img.src = image;

  img.style.position = 'fixed';
  img.style.pointerEvents = 'none';
  img.style.opacity = '0';

  document.body.appendChild(img);
  const range = document.createRange();
  range.selectNode(img);
  window.getSelection()?.addRange(range);
  document.execCommand('Copy');
  document.body.removeChild(img);
``
