### ISSUE TITLE
Adding new chemical structure fails

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1686]
There is a new bug that appeared, when we try to add a second structure it does not appear.

It would be nice to have a testcase if possible so that there is no more regression for tis.

![2022-08-11 07 12 19](https://user-images.githubusercontent.com/1484241/184068396-3611464c-5a33-4449-86b4-3d3bcadb3e43.gif)

**Comment by hamed-musallam** [comment]
@lpatiny 

it is a problem in the style and not in the functionality

**Comment by lpatiny** [comment]
And how to fix it ?

**Comment by hamed-musallam** [comment]
@lpatiny 

in the old way i include Responsive Chart  component inside the Slider component, for some reason when we slide to left or to right the Responsive Chart calculate the parent div dimention wrongly.

so i move the   Responsive Chart and set it as the parent component for the slider component
