### ISSUE TITLE
Test case of shortcuts for processing

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1694]
https://user-images.githubusercontent.com/1484241/184194187-ec1fc1ae-aea8-4a5e-b8f2-bfba216664ab.mp4

**Comment by wadjih-bencheikh18** [comment]
clicking A in the first step does not apply apodization filter, instead it activate phase correction filter

https://user-images.githubusercontent.com/56769876/184373211-a1b5a864-334e-4677-92ce-a01a9eb62e52.mp4
