### ISSUE TITLE
Import varian

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1710]
Could we check that this file can be uploaded in NMRium for Philipp Weller

[Butyl_acetate_20160628.zip](https://github.com/cheminfo/nmrium/files/9352674/Butyl_acetate_20160628.zip)

**Comment by lpatiny** [comment]
This will be related to the new procedure to upload files using nmr-load-save

**Comment by jobo322** [comment]
it was done by e97a6e27b7ca558b65d3f827a82c7eb275531d1e
