### ISSUE TITLE
SplitPane bug

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [cheminfo/nmrium#1713]
https://user-images.githubusercontent.com/56769876/185176492-1f94689a-ecd6-4783-a8d6-fe798404dcf0.mp4

**Comment by lpatiny** [comment]
I'm surprised this bug exists. I think we are using the component from analysis-ui-components and there we can not reproduce this bug. https://zakodium-oss.github.io/analysis-ui-components/

**Comment by lpatiny** [comment]
@wadjih-bencheikh18 Do you have the same problem on https://dev.nmrium.org/#/SamplesDashboard/zmqbd0fnnqc/Viewdatacytisinedatacytisine1Hjson ? I can not reproduce it.

**Comment by wadjih-bencheikh18** [comment]
> Do you have the same problem on

No I cannot reproduce it too here,
just in COSY ethylbenzene 1H,1H it moves slowly

**Comment by targos** [comment]
https://github.com/zakodium-oss/analysis-ui-components/issues/209
