### ISSUE TITLE
If more than one molecule, problem with referenced molecule

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1714]
In ranges and integrals when we specify a molecule for the sum of atoms and that there is more than one molecule the saved .nmrium file does not remember this information.

**Comment by lpatiny** [comment]
Apparently the origin of the problem is that each time we load a '.nmrium' file the id of the molecules are regenerated.

**Comment by lpatiny** [comment]
Duplicate of https://github.com/cheminfo/nmrium/issues/1719

**Comment by wadjih-bencheikh18** [comment]
@lpatiny Would you please close this issue if it's fixed
