### ISSUE TITLE
Toggle ranges preferences

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1721]
If you take as example "FULL ethylbenzene" and create an 'auto range picking' you can toggle small chart on the spectrum (there are 2 toggle button).

You can then switch to 2d and go back to 1d spectrum and the toggle button are not correct anymore.

![2022-08-25 11 30 58](https://user-images.githubusercontent.com/1484241/186630691-d1a5b9e1-a1bd-4fc5-9592-c574c7381ac5.gif)

Toggling those little charts is related to the currently displayed spectrum (and therefore should be related to an 'id' (v4) of the spectrum !

In the 'view' context we need to add a property 'ranges' that is an array containing the following properties:
- spectrumID
- showMultiplicityTree
- showJGraph

**Comment by lpatiny** [comment]
there should also be the property 'showIntegral'

![image](https://user-images.githubusercontent.com/1484241/186631829-782a2339-9dd8-47f2-8658-ca29584a0d4f.png)

There is a small trick for this one, IF the nucleus is '1H' then the default value is 'true' otherwise it is false

![image](https://user-images.githubusercontent.com/1484241/186632075-3854c513-6542-4bf7-ab8f-0b6b71b67d18.png)

**Comment by wadjih-bencheikh18** [comment]
> In the 'view' context we need to add a property 'ranges' that is an array containing the following properties:
> 
> * spectrumID
> * showMultiplicityTree
> * showJGraph

I found out that it's already saved in the state `state.toolOptions.data`
and the bug is fixed.

I don't know if we have to refactor it

**Comment by wadjih-bencheikh18** [comment]
Also would you please check if `fix integral values` btn need to be fixed

**Comment by lpatiny** [comment]
Yes I would still refactor it to a new property view.ranges so that everything related to the currently displayed information is in the 'view'.

**Comment by lpatiny** [comment]
The fix integral values should not be changed for now.
