### ISSUE TITLE
Refactor active spectrum

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1723]
We need to add a new property in 'view' called 'spectra'

This new `spectra` property will be an object with the property:
- currentSpectrumId

https://github.com/cheminfo/nmrium/blob/84f399fdf053fa866a554091b72b3c408982e34e/src/component/hooks/useSpectrum.ts#L7-L18

**Comment by lpatiny** [comment]
Currently there can be only one active spectrum at the same time.

You can change from one category of spectra to another. Each category keeps his currently selected spectrum.

![2022-08-25 14 40 27](https://user-images.githubusercontent.com/1484241/186667258-8b91a3c0-fc9c-4102-9e35-f17f7a12a723.gif)

@wadjih-bencheikh18 tell us if you see some problem in this refactoring as it can have side effects that I currently don't see.

**Comment by wadjih-bencheikh18** [comment]
> Currently there can be only one active spectrum at the same time.

I didn't undersand what do you mean in this comment.
there's only one active spectrum but each tab active spectrum is saved in `tabActiveSpectrum`

**Comment by lpatiny** [comment]
I added some comments in the PR
