### ISSUE TITLE
Rename types MoleculeObject / Molecule

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1727]
I find the type names `Molecule` and `MoleculeObject` quite confusing.

https://github.com/cheminfo/nmrium/blob/5c43d1fdc5fbd5875d432ec2a7a157653ee68037/src/data/molecules/Molecule.ts#L6-L17

Please could you rename:
- Molecule -> InternalMolecule
- MoleculeObject -> Molecule

Like that it would be more clear that InternalMolecule is a Molecule with couple of extra properties (mf, mw, svg, atoms)l that is used internally.

**Comment by stropitek** [comment]
> Like that it would be more clear that InternalMolecule is a Molecule with couple of extra properties

I think of variables / types exported with the `Internal` prefix more of private and not exported.

I think `Molecule` and `ExtendedMolecule` (the one with the additional properties) makes more sense.

**Comment by lpatiny** [comment]
I hesitated between those 2 names. ExtendedMolecule is used in openchemlib https://github.com/Actelion/openchemlib/blob/master/src/main/java/com/actelion/research/chem/ExtendedMolecule.java (but Molecule as well ...).

I thought it was 'Internal' because from outside NMRium those 'extended' values are not accessible but we could decide what we systematically use as prefix / suffix for
- accessible from outside
- accessible only from inside the project
- accessible only from inside a file

**Comment by stropitek** [comment]
I don't think we have to be systematic, just try to use names that make sense and disambiguate when needed.

Since those are the data state molecules, they could be called `StateMolecule` and `StateMoleculeExtended` to differentiate them from the any `Molecule` type that comes from a library.
