### ISSUE TITLE
JEOL 1D files, unprocessed and processed

### ISSUE THREAD

**Issue by cp2ru2** [cheminfo/nmrium#1740]
Hi,
The raw or unprocessed JEOL files need to be zero filled before fft. If I try to just fft with no zero filling, it says something went wrong and there is no spectrum. After zero filling and fft, the spectrum looks fine. 

If I take that same raw data, process it in Delta (JEOL's software), the spectrum loads just fine, but the spectrum needs to be re-referenced with the CHCl3 peaking coming at about 9.68 ppm, instead of 7.26 ppm. 
[jeol_processed_unprocessed.zip](https://github.com/cheminfo/nmrium/files/9462446/jeol_processed_unprocessed.zip)

**Comment by lpatiny** [comment]
This can now be tested on https://dev.nmrium.org/ but the default value for phase correction is still problematic. We don't know how to get a good starting point for phase correction. See https://github.com/cheminfo/nmrium/issues/1690
