### ISSUE TITLE
set kind of shape to lorentzian by default for peaks

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#1747]

**Comment by jobo322** [comment]
@lpatiny @jliermann, I think the shape looks better as `gaussian` than `lorentzian` by default just after auto-peakpicking. 

![image](https://user-images.githubusercontent.com/12143935/188193440-090efeab-42ec-42da-890d-0ffebaf3bb8c.png)

It is really improved after the optimization step

![image](https://user-images.githubusercontent.com/12143935/188193721-32d030d5-f6c9-400c-86ef-fab837a713a7.png)

so I propose to keep `gaussian` as default for peaks out of the box from auto-peak-picking

**Comment by jliermann** [comment]
Thanks for the comment and the examples!
However, I would disagree. If you look at the sum spectrum, the optimized Lorentzian is better.

Gaussian:
![grafik](https://user-images.githubusercontent.com/40795855/188196472-ce26788d-a9c5-4b5d-a958-4ead9698bdab.png)

Lorentzian:
![grafik](https://user-images.githubusercontent.com/40795855/188196638-9d692590-7484-4998-b1b5-f2216075f31d.png)

And that is actually expected from FT theory which gives Lorentz-distributed lines:
![grafik](https://user-images.githubusercontent.com/40795855/188196278-fc004e2d-ef65-410e-b3c7-58ddca831010.png)

**Comment by jobo322** [comment]
GSD gets the `width` from the inflection points of the shape (experimental data), but the relation between `width` and `FWHM` depends of the kind of shape. Based on the wolfram pages of [lorentzian](https://mathworld.wolfram.com/LorentzianFunction.html) and [gaussian](https://mathworld.wolfram.com/GaussianFunction.html) I found that:

for Lorentzian shape, the relation between `width` and `FWHM` is:
```js
width = FWHM/sqrt(3)
```
for Gaussian shape, the relation between `width` and `FWHM` is:
```js
width = FWHM/sqrt(2 * Ln(2))
```
So, for a gaussian the difference between `width` and `FWHM` is an 17.7 %. But for a Lorentzian shape the difference is around 73 %. That is why, the gaussian shape looks better than lorentzian for peaks without optimization. 

Let me know if I am wrong.

**Comment by jobo322** [comment]
I did test the shape with the [simulated spectra](https://dev.nmrium.org/#/SamplesDashboard/cir2oryna9g/Viewtestssimulateddatatestssimulatedd1-12_j7json). It is drawen with a `gaussian` shape but the idea is the same.

**Comment by jobo322** [comment]
@jliermann @lpatiny I propose to use `pseudoVoigt` shape as default for peaks, 

![image](https://user-images.githubusercontent.com/12143935/191651617-edfcb3e2-d3e8-49c7-bec4-35b26b3981a1.png)

**Comment by jliermann** [comment]
> @jliermann @lpatiny I propose to use `pseudoVoigt` shape as default for peaks,

Sorry for not answering earlier! I appreciate that the Lorentzian shape causes optimisation issues but I still feel that the theoretically correct shape should be the default as this will have an educational impact. Other shapes should only be used by people how choose so intentionally.
