### ISSUE TITLE
JEOL processed data, x axis not correct

### ISSUE THREAD

**Issue by cp2ru2** [cheminfo/nmrium#1761]
Hi, When loading a JEOL processed data file in the jdf extension, the chloroform peak is at 9.68 ppm instead of the 7.26 ppm. It would be fine if I can just reference the peak, but the chemical shift of the other peaks are off as well. Attached is a spectrum of acetylsalicylic acid. The chemical shift of CHCl3 is 7.25 ppm, the CH3 of the acetyl group is 2.34 ppm in Delta (JEOL software), with a difference of 4.91 ppm. In NMRium, the peaks are 9.70 ppm and 3.55 ppm, with a difference of 6.15 ppm. So I am not sure why the chemical shift for the CH3 group is off, even when changing the solvent peak to be 7.26 ppm. When I reference the CHCl3 peak to 7.26 ppm, the CH3 then becomes 1.13 ppm, in NMRium. I hope this all made sense. I have attached the JEOL processed data of the acetylsalicylic acid in CDCl3
[rmc082522_aspirin_PROTON-1-1.zip](https://github.com/cheminfo/nmrium/files/9558879/rmc082522_aspirin_PROTON-1-1.zip)

**Comment by cp2ru2** [comment]
I should add that converting the jdf file to a jcamp works just fine. The jcamp spectrum has the correct chemical shifts and is referenced correctly in NMRium

**Comment by jobo322** [comment]
Hello @cp2ru2, thanks for advise this bug, could you share with us the jcamp you mention above? I would like to check why we are calculating wrongly the x axis

**Comment by jobo322** [comment]
Also, could you share with us, what is the origin offset and the origin frequency. Our converter catch those values:

- origin offset: -1005.61 Hz
- origin frequency 399782198.37825 Hz

**Comment by cp2ru2** [comment]
Hi, I have attached the same nmr file converted to jcamp 6.0
Thanks,
Martin
[rmc082522_aspirin_jcamp.zip](https://github.com/cheminfo/nmrium/files/9576246/rmc082522_aspirin_jcamp.zip)

**Comment by cp2ru2** [comment]
The X freq is 399.7822 MHz
The X offset is 5 ppm

**Comment by jobo322** [comment]
@cp2ru2, could you test again in [dev.nmrium.org](https://dev.nmrium.org)

**Comment by cp2ru2** [comment]
Hi Jose, 

it is still putting the solvent peak (CHCl3) at 9.69ppm
Martin

**Comment by lpatiny** [comment]
@jobo322 In the jcamp they have an unusual parameter:
`##$X_OFFSET= 5 $$ppm`
and likely we don't take it into account.
I wonder how it is in the native format. Do we correctly deal with the offset in ppm (and not in Hz) ?

**Comment by cp2ru2** [comment]
Ashok at JEOL might be able to help. ashok@jeol.com

**Comment by cp2ru2** [comment]
It looks like it works now for the jdf file. But the jdx (jcamp) is still flipped. Thanks for all your work on this

**Comment by cp2ru2** [comment]
Hi Jose,

do you know when the updated version will be deployed? Because the current
on on the nmrium.org site is still misplacing the solvent peak for the JEOL
processed data (jdf ) file.

Thanks,
Martin
