### ISSUE TITLE
General preferences dialog box should be centered vertically

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1771]
This issue is related to https://github.com/zakodium-oss/analysis-ui-components/issues/218 and the new dialog component should be reused (if possible) in this project.

When you click in the top right to open general preferences

![image](https://user-images.githubusercontent.com/1484241/192130499-da5067e5-fff0-4f26-83f2-c073b5a93c71.png)

- top banner so that it is similar to the one of 'about'

![image](https://user-images.githubusercontent.com/1484241/192130518-7b0cfc48-0af1-466e-8957-aeeaf02e381f.png)

- like for the 'about' dialog box it should be centered vertically

- the current size is too small on large sreen (HD).

I would try the following rules:
- minimal size is 600 x 400
- maximal size is 1000 x 800
- the width should not be larger than 80% of NMRium component width
- the height should not be larger than 80% of NMRium component height

@stropitek does those rules make sense ? I would not like to have super complex code just to deal with the dialog size.

**Comment by stropitek** [comment]
@wadjih-bencheikh18 it should be possible to use the Modal component from analysis-ui-components with the latest release

The component was designed such as either
- The modal size adapts to the content + maxWidth -> should be use for static content
- The modal width / height is fixed -> should be used for dynamic content
