### ISSUE TITLE
Generalize data source

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1775]
Currently if the data is coming from the server the only source that we allow in the .nmrium file is jcampURL.

We should make this more general and allow a FileCollection as source.

**Comment by lpatiny** [comment]
This is related to this issue in order to keep in cache the data (and possibly the parsed data).
- https://github.com/cheminfo/filelist-utils/issues/57

**Comment by hamed-musallam** [comment]
@lpatiny 

This deal only with the local files which is not always the case, we should keep it general and instead of have ```jcampURL``` we have ```url``` and it accept the local or remote path

**Comment by lpatiny** [comment]
@jobo322 This feature will have to be implemented in nmr-load-save. Is there some obvious problems with this approach ?

**Comment by hamed-musallam** [comment]
@lpatiny 

we need to consider of the remote file is a zip file

**Comment by lpatiny** [comment]
This is managed by filelist-utils. It should be transparent.

**Comment by hamed-musallam** [comment]
@lpatiny 

what is going to be the behavior if you drag and drop a zip file, filelist-util will  unzip the files and once you export as .nmrim will get the unzip files in the `source` object which is not available in your local machine because it is compressed

**Comment by lpatiny** [comment]
If you drag and drop something the source should stay empty. It is only when the data are coming from a server that we can store relative path to the '.nmrium' source file.

This could change in the future if we implement: https://developer.mozilla.org/en-US/docs/Web/API/FileSystem

**Comment by lpatiny** [comment]
How to deal with zip files ?

```js
{
  "version": 3,
  "spectra": [
    {
      "id": "53f1ff98-d146-4444-9a79-bbf8ee40102a",
      "source": {
        "fileCollection": [
          {
            "name": "data.zip",
            "size": 1234,
            "relativePath": "data/data.zip",
            "lastModified": 234234,
          }
        ],
        "filter": {general: {keepFID:1}, bruker: {expno:'10'}}
      }
    },
    {
      "id": "f1ff98d1-46e4-44da-b9bb-f8ee40102a69",
      "source": {
        "fileCollection": [
          {
            "name": "data.zip",
            "size": 1234,
            "relativePath": "data/data.zip",
            "lastModified": 234234,
          }
        ],
        "filter": {general: {keepFID:1}, bruker: {expno:'11'}}
      }
    },
    {
      "id": "f1ff98d1-46e4-44da-b9bb-f8ee40102a69",
      "source": {
        "fileCollection": [
          {
            "name": "data.fid",
            "size": 1234,
            "relativePath": "data/data.fid",
            "lastModified": 234234,
          },
          {
            "name": "data.acqu",
            "size": 1234,
            "relativePath": "data/data.acqu",
            "lastModified": 234234,
          },
          {
            "name": "data.acqus",
            "size": 1234,
            "relativePath": "data/data.acqus",
            "lastModified": 234234,
          }
        ],
        "filter": {general: {keepFID:1}, bruker: {expno:'11'}}
      }
    },
    {
      "id": "f1ff98d1-46e4-44da-b9bb-f8ee40102a69",
      "source": {
        "fileCollection": [
          {
            "name": "test.jdx",
            "size": 1234,
            "relativePath": "data/text.jdx",
            "lastModified": 234234,
          }
        ],
        "filter": {general: {keepFID:1}, jcamp: {index:'2'}}
      }
    }
  ]
}
```

/

**Comment by hamed-musallam** [comment]
@lpatiny 

then it would be ok to go with having a file collection inside the source and it should be a role to have a single experiment person zip file.


@CS76 

what do you mean by signal experiment, does it mean one spectrum?

**Comment by CS76** [comment]
> what do you mean by a single experiment, does it mean one spectrum?

Yes

**Comment by hamed-musallam** [comment]
@CS76 

Sorry for asking one more time,  is this apply also on the Bruker ? as i know we could have multiple spectra inside the Bruker

**Comment by hamed-musallam** [comment]
@CS76 

this will reflect on the shape of the nmrium object that you will get 
{
  "version": 3,
  "spectra": [
    {
      "id": "f1ff98d1-46e4-44da-b9bb-f8ee40102a69",
      "source": {
        "fileCollection": [
          {
            "name": "1h.zip",
            "size": 1234,
            "relativePath": "data/1h.zip",
            "lastModified": 234234,
          }
        ],
      }
    ,
    ranges:{values:[],options},
    peaks:{values:[],options},
    integrals:{values:[],options},
    ...etc
    },
{
      "id": "f1ff98d1-46e4-44da-b9bb-f8ee40102a69",
      "source": {
        "fileCollection": [
          {
            "name": "13c.zip",
            "size": 1234,
            "relativePath": "data/13c.zip",
            "lastModified": 234234,
          }
        ],
      }
    ,
    ranges:{values:[],options},
    peaks:{values:[],options},
    integrals:{values:[],options},
    ...etc
    }
    ]
   }

**Comment by hamed-musallam** [comment]
@lpatiny 

Are we going to assume that the Bruker or JCAMP should include one spectrum, whereas others who use the NMRium have to be sure that loaded file == one experiment?

**Comment by lpatiny** [comment]
No we can not assume this and we need this filter property.
Also the zip file contains one experiment but actually often 2 spectra (FID + FT) so even in this 'simple' case we will need the filter.

**Comment by hamed-musallam** [comment]
@lpatiny 

but can not rely on the `jcampSpectrumIndex` for the jcamp files and we should move to filter otherwise it will be a missy if the order of the spectra changes in the .nmrium file, beside that, actually we change the order of the spectra from multiple spectra analysis.

and I think this change has to be listed in the migration file

**Comment by CS76** [comment]
> @CS76
> 
> Sorry for asking one more time, is this apply also on the Bruker ? as i know we could have multiple spectra inside the Bruker

Sorry if I wasn't clear but Bruker's output (one experiment) often contains FID and FT spectra.

**Comment by lpatiny** [comment]
> but can not rely on the `jcampSpectrumIndex` for the jcamp files and we should move to filter otherwise it will be a missy if the order of the spectra changes in the .nmrium file, beside that, actually we change the order of the spectra from multiple spectra analysis.
> 
> and I think this change has to be listed in the migration file

But this was already done in the proposal I did

```
    {
      "id": "f1ff98d1-46e4-44da-b9bb-f8ee40102a69",
      "source": {
        "fileCollection": [
          {
            "name": "test.jdx",
            "size": 1234,
            "relativePath": "data/text.jdx",
            "lastModified": 234234,
          }
        ],
        "filter": {general: {keepFID:1}, jcamp: {index:'2'}}
      }
    }
```

Now the problem I see if when we have a zip file containing many jcamp that contain many spectra. We will probably need also a zip filter.

**Comment by jobo322** [comment]
done by https://github.com/cheminfo/nmrium/commit/8aad5c6878595c77f080ae5c9ba6686479c95cd9
