### ISSUE TITLE
Testcase of drag / drop of a folder

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1779]
We should simulate the drag and drop of this folder

https://github.com/cheminfo/nmrium/tree/main/test-e2e/data/bruker

In the browser when we drag / drop a folder we have a 'filelist' that is actually a 'flat' structure meaning that if there are some recursive folder and files they all end up as a simple array.

In order to simulate a drag / drop of a folder I would expect that you simply need to send to your function (https://github.com/cheminfo/nmrium/blob/b1eb89cbbbe48fc6789e87502ded2a58e474784f/test-e2e/NmriumPage.ts#L96-L101) the recursive list of the files

To get the recursive list you could get inspired by:

https://github.com/cheminfo/filelist-utils/blob/main/src/fileListFromPath.ts

**Comment by wadjih-bencheikh18** [comment]
Drop a list of files test is already implemented

https://github.com/cheminfo/nmrium/blob/b1eb89cbbbe48fc6789e87502ded2a58e474784f/test-e2e/core/import.test.ts#L103-L108

**Comment by wadjih-bencheikh18** [comment]
@lpatiny i think this issue can be closed since uploading list of files test is already implemented

**Comment by lpatiny** [comment]
Implemented
