### ISSUE TITLE
Nucleus off / off

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1782]
@jobo322 could you check why when we drag / drop this file

[13.zip](https://github.com/cheminfo/nmrium/files/9672585/13.zip)

Has nucleus off / off

![image](https://user-images.githubusercontent.com/1484241/192979353-edca5af7-1ed0-44ec-9e9b-6d06d50d7d1f.png)

**Comment by jobo322** [comment]
it was fixed in c9fcbf4bdee6c224e5b2e573396fb7fba2072be9
