### ISSUE TITLE
Not obvious for the users that they have to double-click on the 3 dots to open the side panel.

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1800]
@lpatiny 

I got some feedback from the users who visited nmrXiv for the first time and use NMRium that it is not obvious that they have to double-click on the 3 dots to open the side panel.

Any suggestion to improve the user experience?

**Comment by lpatiny** [comment]
Duplicate https://github.com/cheminfo/nmrium/issues/1768
