### ISSUE TITLE
Display 2D fid of jres fails

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1801]
[23.zip](https://github.com/cheminfo/nmrium/files/9733036/23.zip)

@hamed-musallam you may need some help from @jobo322 to solve this issue

**Comment by hamed-musallam** [comment]
@lpatiny 

the matrix is 20 * 8192  and most of the values inside the matrix are 0.

**Comment by hamed-musallam** [comment]
@jobo322 

Can you check if there is a problem with the 2d fid parser? does this data correct?

**Comment by jobo322** [comment]
just to keep this link in the right place, there kirk marat answer a lot of question about nmr acquisition parameters

https://qa.nmrwiki.org/users/40/kirk-marat/

**Comment by jobo322** [comment]
It seems to be working
