### ISSUE TITLE
Remove 'fromJcamp' from NMRium

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1811]
Currently the examples that have in the .nmrium files 'jcampURL' as source call the code 'fromJcamp'.

Like for drag / drop it should call 'nmr-load-save'

**Comment by hamed-musallam** [comment]
related to  https://github.com/cheminfo/nmrium/issues/1811

**Comment by jobo322** [comment]
Yes, there is a pr that remove the dependency of nmr-parser

**Comment by jobo322** [comment]
It was closed with #1811
