### ISSUE TITLE
uuid instead of title ?!

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1813]
When we drag / drop jcamp files we see a UUID in the list of spectra rather that the title

![image](https://user-images.githubusercontent.com/1484241/195598526-9322d6d0-0ab5-4729-8006-95187aec5e7a.png)

@jobo322 could you check this problem ?

**Comment by jobo322** [comment]
A preview of the fix is 

https://deploy-preview-1817--nmrium.netlify.app/

for bruker data I'm using the name of the folder + expno
