### ISSUE TITLE
The integral values a placed under the x-axis. This should be changed to in between the axis and the spectrum.

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1835]

**Comment by hamed-musallam** [comment]
@lpatiny 
this is what we have currently and the other image is what they looking to have but this raises another question, We display once we select the spectrum, do want to keep the same behavior and just change the position of the integration and have the same shape and what if we are in the stack mode 

![image](https://user-images.githubusercontent.com/35760236/198047760-d9fed392-97de-447d-9fd0-76dbbf0ca1c9.png)

![image](https://user-images.githubusercontent.com/35760236/198047638-52e655b9-988d-40da-a7c1-6da24ef19eea.png)

**Comment by lpatiny** [comment]
Looks good !

Please take care than when the number is less than 10 there is no overlap between the lines and the first digit

![image](https://user-images.githubusercontent.com/1484241/198250825-0b131e3b-bbc6-4518-8cdf-f1b434d86260.png)

The vertical lines could be smaller and the text slightly higher.

Can you also display those integrals in the 'Ranges' mode when the integral are displayed ?
