### ISSUE TITLE
The copy to clipboard option in the Export As does not work. The save as png option needs an option to set the resolution of the image.

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1837]

**Comment by lpatiny** [comment]
@hamed-musallam This issue if for you. Nothing against setting resolution if possible.

**Comment by hamed-musallam** [comment]
@lpatiny 

I'm wondering why he needs a resolution option because he has the other option to save as SVG if he looking for a high-resolution image.

**Comment by lpatiny** [comment]
Indeed SVG will always be better.

**Comment by hamed-musallam** [comment]
@CS76 

can you check this, if you see it is acceptable, please close the issue

**Comment by CS76** [comment]
Yes, I agree. SVG is always better. I also conveyed the same to our user. We can close this.
