### ISSUE TITLE
Split table to display spectrum information

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1843]
Please split in 2 and create 2 tables (while keeping only 1 search box)

![image](https://user-images.githubusercontent.com/1484241/198310499-12764790-96a6-4408-b214-3b85e50ec6e9.png)

The 'info' should be a table called 'Spectrum information'

The 'meta' should be a table called 'Other parameters'

**Comment by hamed-musallam** [comment]
@lpatiny 

Do the two tables are going to take equally half of the vertical space?

**Comment by lpatiny** [comment]
No the scrolling is like today. First all the info and if you scroll down you will see the meta.
