### ISSUE TITLE
Is clipboard-polyfill really useful?

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#1848]
The npm package emits a deprecation warning and the readme says that what it does is now supported by all major browsers, including Firefox: https://github.com/lgarron/clipboard-polyfill#readme

**Comment by lpatiny** [comment]
@hamed-musallam There was one exception no ?

**Comment by hamed-musallam** [comment]
@lpatiny 

we use this package to solve the problem of copying the text and HTML to the clipboard in Firefox,  and until this moment as far as I know there is no way to copy HTML to the clipboard in firefox

**Comment by hamed-musallam** [comment]
@lpatiny 

the only exception is we can not copy image to clipboard

**Comment by targos** [comment]
It seems that the deprecation was too early: https://github.com/lgarron/clipboard-polyfill/issues/149
