### ISSUE TITLE
NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by NRayya** [cheminfo/nmrium#1850]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/82588017/198548953-e600c56a-8d1e-452e-990a-f8cebcaaba26.png">

Here are the files, we are facing the issue with datasets 2,6, and 7
https://cloud.uni-jena.de/s/588LfmRnyTbiDT3

**Comment by lpatiny** [comment]
did you check in the developper tools the list of query that were done and what was the answer to those queries ?

**Comment by hamed-musallam** [comment]
it is not related to the NMRium this should be moved to the wrapper
