### ISSUE TITLE
Database panel and display scroll position

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1854]
When scrolling in the database panel would it be easily possible to display the current position and the total number of rows ?

![2022-10-28 17 12 48](https://user-images.githubusercontent.com/1484241/198672109-a20b36ed-57e7-43c0-9280-e35d9adba460.gif)

**Comment by hamed-musallam** [comment]
@lpatiny 

as I can see we have to keep the mapping for the database for two reasons if we need to have this feature in the react-table:

1- create rows per coupling constant and by that, I can use rowspan to have the current shape of the table.
2-  I rely on the index of the last visible element on the screen which I get from the mapped data.

 I created a demo for the sticky footer that shows a counter.
