### ISSUE TITLE
Copy result from multiple spectra analysis

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1875]
when clicking on 

<img width="251" alt="image" src="https://user-images.githubusercontent.com/1484241/200189106-4281affa-4a04-4196-ba51-373f7479d0f7.png">

there should be a feedback when the result is in the clipboard like with other copy features.

**Comment by hamed-musallam** [comment]
@lpatiny 

we have a feedback message, Are you sure that it does not appear ?
![image](https://user-images.githubusercontent.com/35760236/200521915-d0ba4d7a-7587-49e7-af05-d65843b20e73.png)

**Comment by lpatiny** [comment]
You are right. After testing I could reproduce the issue that must be general as well. If you resize the window (shrink the window) the message is outside the visible page.
