### ISSUE TITLE
Resizing ranges and recalculate multiplicity

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1880]
In many case when we resize a range we would like that the multiplicity is being reevaluate. This means that the same method should be called as the one when we SHIFT + select a range.

![2022-11-07 15 28 34](https://user-images.githubusercontent.com/1484241/200408839-96a90fda-9e1e-4ca4-8858-57e2a4a197d9.gif)

I'm currently not sure if this should be done systematically. On mouse over in the top right of the range highlight are we able, without hacking, to add a 'reload' icon that when you click on it, it redo the calculation and replace the current range ?

**Comment by hamed-musallam** [comment]
@lpatiny 

I think it is better to revaluate the multiplicity once the resize is completed, Are you ok with this way?

**Comment by lpatiny** [comment]
Yes sure it may be a super long process if we make multiplet-analysis
