### ISSUE TITLE
Add header in the list of spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1881]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/1484241/200433500-1d630519-acd2-4bab-989b-a8c74995be0a.png">

We should display the column name in a header.

**Comment by hamed-musallam** [comment]
@lpatiny 

it seems not all the column come from the ```info``` or ```meta``` object, for example, the ```name``` and ```color``` and ```visible``` of spectre come from ```display``` object 

What do we have to do in this case?

What are the default columns?

Do need to store the preferences inside the local store per workspace?

**Comment by hamed-musallam** [comment]
@lpatiny 


Are we will have different columns per nucleus or it the same?

**Comment by lpatiny** [comment]
Let's plan different column per nucleus like for most of the other preferences.

**Comment by lpatiny** [comment]
For the 4 following properties we could have checkbox to show / hide them

- `color`
- `visible`
- `display`
- `name`

**Comment by hamed-musallam** [comment]
- #1884
