### ISSUE TITLE
distinct color by class

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1882]
Recolor spectra by class using contextual menu (clicking on the header of the spectra list)

**Comment by hamed-musallam** [comment]
@lpatiny 
What class do you mean, Are you meaning we have a pre-set list of colors and we can select one of them

**Comment by lpatiny** [comment]
Now that it is possible to load meta information this feature can be implemented.

You can load meta information and display it in a column in the Spectra Panel

![image](https://user-images.githubusercontent.com/1484241/211139638-ed24d6f3-a8b1-4ed2-b249-afc51292cd3f.png)

A very useful feature is to be able to recolor the spectra based on the distinct values present in a specific column.

So we should be able to click on the header of the table and add a contextual menu with the only option 'Recolor based on distinct value'

When this option is selected we will first check how many categories we have (in this case Pre, W2, W6 and W8). So for those 4 categories we will select a new color (based on our selected colors) and we will set this new color for all the spectra.

In the future (or directly ?) we could have a dialog box that allows to have the preselected colors but also the possibility to provide custom colors for each category.
