### ISSUE TITLE
Spectra list and meta / info information

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1884]
From preferences we should be able to add unlimited number of columns by selecting jpath.

This is related to:

https://github.com/zakodium-oss/analysis-ui-components/issues/252

**Comment by hamed-musallam** [comment]
@lpatiny 

Do you mean to add a custom column in the spectra list from meta or info?

![image](https://user-images.githubusercontent.com/35760236/200843583-47d25e6c-7d8e-42f7-a23b-c1234de3b562.png)

**Comment by lpatiny** [comment]
Yes exactly. We should also be able to hide the default one that are actually coming from info if I'm not wrong.
