### ISSUE TITLE
Add filter to all the spectra based on the matrix generation preferences

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1893]
Once those options are created:

https://github.com/cheminfo/nmrium/issues/1892

We should update / add the ml-signal-processing filter to all the spectra of the current nucleus.

In the matrix generation panel there should be a button 'create' or 'update' to apply the filter to all the spectra when preferences changes.

**Comment by hamed-musallam** [comment]
closed by [#2023](https://github.com/cheminfo/nmrium/pull/2023)
