### ISSUE TITLE
Export current spectrum as jcamp if 1D

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1898]
If there is one spectrum selected and it is a 1D there could be one more export possibility:

Export current spectrum as JCAMP-DX

There is more or less a good example here but we should take care if it is a FID or a FT file.

https://github.com/cheminfo/convert-to-jcamp/blob/master/src/__tests__/from1DNMRVariables.test.ts#L39-L84

@hamed-musallam Could you try to implement this ?

This will require as dependency `convert-to-jcamp`

It will use: [from1DNMRVariables](https://github.com/cheminfo/convert-to-jcamp/blob/master/src/from1DNMRVariables.ts)

**Comment by targos** [comment]
Do you think it's more intuitive than right click -> export as jcamp directly in the list?

**Comment by lpatiny** [comment]
I was thinking about it. Maybe we could allow both.

**Comment by lpatiny** [comment]
Or it is easier to implement we can only have the export as JCAMP-DX with right click on the spectrum
