### ISSUE TITLE
Select more than one spectrum

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1901]
In the spectra panel we should be able to select more than one spectrum using CTRL and SHIFT like in the file explorer.

@targos @stropitek Any input about how to deal with those selections ? Should everything be done by hand ?

First application will be to allow to show or hide a selection of spectra

<img width="77" alt="image" src="https://user-images.githubusercontent.com/1484241/201434414-ebfae196-8b63-4bf1-a4f7-4ca4df86f44d.png">

**Comment by lpatiny** [comment]
There is also some weird effect when you quickly click on spectra. Previous selected spectra are sometimes not removed.

![2023-02-22 22 56 55](https://user-images.githubusercontent.com/1484241/220768906-2cde58f3-a3b2-45ef-a4f5-0dc1e7337448.gif)

**Comment by hamed-musallam** [comment]
@lpatiny 

it seems to me after I dig down in the code, the fast mouse move and click not triggering or blocking the Mouse Leave event, so the `hide function` not working and removing the highlight 

https://github.com/cheminfo/nmrium/blob/5c0556dd98ba73301b76729825c47d20350c3f2e/src/component/highlight/index.tsx#L257-L265

https://github.com/cheminfo/nmrium/blob/5c0556dd98ba73301b76729825c47d20350c3f2e/src/component/elements/ReactTable/Elements/ReactTableRow.tsx#L91-L101

**Comment by lpatiny** [comment]
The issue is that the component is `unmounted` and therefore the onmouseleave event is called on a component that does not exists anymore.

We could find out this using the following modification:

```
export function SpectrumName(props: SpectrumNameProps) {
  useEffect(() => {
    return () => {
      console.log('Bye');
    };
  });
  console.log('Hello');
  return (
    <div style={styles.info}>
      <div style={styles.icon}>
        <SpectraIcon {...props} />
      </div>
      <span>{props.data.display.name}</span>
    </div>
  );
}
```

There is no reason that with a mouse over the table and the rows are being recreated. It should only be recreated when we switch of tabs or we delete a line.
