### ISSUE TITLE
Highlight on mouse over an atom not working

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1903]
I'm expecting that when we are hover an atom that there is also the highlight of the range in the spectrum.

![2022-11-12 09 07 59](https://user-images.githubusercontent.com/1484241/201477924-48d07f1e-31d8-4fda-80fd-1a26386f6677.gif)

**Comment by hamed-musallam** [comment]
@lpatiny 

I can not reproduce the bug with the last version of NMrium locally

**Comment by lpatiny** [comment]
Me neither.
