### ISSUE TITLE
Save as and data / view / prefs

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1908]
NMRium should be able to save (and realod) the full state and not only the data.

This means that the 3 properties, `data`, `view` and `preferences` should be saved in NMRium file format and we need to add in the file format a first level with those 3 properties.

In the dialog box 'Save as'

<img width="357" alt="image" src="https://user-images.githubusercontent.com/1484241/201485931-ff642407-ca8c-42d5-8ce1-ecf63ac6df6d.png">

We should add a third option for data:
- Raw data, Data source, No data

We should add 2 checkboxes:
- include view (unchecked by default)
- include preferences (unchecked by default)

For the exact name of the preferences property we should adopt the same as in analysis-ui-components. See: 
- https://github.com/zakodium-oss/analysis-ui-components/issues/351

When reloading the `.nmrium` file the `data` part should be send to nmr-load-save while the `view` and `settings` should directly be managed by NMRium.

**Comment by lpatiny** [comment]
This feature will interest https://gigabytejournal.com/ and we should tell @jwist when it is implemented

**Comment by hamed-musallam** [comment]
@lpatiny 

1- we should take care that any change we will make in the .nmrium file data structure needs to be reflected in the migration script.

2- we need to be precise about what we need to have in the view or the preferences object, and we have to differentiate between what we have in the preferences that we have in the local state and what it should be in the preferences object.

can you compare what we have in the file right now and what it should look like

**Comment by lpatiny** [comment]
Currently the 'view' part only deal with few properties like the floating molecules but this will evolve in the future.

I don't think that with this change we should reconsider completely the state but simply store the 3 current states:
- data
- view
- settings (also known as preferences)

Indeed we will need a migration script and this is with nmr-load-save right ?

**Comment by hamed-musallam** [comment]
closed by #2003
