### ISSUE TITLE
Structure not loaded if loaded from URL

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1926]
When loading an assigned spectrum from an URL the structure is not loaded

https://dev.nmrium.org/#/SamplesDashboard/1ye5yuhl7b4/ViewdataacddataacdjcampWithAssignmentjson

However if you drag / drop the same file it is loaded correctly.

[assignment.jdx.zip](https://github.com/cheminfo/nmrium/files/10034968/assignment.jdx.zip)

**Comment by hamed-musallam** [comment]
@lpatiny 

Can you still reproduce it ?

**Comment by lpatiny** [comment]
Apparently fixed in 741646d883990c099e63e096cd96900cb3a6b5c4
