### ISSUE TITLE
Move filters to nmr-processing

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1930]
`nmr-processing` should be able to reprocess the filters in a batch mode (as an option).

We should add an array of filters and nmr-processing should so all the work taking into account at which level you want to stop and which filters are active.

**Comment by lpatiny** [comment]
Actually it should not be in nmr-load-save but rather in nmr-processing as Michael suggested.

**Comment by jobo322** [comment]
it was done in 470abab98a53a6ddee6bc93818b0cff90a41bdfb
