### ISSUE TITLE
Autoassignment crash

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1931]
Using the ethylvinylether example we have a crash if we try to apply an assignment.

This requires to have the panel 'autoassignment active"

<img width="424" alt="image" src="https://user-images.githubusercontent.com/1484241/202722704-4f3b4ffe-6d4c-4278-ad51-162f736f6f05.png">

@hamed-musallam could you fix this bug ?

https://dev.nmrium.org/#/SamplesDashboard/rguvmna2c7e/Viewdataethylvinyletherdataethylvinylether1hjson

**Comment by hamed-musallam** [comment]
@lpatiny 
I used the same example but I can not reproduce this bug, it seems i'm missing something, can you test it again and give me a short video if the bug exists.

**Comment by hamed-musallam** [comment]
@lpatiny 

can you close this issue if you can not anymore reproduce it?

**Comment by lpatiny** [comment]
I can not reproduce it currently neither.
