### ISSUE TITLE
strange rescaling of integration

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#1938]
when a spectrum is loaded with ranges that not contain absolute values nmrium assign those values but the assignment seems to be wrong.

https://user-images.githubusercontent.com/12143935/203090398-9e7758c7-ceb3-4648-b4f8-ffeaaa05651d.mov

**Comment by hamed-musallam** [comment]
@jobo322 

can you check this issue and close it if it has been resolved

**Comment by jobo322** [comment]
it seems to be working well, thanks
