### ISSUE TITLE
Baseline correction of degree 3 does not work.

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1941]
Polynomial baseline correction of degree 3 seems not to work while levels 2 or 4 are ok.

![2022-11-21 11 53 20](https://user-images.githubusercontent.com/1484241/203113989-7d971b81-3bee-4b89-9679-144546c5569d.gif)

@jobo322 @hamed-musallam Not sure where the bug is.

**Comment by hamed-musallam** [comment]
linked to #1969
