### ISSUE TITLE
Baseline correction preview is not working

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1949]
Even if preview is activated we currently don't see the baseline preview.

**Comment by hamed-musallam** [comment]
@lpatiny 

i test this and it seems it is working, once I change the degree, I got this result 
![image](https://user-images.githubusercontent.com/35760236/203979537-9c24d70d-888b-42bf-874f-90988bb2f4ee.png)

**Comment by lpatiny** [comment]
The issue is that as soon as you enter this tool there should be already a baseline correction (the default one) that should be applied.

Also changing the algorithm should also update the preview.
