### ISSUE TITLE
Keep the same vertical zoom when zooming out using double-click

### ISSUE THREAD

**Issue by michelgravel** [cheminfo/nmrium#1958]
Would it be possible to keep the same vertical zoom when double-clicking? I find myself constantly having to zoom in vertically when I double click to zoom out horizontally. Thank you.

**Comment by lpatiny** [comment]
For now you can use the shortcuts `f` and `ff` to zoom out only horizontally or both.

You can also save your current zoom / spectra state using the number keys (example `1`) and call back this zoom state by pressing again this number.

With the mouse how you would zoom out in both direction if double click zoom out only horizontally ?

**Comment by michelgravel** [comment]
I was not aware of the number keys to call back a zoom. That solves all my problems! Thank you.
