### ISSUE TITLE
Append / Replace data state ?!

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1968]
Currently there is a bug when you try to upload many .nmrium files.

You can reach a situation in which you superimpose FID and FT files which should never be the case.

![2022-11-30 19 34 59](https://user-images.githubusercontent.com/1484241/204880686-699b38e2-0224-40ea-9965-c2276af7e56c.gif)

As well as bugs switching from one tab to another

![image](https://user-images.githubusercontent.com/1484241/204880658-5e417f91-86da-4794-affa-eff535c2bd03.png)

I think that when we load a .nmrium file the data state (and in the future config and view states as well) should be completely replaced.

The question raise when we drag / drop a mixture of .nmrium files, bruker files, jcamp files, etc

I think that we could first have the '.nmrium' loader and as soon as we meet a '.nmrium' file we stop and we should replace the FULL data / view / config state !

**Comment by hamed-musallam** [comment]
@lpatiny 

this was work well before because we reset the state, i will check and see what is happening

**Comment by lpatiny** [comment]
The simplest seems to be:
- nmr-load-save starts by loading `.nmrium` files. Once it found a file it returns immediately (will not process any other file). At the level of NMRium the state is completely (currently only the data state, we don't deal with view and preferences) replaced rather than append
- if there is no .nmrium file the return value of nmr-load-save has the property `append:true` and at the level of NMRium the state is append

We should already take the opportunity to add one level in `nmr-load-save` to have 3 possible properties:
- data
- view
- config
- append: true / false

Currently we will only have 'data' but in the future we will have in .nmrium files view and config information.

**Comment by hamed-musallam** [comment]
@lpatiny 

this means we have to make the changes at nmr-load-save before we can solve this bug

**Comment by jobo322** [comment]
I'm confused, if inside a fileCollection nmr-load-save catch a .nmrium file it should returns only the content of this file and ignore the rest?

**Comment by hamed-musallam** [comment]
@lpatiny 

i think we could have them, but apply them in the right order, first with the last .nmrium file and then jcamp,borker .... etc
it depends on, what is the normal behavior that you looking for.

pick up the first file is not an expected thing for the end user because he does not know what happens and how the NMRium deal with this scenario, this why I suggest we should show a message to the end-user and not allow all the drop files because he has multiple .nmrium inside it and by that he can know exactly how NMRium deal with this case

**Comment by hamed-musallam** [comment]
and if we need to make it better, we should show a modal that lists nmrium files that we found and he can pick which one should import
