### ISSUE TITLE
Rename filters properties

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1973]
Ignore does not seem the right term to use ... keep would sounds better

@jobo322 Please could you rename those properties and make them `true` by default ? The logic (and property names) in bruker-converter also need to change.

![image](https://user-images.githubusercontent.com/1484241/205084617-2a9b2398-75af-4c4f-845f-beb4e6e2a874.png)

https://github.com/cheminfo/brukerconverter/blob/b880d77624a73a701d8bfd273cdd415f053b4262/src/groupByExperiments.js#L17-L20

- keepFID = true
- keepFT = true
- keep1D = true
- keep2D = true

**Comment by jobo322** [comment]
it was done by 833e6271f7ed42ccd0f9d1563dcaa43c68151cb4
