### ISSUE TITLE
Create dataset to check integration

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1982]
We would need a dataset to be sure that when we do multi spectra analysis the integration is correct.

I propose we create 10 spectra with gaussians from 0 to 10 ppm at 500 MHz, 100'001 points containing only singulets:
- 2 ppm: peak width is 1Hz, height: 10, 20, 30, 40, 50 ...
- 5 ppm: peak width is 2Hz, peak height is 100, position is 4.75, 4.8, 4.85, 4.90, 4.95, 5.0, 5.05, 5.1, 5.15, 5.20
- 8 ppm: peak height: 100, peak width: 1Hz, 2Hz, 3Hz, ... 10Hz

This dataset should go in the simulate section:

![image](https://user-images.githubusercontent.com/1484241/205501955-f8198ce3-3617-4eaf-bcb3-d0fda17e684d.png)

And will allow to check multiple spectra integration.

**Comment by jobo322** [comment]
it was done
