### ISSUE TITLE
Copy the legend as well in the clipboard

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1985]
![image](https://user-images.githubusercontent.com/1484241/205564527-e7b6c8b9-1554-4e5a-baa7-2316a43ecaf3.png)

**Comment by hamed-musallam** [comment]
@lpatiny 

When do you want to copy the legends? I mean from the perspective of the user

**Comment by lpatiny** [comment]
The goal is that when you copy the spectrum to clipboard, export PNG or export SVG the legend is in the image that is in the clipboard.

Because legend is currently HTML this can be a real issue (also at the speed point of view if it is implemented in svg) so we could keep this for later.
