### ISSUE TITLE
Saving workspace default behavior

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1991]
We have 4 kinds of `workspace`: 
- default workspace (hardcoded in the NMRium project)
- custom workspaces (injected from the property in the NMRium component)
- user workspaces (saved by the user)
- from .nmrium file (in the future)

When are the preferences saved ? Currently you need to go in the General settings and click on 'Save'. However if it is a custom workspace (or from .nmrium) it will not be saved even if you press save ...

Maybe it would be more natural that NMRium remembers the last selected workspace and saves systematically all the changes to the current workspace.
This could work with default workspace and user workspace but what about `custom` workspaces and `.nmrium` workspaces ?

An alternative could be to add a small save icon next to the drop down menu.

![image](https://user-images.githubusercontent.com/1484241/205746352-a72a7f79-75f6-40ad-9617-e3203a1ee5d5.png)

And this button is active when the currently selected workspace changes and is 'saveable'. In this case ONLY the currently selected workspace will be saved.

The buttons of the dialog box could then as well be changed for `done` rather than Cancel / Save

![image](https://user-images.githubusercontent.com/1484241/205746590-3601202c-5fe5-4fca-9857-e1c1c23e3308.png)

Because currently we don't know what will happen when you cancel or save.

A save button could be placed as well next to the drop-down menu:

![image](https://user-images.githubusercontent.com/1484241/205746725-12e84b4c-1ba2-41ce-afc2-43ecc5dacf7d.png)

This button would only be present if there is something to save (either the default workspace changed or you changed some preferences).

If the workspace is NOT saveable (because it is readonly, from '.nmrium' or CustomWorkspace) the button could still be there but there should be a dialog box:
This is a read-only workspace, please enter a name to create a User workspace. The new workspace will then be created, saved and selected.

**Comment by hamed-musallam** [comment]
closed by #2003
