### ISSUE TITLE
Multiplet analysis change the original data !!!!

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2013]
There is a weird problem when you make a multiplet analysis and it is not on the baseline. The data is being moved.

I suspect that we send a 'subarray' of a typed array and that this data is changed in place. If you send a subarray it shares the same buffer as the original data: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/subarray

![2022-12-15 17 04 21](https://user-images.githubusercontent.com/1484241/207909684-30036a3f-2c3c-4608-8f32-b29b137c96ad.gif)

@jobo322 Could you fix this bug ? Either by sending a copy of the data or by fixing multiplet-analysis.

**Comment by jobo322** [comment]
done by https://github.com/cheminfo/nmrium/commit/8aad5c6878595c77f080ae5c9ba6686479c95cd9
