### ISSUE TITLE
LoadJCAMPModal becomes older 

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#2024]
we could use [readJcampFromURL](https://github.com/cheminfo/nmr-load-save/blob/master/src/reader/readJcamp.ts#L35-L47) @hamed-musallam  what do you think?

**Comment by hamed-musallam** [comment]
@jobo322 

yes, you are right, you could use it

**Comment by jobo322** [comment]
seems it was done by https://github.com/cheminfo/nmrium/commit/b5eb3e77690397b3d5da9b1970a32bb2cf92c37c
