### ISSUE TITLE
Spectrum problem - Reversed spectrum

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2025]
The FT returns a reversed spectrum for some reason. I'm using https://go.magritek.com/. Thanks for any assistance.

[100412-1D EXTENDED+-JMW-720-086.zip](https://github.com/cheminfo/nmrium/files/10273178/100412-1D.EXTENDED%2B-JMW-720-086.zip)

**Comment by jobo322** [comment]
Inside of the data exists a jpg of the spectrum (expected result)

![data](https://user-images.githubusercontent.com/12143935/213016223-28433c8d-4d3e-483b-8f58-458b2236ecc6.jpg)

Topspin 3.6 result 

<img width="673" alt="image" src="https://user-images.githubusercontent.com/12143935/213015725-07d10f5d-aa2e-4e4f-8442-14194c6ff347.png">

nmrium result

<img width="334" alt="image" src="https://user-images.githubusercontent.com/12143935/213015860-de5bf362-e1db-4737-9fdc-a2eec766c8ae.png">

**Comment by jobo322** [comment]
Here there are two thing to manage:

1. add support for .SHIFT REFERENCE at the moment to calculate the parameter `frequencyOffset` 
2. exists an LDR called `REVERSE` with a boolean value

<img width="421" alt="image" src="https://user-images.githubusercontent.com/12143935/213295844-caac533a-4910-4684-8423-c660b4bf6cd7.png">

**Comment by jobo322** [comment]
With the first item solved, I obtained:

<img width="370" alt="image" src="https://user-images.githubusercontent.com/12143935/213296355-6773610c-4c71-40db-b9b1-37f6edb9736f.png">

So, the question @lpatiny is, should we add a filter to reverse the data after apply FFT? or just check for this REVERSE metadata and reverse the spectrum?

**Comment by lpatiny** [comment]
@jobo322 this reverse seems quite specific and I would not add a filter.

During FFT how to we determine the from / to in ppm ?

Can we change during normalisation of the spectra after the JCAMP-DX converter the values so that it is ok after FT ?
