### ISSUE TITLE
 jcamp file not recognized but jdx file is recognized 

### ISSUE THREAD

**Issue by NRayya** [cheminfo/nmrium#2029]
We have received this issue on nmrXiv which is related to NMRium: https://github.com/NFDI4Chem/nmrxiv/issues/645

**Comment by hamed-musallam** [comment]
this should be fixed in the current version of NMRium, can you test one of the sample  here https://dev.nmrium.org/

**Comment by NRayya** [comment]
@hamed-musallam yes it works now, thanks.

**Comment by hamed-musallam** [comment]
closed by https://github.com/cheminfo/nmrium/commit/d78acd43c8fa48727b8b176d1bcda938e17ac71b
