### ISSUE TITLE
exclude node_modules not working

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#2030]
@targos 

Can you check why `node_modules` are not excluded  in `tsc`
![image](https://user-images.githubusercontent.com/35760236/209301446-3baf90cb-298d-4ded-b1c5-59c9f976c311.png)

you can test it here
https://github.com/cheminfo/nmrium/pull/2023

**Comment by targos** [comment]
It seems to me that the correct thing to do is to fix `ml-signal-processing`.

**Comment by hamed-musallam** [comment]
closed by e79a8db9f248abd0f0c8eb84d52d868610d4b96a
