### ISSUE TITLE
Zipped 2D FID Bruker files not being recognized

### ISSUE THREAD

**Issue by NRayya** [cheminfo/nmrium#2031]
I tried few Zipped 2D FID Bruker files. They are supposed to result in a message saying 2D FID can't be displayed in NMRium now, but they were not recognized at all. Here are some links:

http://www.nmrshiftdb.org/download/NmrshiftdbServlet/60004137_H,H-COSY.zip?spectrumid=60004137&nmrshiftdbaction=exportspec&format=rawdata

http://www.nmrshiftdb.org/download/NmrshiftdbServlet/40256186_H,C-HMBC.zip?spectrumid=40256186&nmrshiftdbaction=exportspec&format=rawdata

**Comment by NRayya** [comment]
looking into the pulse program, I am not sure if those are avance files handled with Bruker topspin software

# 1 "C:/Bruker/TOPSPIN/exp/stan/nmr/lists/pp/cosygpqf"
;cosygpqf
;avance-version (00/04/28)
;2D homonuclear shift correlation
;using gradient pulses for selection
;
;$CLASS=HighRes
;$DIM=2D
;$TYPE=
;$SUBTYPE=
;$COMMENT=


# 1 "C:/Bruker/TOPSPIN/exp/stan/nmr/lists/pp/Avance.incl" 1
;Avance.incl
;
;avance-version (07/01/22)
;
;$CLASS=HighRes Incl
;$COMMENT=

**Comment by lpatiny** [comment]
Should be fixed now and you can test it on https://dev.nmrium.org
