### ISSUE TITLE
Structure editor can't read NMReData

### ISSUE THREAD

**Issue by NRayya** [cheminfo/nmrium#2040]
The structure editor used in NMRium ("Chemical structures" table) can't read the mol out of the NMReData when draged and dropped in it.

**Comment by lpatiny** [comment]
Can you upload here the molfile ? (you will have to zip it probably).

**Comment by NRayya** [comment]
Good afternoon @lpatiny  
Here is the tested NMReData file:
[test.nmredata.zip](https://github.com/cheminfo/nmrium/files/10360795/test.nmredata.zip)

And here is the mol out of it
[test.mol.zip](https://github.com/cheminfo/nmrium/files/10360833/test.mol.zip)

**Comment by lpatiny** [comment]
I don't see the issue. When I drag and drop your file (after having the correct .mol extension) the molecule is loaded correctly.

![2023-01-07 07 33 39](https://user-images.githubusercontent.com/1484241/211134822-de361af9-78eb-408d-a12a-ef8910c92e16.gif)

.nmredata is not a molfile extension but the extension of a zip file.

**Comment by NRayya** [comment]
Using the test.mol, I am receiving this error:
[screen-capture.webm](https://user-images.githubusercontent.com/82588017/211316989-e2ad013d-5a70-45ea-bdad-1224b20fe620.webm)

But in all cases, What I meant is that NMReData itself, not a mol file, should be able to generate a structure in the editor. If you agree I can open a feature request in the editor repo
