### ISSUE TITLE
Drag drop of jcamp does not work anymore

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2042]
If you drag and drop ethylbenzene-1h.jdx file (that is present in the repository) the spectrum is not loaded.

**Comment by targos** [comment]
Please add a test case similar to the existing ones in https://github.com/cheminfo/nmrium/blob/main/test-e2e/core/import.test.ts

**Comment by lpatiny** [comment]
The test will be done by @wadjih-bencheikh18 (maybe before the fix BTW).

**Comment by lpatiny** [comment]
I can not reproduce this issue anymore and it works correctly with the current version. It could be a problem with my preferences and we will have to soon give a report on the imported spectra, I current have no explanation.
