### ISSUE TITLE
Possibility to add parameters on the spectrum

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2043]

**Comment by hamed-musallam** [comment]
@lpatiny 

what do you mean by adding parameters on the spectrum, what is the use case for this?

**Comment by lpatiny** [comment]
In reports some software are adding information like 'Number of scan', 'Acquisition time', 'Pulse sequence', etc.

We would need to define preferences that allows to define the information to display. Could be something very similar to:

![image](https://user-images.githubusercontent.com/1484241/211920446-896f94b9-f24e-46e7-bb45-745a11bd7878.png)

This is something end users would like to get in the image or SVG they copy / save from NMRium.

I think it should be placed in the general preferences (a new tab called 'Title block'). There should also be a checkbox to show / hide this Title block.

The position by default would be top left (but could change in the future).

So it is the same place as the multispectra analysis peak tracker.

![image](https://user-images.githubusercontent.com/1484241/211922406-1b61ba8a-2bdc-4805-95f8-519a36f1cab7.png)
