### ISSUE TITLE
advance select component with search options 

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#2045]
- [x] create the select component https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

- [x] use this component instead of the column path field in spectra preferences and importation of meta information

**Comment by hamed-musallam** [comment]
@lpatiny 

we can not style the datalist  
![image](https://user-images.githubusercontent.com/35760236/211337854-d2e73455-73e9-41cd-a75c-858280b08470.png)

if you will need to do with this way https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist then i think we can just have the datalist in the Input component https://github.com/cheminfo/nmrium/blob/main/src/component/elements/Input.tsx

**Comment by lpatiny** [comment]
The goal is indeed to have the datalist in the input component.
