### ISSUE TITLE
Select multiple spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2051]
This is not an easy issue and the goal is to improve the method we select spectra. Currently either we have no spectrum selected or one spectrum selected. The behaviour at the level of the spectra panel is not intuitive. You need to unselect the spectrum to see them all without transparency.

Moreover in some cases we will need more than one spectrum selected.

I think the first step will be to check the code and decide how it can be achieved:
- check how to replace the currently selected spectrum by currently selected spectra (so convert to an array)
- probably decide that practically all our tools that exist today are deactivated if it is not exactly one spectrum selected (the current behaviour in fact).

This will allow in the future to implement new features like;
- scale a selection of spectra
- recolor a selection of spectra
- compare meta information of a selection of spectra
- ...

But all those new possibilities will be discussed in other issues.

**Comment by hamed-musallam** [comment]
@hamed-musallam 

1- The first step is to move the activeSpectrum from accepting `string` to an array `string[]`.
2- rework the features to work with multiple active spectrum
