### ISSUE TITLE
tool still active after closed

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#2066]
I found that the manual range picking is still active after close the tool by clicking over the icon.

![toolStillActiveAfterClosed](https://user-images.githubusercontent.com/12143935/212059355-61b1af54-9606-4e03-ac43-e7bdfc3cf7e3.gif)

**Comment by lpatiny** [comment]
Indeed this should not be a toggle button but a radio button. Clicking on a selected tool should have no effect.

Also if the selected tool is not available for a reason (like changing from FT to FID) we should select the 'zoom' tool.
