### ISSUE TITLE
Superimposition of 2D and vertical scroll

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2069]
When you have the superimposition of 2D spectra and no spectrum is selected I would expect that with the scroll wheel you do a vertical scaling in a similar way we do for 1D.

![image](https://user-images.githubusercontent.com/1484241/212181724-4766c559-a017-42df-862f-6e8f85049c9e.png)

**Comment by hamed-musallam** [comment]
@lpatiny 

I think if we have too many 2d spectra, the performance will not look nice, we can have it as you suggested but you have to expect a downside in the performance.

**Comment by lpatiny** [comment]
Yes sure I also expect this. But most of the time we only have 2 (HSQC and HMBC).
