### ISSUE TITLE
jpathToArray function ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2080]
I think the only way to deal correctly with the 'jpath' is to keep an array of strings in all the configuration files (.nmrium files) and internally.

So this means that in the drop down menu in which you select a path you need to create a map containing as key the `array.join('.')`:
```
{
"meta..solvent": ['meta', '.solvent'],
...
}
```

And display the key of the map in the menu. However when selecting the item you need to store the array.

If you don't do this we will always have some trouble with '.' that are in the key like 

[test.jdx.zip](https://github.com/cheminfo/nmrium/files/10461314/test.jdx.zip)

In which we have a '.' in Pulse sequence

![image](https://user-images.githubusercontent.com/1484241/213568620-33dbcdd9-27a8-40d0-92a7-f34c6dabc159.png)

If we select this field in the preferences for a new column no value is displayed.

![image](https://user-images.githubusercontent.com/1484241/213568476-bf1d4211-abe7-4666-b4e1-fa8b4e48e0a8.png)

We could also in the future have really 3 levels in the 'jpath'.

**Comment by lpatiny** [comment]
If we are sure that the jpath contains only 2 parts and the first part may not contain a '.' we could simplify the jpathToArray function:

```
const parts = jpath.split('.');
if (parts.length===1) return parts;
return [parts.shift(), parts.join('.')]
```

**Comment by hamed-musallam** [comment]
@lpatiny 

even if we have it as an array it will not solve our problem because we need to save the array back and forth inside the input.

It seems to me the best solution is to manipulate the keys once we load the spectrum, to have structure like this 

```ts
{
  meta:{
    nmrShift:{ value:"xxxx", key:"nmr.shift" },
    ...etc
    },
...etc
}
```

an map it again once we export the data to it original form 

```ts
{
 meta:{
    "nmr.shift":"xxxx",
    ...etc
    }
...etc
}
```

**Comment by hamed-musallam** [comment]
@lpatiny 

we applied a general solution to save the jpath as an array of keys instead of using it as a string with `.` separator. and map the value forth and back to the input field to display it in the proper way and save the value back to an array once we change it.
