### ISSUE TITLE
JEOL processed data showing incorrect scales

### ISSUE THREAD

**Issue by cp2ru2** [cheminfo/nmrium#2098]
Hi, when I use processed data file that the spectrometer emails me, the x axis is not correct. However, when I save the processed data using JEOL Delta software, and use that jdf file, it shows up correctly. Both files are jdf files and should be identical, but something is making them be read differently. 

Also, the raw data (fid file) has that error message saying something went wrong. You then have to zero fill and then do the FT to get the processed spectrum This was an issue previously and it was fixed. I am not sure why it is not working this time. 

Attached are the 3 files, the processed from the spectrometer, the processed from Delta and the raw data. Ashok from JEOL might be able to help @ak-jeol

[nmr files.zip](https://github.com/cheminfo/nmrium/files/10540091/nmr.files.zip)

- lineshape_raw.jdf - The FID
- lineshape good one.jdf - File after reprocessing in JEOL Delta Software
- lineshape wrong.jdf - Original file with wrong X axis

Expected values:
- 8.02 ppm for CHCl3 
- 2.05 ppm residual acetone

**Comment by jobo322** [comment]
Dear @cp2ru2, having a fast look to this problem, I saw that data in `lineshape_wrong.jdf` file is not only shifted with respect with the data into `line shape_good.jdf` the peak at 8 ppm is shifted to high field by 2 ppm while the signal at 2 ppm has only a shift of 1.13 ppm. 

<img width="317" alt="image" src="https://user-images.githubusercontent.com/12143935/215615287-7a1ed24e-e4f2-4208-9839-32c39d0a67ed.png">

Could you share an image of each expected result and how to reproduce those?

**Comment by cp2ru2** [comment]
Hi Jose,

The spectrum that you have in red is the correct one. The sample is CHCl3
in acetone-d6, so the expected chemical chemical shifts are 8.02 ppm for
CHCl3 and the residual acetone peak would be at 2.05 ppm (quintet,
CD2HCOCD3). So the line_good spectrum is the correct one. That file came
from saving it in the Delta software (JEOL's software) first as a jdf. It
shows up correctly in NMRIUM. The green spectrum is from a macro that the
spectrometer runs and then emails the user a copy of the jdf file. This one
is not correct as you can see the CHCl3 peak is at 5.89 ppm and the
acetone peak at 1.13ppm. @ak-jeol would be able to tell you what the
differences are between the instrument processed data and the processed
data saved from Delta.

NMRIUM has encountered this before and I think it was fixed. But somehow it
has reverted to NOT having the correct chemical shifts. Attached is a
screen shot from the previous Github thread #1772

Thanks,
Martin
[image: image.png]

**Comment by ak-jeol** [comment]
When I open all three files in our Delta program it opens fine and the referencing is correct.

But if I drop the file lineshape_wrong.jdf into nmrium it has incorrect

What I noticed was the differences in offset information

GOOD

***@***.***

BAD

***@***.***

Raw data if zerofilled to 32768 works fine.  We allow collection of non-power of 2 so we can control data collection as a function of resolution or acquisition time.

Regards

Ashok

From: cp2ru2 ***@***.***>
Sent: Monday, January 30, 2023 4:23 PM
To: cheminfo/nmrium ***@***.***>
Cc: Ashok Krishnaswami ***@***.***>; Mention ***@***.***>
Subject: [cheminfo/nmrium] JEOL processed data showing incorrect scales (Issue #2098)


Hi, when I use processed data file that the spectrometer emails me, the x axis is not correct. However, when I save the processed data using JEOL Delta software, and use that jdf file, it shows up correctly. Both files are jdf files and should be identical, but something is making them be read differently.

Also, the raw data (fid file) has that error message saying something went wrong. You then have to zero fill and then do the FT to get the processed spectrum This was an issue previously and it was fixed. I am not sure why it is not working this time.

Attached are the 3 files, the processed from the spectrometer, the processed from Delta and the raw data. Ashok from JEOL might be able to help @ak-jeol<https://github.com/ak-jeol>
nmr files.zip<https://github.com/cheminfo/nmrium/files/10540091/nmr.files.zip>

-

**Comment by cp2ru2** [comment]
Is there any progress on this issue? Thanks,
Martin

**Comment by ak-jeol** [comment]
Not sure if I can provide any further input into this thread apart from the fact that somehow non power of 2 data is being referenced incorrectly.

**Comment by jobo322** [comment]
both files are processed data, the offset is the same but the increment is different

<img width="373" alt="image" src="https://user-images.githubusercontent.com/12143935/227232499-c8fbff88-c2f5-4d10-ae5d-b8e7cb9bb775.png">

**Comment by lpatiny** [comment]
We have something a peak at 7.98. In Jeol software it appears really at 8.02 ? This would mean there is still a shift missing somewhere.

![image](https://user-images.githubusercontent.com/1484241/227460355-48e387cf-b273-415a-a02d-b7b5a340f472.png)

@ak-jeol please answer directly on Github website and not by email because we are loosing images otherwise.

**Comment by jobo322** [comment]
I got the same result in topspin

**Comment by lpatiny** [comment]
This issue appears to be solved now on www.nmrium.org

**Comment by cp2ru2** [comment]
Thank you very much! Works from my end.

Thanks again,
Martin
