### ISSUE TITLE
Number of digits

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2110]
When doing peak picking on cytisine we get in the peak panel:

![image](https://user-images.githubusercontent.com/1484241/216654377-e2aa3fee-6364-4a8d-ace7-754bd4d51586.png)

While in the settings we force 2 digits for the delta (ppm)

![image](https://user-images.githubusercontent.com/1484241/216654500-2ed6239c-79c5-4759-9479-87a8988d23dd.png)

The project relies on the library `numeral` and I would expect it is being used to format the number but looking at `3` it does not seem the case. @hamed-musallam could you fix this issue and check if it happens in other places ?

**Comment by hamed-musallam** [comment]
@lpatiny 

we have this because we cast the string to a number to be able to order the columns correctly, it is a global code, this change we did when we add reorder multiple spectra analysis columns.
