### ISSUE TITLE
Add one level in filters

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2113]
Currently all the filters but 2 have as parameter an object

![image](https://user-images.githubusercontent.com/1484241/216656821-e5b27565-1e34-438b-b433-1a6da4990ffa.png)

We would need for `Zero Filling` and `Shift X` also to have an object.

This will require a migration script.

**Comment by jobo322** [comment]
@lpatiny, the property names for those filter could be:
```js
{
  zeroFilling: { nbPoints: number },
  shiftX: { shift: number ),
}
```
