### ISSUE TITLE
Still unable to process some Bruker datasets

### ISSUE THREAD

**Issue by NRayya** [cheminfo/nmrium#2119]
I am testing the new release on https://dev.nmrium.org/ 
Using the following bruker dataset (and others), no spectrum was created, and no error message in the console: 

[60000976_13C.zip](https://github.com/cheminfo/nmrium/files/10581673/60000976_13C.zip)

**Comment by lpatiny** [comment]
Indeed the hierarchy of the folder has been changed manually. All the data are expected to be in a folder that contains a number and in this case all the data were moved outside the folder called '2' that is still present.

If you have the following data structure

![image](https://user-images.githubusercontent.com/1484241/216757322-d25dbe2c-7ca8-4ea1-9a0e-610d4cb3a234.png)

it works correctly.

We will make the parser more tolerant to this kind of manual modification.

**Comment by lpatiny** [comment]
This will be solved in https://github.com/cheminfo/brukerconverter/issues/84

**Comment by NRayya** [comment]
Thanks a lot
