### ISSUE TITLE
Why digitalFilter can not be disabled anymore

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2127]
Not sure why it is not possible to Disable Digital Filter

![image](https://user-images.githubusercontent.com/1484241/217444720-6714b18c-50a3-4c00-83da-dd24b87b40f5.png)

**Comment by hamed-musallam** [comment]
@lpatiny 

it seems it based on your request https://github.com/cheminfo/nmrium/issues/2114 or it is a misunderstanding from my side.

**Comment by lpatiny** [comment]
Indeed you are right i was not well written. Sorry for this.

The idea was that if you delete all the filters you should remove the Digital Filter and not disable it neither.

However it is probably still useful to allow to disable the filter with a click for educational purpose.
