### ISSUE TITLE
Rethinking meta information

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2128]
We need a way to have an example in one click that not only loads the NMR spectra but also the meta information.

This is a real case example that should work: 

[BariatricRats.zip](https://github.com/cheminfo/nmrium/files/10682265/BariatricRats.zip)

The idea is that the files with extension .csv and .tsv can automatically be considered as meta information. Is the column match a jpath it will be joined automatically (like info.abc or meta.cde as column name).

**Comment by lpatiny** [comment]
This is a smaller dataset that could be used to test

[BariatricRats.zip](https://github.com/cheminfo/nmrium/files/10757633/BariatricRats.zip)

**Comment by hamed-musallam** [comment]
@lpatiny  

can you use this file for testing, i changed the column jpath and its values

[BariatricRats (3).zip](https://github.com/cheminfo/nmrium/files/10784038/BariatricRats.3.zip)
