### ISSUE TITLE
ExpNo

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2130]
In bruker file we have the property 'experimental number' however it is not kept in the `info` object.

This is annoying because we need sometimes to attach meta information based on this experimental number.

Which information should we add in 'info' so that it is not specific to Bruker directory structure ?

**Comment by lpatiny** [comment]
Yes we can simply put '0' in this case for expno

**Comment by lpatiny** [comment]
Here the problem is different. In the normalisation of the `info` in nmr-load-save we are loosing the information about the experimental number. And this is what we need to keep.

**Comment by jobo322** [comment]
there is a PR on brukerconverter that will allow this loading

- https://github.com/cheminfo/nmrium/issues/2130

**Comment by lpatiny** [comment]
@jobo322 What is the status of this issue ?

**Comment by jobo322** [comment]
it was done by b88f7fdad1e348964ba98ed41aecbae5fc28dbd7
