### ISSUE TITLE
onDataChange call-back not returning the source object

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#2133]
@lpatiny @jobo322 

I think the onDataChange should return all the objects which could be any kind of object except the `function` like those in the file object `text`, `arrayBuffer` ...etc.

who uses the component can decide what to keep and what not, or we could have an option on the component to specify if we need to include data or source, or both.

![image](https://user-images.githubusercontent.com/35760236/217509897-ea5e8c0a-a6e6-419a-9834-a47c8646822a.png)
![image](https://user-images.githubusercontent.com/35760236/217510549-63f6fcb4-ddda-4d02-8da9-7d315b2fb330.png)

**Comment by lpatiny** [comment]
@hamed-musallam Is this still an issue ? Otherwise you could close it.

The source has been simplified.

![image](https://user-images.githubusercontent.com/1484241/220771372-caa414c0-8b16-4e7c-a118-c8bb3eb86b5c.png)

**Comment by lpatiny** [comment]
This was fixed.
