### ISSUE TITLE
Use typescript types from nmr-load-save

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2134]
@hamed-musallam could you check what it missing so that NMRium state extends the one coming from nmr-load-save ?

**Comment by hamed-musallam** [comment]
@lpatiny 

We need to refactor the main reducer actions to use types like what we did in the preferences reducer https://github.com/cheminfo/nmrium/blob/95b9227b471d89281804067213ecc06f928fd2a7/src/component/reducer/preferences/preferencesReducer.ts#L45-L122
