### ISSUE TITLE
broad singulet should has a delta instead of from-to

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#2140]
in the range table a range of a `br s` signal has from-to instead of a delta.

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/12143935/218676736-9ad96dac-6c89-46a4-9acf-0481c570ef6a.png">

seems the [`checkMultiplicity`](https://github.com/cheminfo/nmrium/blob/main/src/component/panels/extra/utilities/MultiplicityUtilities.ts#L26-L34) function could be improved to add support for it.

additional to this, we can notice that the `Rel H` is not recalculated with the real integration data. 

![sumIntegrationIssue](https://user-images.githubusercontent.com/12143935/218679242-68695567-fdcd-4960-ba93-d0ddb27130db.gif)

to reproduce it, you should import this ACS string

```
1H NMR (CDCl3, 400 MHz) d: 5.55 (d, J = 8.1 Hz, 1H, H-10 ), 4.72 (br s, 1H),
	4.29 (m, 1H, H-50 ), 3.53 (m, 2H, H-30 , H-40 ), 3.42  
	(m, 1H, H-20 ), 3.15 (dd, J = 6.0 Hz, J = 10.0 Hz, 1H, H-3), 3.00 (td, J = 11.0 Hz,  
	J = 4.5 Hz, 1H, H-19), 1.69 (s, 1H, H-30)
```

**Comment by hamed-musallam** [comment]
@jobo322 

the `br` comes from the publication string `4.72 (br s, 1H)`

**Comment by jobo322** [comment]
Add br to the list of possible multiplicities could help to fix the problem I think.
