### ISSUE TITLE
Old nmrium files stay as fid, new ones work

### ISSUE THREAD

**Issue by cp2ru2** [cheminfo/nmrium#2146]
Hi,
I cannot open old (created September 2022) nmrium files. It stays as an fid. Clicking on the ft button does not do the ft. But a newly saved nmrium file works, meaning
[nmr files.zip](https://github.com/cheminfo/nmrium/files/10747154/nmr.files.zip)
 it reads and shows as the correct spectrum.

**Comment by jobo322** [comment]
Hello @cp2ru2 i found the problem, let me fix it

**Comment by lpatiny** [comment]
@jobo322 please don't forget to first add a failing testcase with this file (can be in nmr-load-save if it is there the problem)
