### ISSUE TITLE
How to get feedback after drag / drop of files

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2147]
nmr-load-save should keep track of events and give back this information to NMRium in order to display a message to the enduser

@jobo322 can you check your current PR: https://github.com/cheminfo/nmr-load-save/pull/39 and add testcases

Currently if we drag / drop this jcamp we have no idea what is going on. Actually it is an infrared that is in this jcamp but still the enduser should be aware of it.

[1.jdx.zip](https://github.com/cheminfo/nmrium/files/10753535/1.jdx.zip)

**Comment by jobo322** [comment]
seems this ticket is duplicated with 
- https://github.com/cheminfo/nmr-load-save/issues/157
