### ISSUE TITLE
Pressing enter after opening general preferences

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2156]
If we press enter we will open and open again the general preferences.

![2023-02-16 09 58 40](https://user-images.githubusercontent.com/1484241/219317158-94ef3c83-3ae2-4639-9646-8c0ca718a491.gif)

**Comment by lpatiny** [comment]
This bug will be solve by using Modal from https://github.com/zakodium-oss/react-science/blob/main/src/components/modal/Modal.tsx (and useDialog for the state)

**Comment by wadjih-bencheikh18** [comment]
> This bug will be solve by using Modal from https://github.com/zakodium-oss/react-science/blob/main/src/components/modal/Modal.tsx (and useDialog for the state)

Do you want me to use `react-science` modal in `GeneralSettings` to fix the bug?

Also am not sure what does @hamed-musallam did in the branch https://github.com/cheminfo/nmrium/tree/2156-pressing-enter-after-opening-general-preferences, do you want me to create a new branch or work on it.

**Comment by lpatiny** [comment]
@hamed-musallam Please tell @wadjih-bencheikh18 if he may try to migrate the general settings dialog box to 'modal' like he did for about.

**Comment by hamed-musallam** [comment]
@wadjih-bencheikh18 

You can go ahead and migrate the general settings dialog box to 'modal' as you did for about.

**Comment by wadjih-bencheikh18** [comment]
> You can go ahead and migrate the general settings dialog box to 'modal' as you did for about.

Thank you
