### ISSUE TITLE
Import Bruker files from nmrShiftDB

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#2159]
@jobo322  

We try to import these Bruker Files which are a sub-set of NMR shift DB but NMRium can not import them

[Jena Team - spectra -not -import.zip](https://github.com/cheminfo/nmrium/files/10755762/Jena.Team.-.spectra.-not.-import.zip)

**Comment by lpatiny** [comment]
The file structure is not correct and it seems the files have been moved manually

![image](https://user-images.githubusercontent.com/1484241/219382211-4fd20605-ccf3-4900-b125-6daa2a546b08.png)

All the files are expected to be in the numbered folder.
Same is true here:

![image](https://user-images.githubusercontent.com/1484241/219382139-0d4d7716-bd79-443e-8bdf-8a8432183acc.png)

this should however be fixed partially in the new release of bruker-converter.

https://github.com/cheminfo/brukerconverter/commit/90b6695f6d184fb8fe0e3e07ff03bba8ceee0ece

**Comment by NRayya** [comment]
Hi @lpatiny 
I would like to confirm that the files were changed manually to fit the submission of nmrXiv. Thanks for taking care of this
