### ISSUE TITLE
multiplet-analysis can lead to strange results

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2163]
multiplet-analysis gives nearly always a result even if it is clearly not a multiplet

This can lead to some confusion for the end user.

Do we have a possibility to get a confidence factor and return a 'm' (massif with from / to and not a multiplet) ?

![2023-02-17 20 47 21](https://user-images.githubusercontent.com/1484241/219776520-ce4a9f2b-8d64-42d1-aa5c-308d24d138b5.gif)

**Comment by jobo322** [comment]
![Image](https://github.com/cheminfo/nmrium/assets/12143935/13d74e39-7048-4702-8bc0-cf4672968e7a)
