### ISSUE TITLE
bug in delta zone edition

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#2178]
At the moment, nmrium throws if we try to modify the delta of a zone. it is fixed by modify this [function](https://github.com/cheminfo/nmrium/blob/main/src/component/reducer/actions/ZonesActions.ts#L90-L116) passing `value` instead of `options` 

but, after the edition, the peaks, the mark of the delta, and the contours are misaligned.

![Monosnap screencast 2023-02-22 06-39-26](https://user-images.githubusercontent.com/12143935/220612632-17a90b03-47e3-406b-965c-984d269d9680.gif)

**Comment by hamed-musallam** [comment]
@jobo322 

we just take care of the signal and not the peaks
![image](https://user-images.githubusercontent.com/35760236/220631840-ccb7fb74-a0ec-45eb-aaa4-2be45943a4ca.png)

if we need to do the same for the peaks, what is going to happen for min and max on X and Y
```ts
orignalX,
originalY,
originalMaxX,
orignalMaxY,
orignalMinX,
orignalMinX

```
I think we need to look for a cleaner solution, for now, we can fix the filter value and then we can look at this issue again.
