### ISSUE TITLE
Allow to copy as molfileV2 or molfileV3

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2188]
Add the options to copy as molfile V2 or molfile V3

![image](https://user-images.githubusercontent.com/1484241/220772725-36a87560-4312-4535-ab3b-6851b02ca1cf.png)

Currently it is V3 that is implemented.

To get V2 you need to call `toMolfile`

https://cheminfo.github.io/openchemlib-js/classes/Molecule.html#toMolfile

**Comment by hamed-musallam** [comment]
@lpatiny 

To implement this, we need to create `moleculeV2` at the molecule object, is this Ok for you
https://github.com/cheminfo/nmrium/blob/b88f7fdad1e348964ba98ed41aecbae5fc28dbd7/src/data/molecules/MoleculeManager.ts#L15-L17

**Comment by hamed-musallam** [comment]
@lpatiny 

We can you this function `OCLMolecule.fromMolfile` to create molefile v2 from molfile v3 string
