### ISSUE TITLE
Simplification of code ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2196]
What is the difference

https://github.com/cheminfo/nmrium/blob/5c0556dd98ba73301b76729825c47d20350c3f2e/src/component/elements/ReactTable/ReactTable.tsx#L501

and simply `{...props}` ?

**Comment by hamed-musallam** [comment]
@lpatiny 
it is a mistake, it should be `{...props}` it seems i was passing other properties and i remove them without modifying the destruction
