### ISSUE TITLE
Possibility to specify width / height of the component in General Preferences

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2209]
By default the width / height should be 100%, 100%

Would be nice however to be able to specify other values in a specific workspace (for example for the documentation).

**Comment by lpatiny** [comment]
This could be done based on the URL on the dev site using something like:  https://dev.nmrium.org/?width=1000&height=800#/SamplesDashboard/d8wi6v1iefr/ViewdatacytisinedatacytisineBig13Cjson

**Comment by hamed-musallam** [comment]
@lpatiny 

the width and height value is in percent `%` unless you suffix the value with `px`
