### ISSUE TITLE
Why Source is defined ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2222]
https://github.com/cheminfo/nmrium/blob/049878f4bfc08e1ae04b5ec98c09d813c38b1351/src/component/NMRium.tsx#L135-L141

You can directly use WebSource from filelist-utils

https://github.com/cheminfo/filelist-utils/blob/890f21555b9d0618982178867f178772ea23ca6d/src/WebSourceFile.ts#L1-L12

**Comment by hamed-musallam** [comment]
@lpatiny 

What do you mean by why it is defined? , We get the `Source` interface from nmr-load-save
