### ISSUE TITLE
Props allowing to load data in the components ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2223]
Currently in order to load data in NMRium when instantiating the component we should use the `data` property.

`data` has the following type

```js
export interface NMRiumData {
  source?: Source; // in reality WebSource
  molecules?: Molecules;
  spectra: DeepPartial<Spectra>;
  correlations?: CorrelationData;
}
```

I would still need the possibility to have as data a 'normal' fileCollection. In some cases I have the JCAMP-DX in the page and need to send it as a raw file to NMRium and I think currently there is no simple way.

@hamed-musallam Could you add a new property 'fileCollection' in the <NMRium> and test it for example with a page in which we have an 'external' (outside NMRium) drag / drop component that will create the fileCollection and create the NMRium component with it ?

**Comment by targos** [comment]
I'm not sure about this feature. Maybe the application should just call nmr-load-save to convert the file collection to the expected structure?
