### ISSUE TITLE
Spectra rendering options

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2234]
Are we certain that those options have any influence ?

I did many tests and it seems that it yields always to the same result.

![image](https://user-images.githubusercontent.com/1484241/224911188-19dabbf9-ee5d-43ee-81be-bd72e0758b86.png)

If this is the case we should remove those options.

**Comment by hamed-musallam** [comment]
Did you test these options' impact on the performance once we have dozens of spectra?

**Comment by lpatiny** [comment]
I tested with over 200 1D spectra and the impact seems to be low (less than 20%).

However we still have an effect on the presence / absence on antialiasing so it make sense to keep it.
