### ISSUE TITLE
Experimental FT for 2D spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2235]
@hamed-musallam 

Could you prepare new buttons for 2D processing:

- Zero filling
- Apodization
- FT

Those 3 buttons will need options (the 3)

For Zero filling we will need 2 zero filling, for first and second dimensions
For apodization we will also need the options for the 2 dimensions
For FT we should be able to select if we want to make FT in both dimensions or not.

All those buttons should be hidden behind the experimental features and this will help @jobo322 to implement the code.

**Comment by hamed-musallam** [comment]
Do you think it is better to wait until we see what options that Alejandro needs for each filter before we add those tools(buttons) in the main toolbar

**Comment by lpatiny** [comment]
Can indeed just be a toolbar with 'apply' 'cancel' 'preview' but currently no options.

![image](https://user-images.githubusercontent.com/1484241/224989951-2fa117ec-9d99-4a70-8586-4585bf12454c.png)

**Comment by hamed-musallam** [comment]
@lpatiny after I checked, maybe we do not need to create a different tool for 2d, we can use the sample 1D tools and based on Nucleus we apply the 1D filter or the 2D filter, WDT?

**Comment by hamed-musallam** [comment]
closed by https://github.com/cheminfo/nmrium/pull/2294
