### ISSUE TITLE
Use child logger when sending the logger to other librairies

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2242]
https://github.com/cheminfo/nmrium/blob/b5c287a02895aba615a873477b459532892e02d3/src/component/loader/DropZone.tsx#L81-L82

For the logger property please try

`logger: logger.getChild({context: 'nmr-load-save'})`

This is related to:
- https://github.com/cheminfo/nmr-load-save/issues/156

By sending a child process it will allow to sort the logs by library that generated it.

**Comment by hamed-musallam** [comment]
> logger: logger.getChild({context: 'nmr-load-save'})

you mean `logger: logger.child({context: 'nmr-load-save'})
`
