### ISSUE TITLE
Apply and Save does not seem to work

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2258]
If I have custom workspace and I make some changes then click on 'apply and save' nothing seems to happen.

![image](https://user-images.githubusercontent.com/1484241/226902347-a021d329-59b5-4a6d-8ba4-980edd010dce.png)

I would expect that the changes are saved and that I quit this dialog box.

**Comment by hamed-musallam** [comment]
@lpatiny 

i can not reproduce this bug, can you show me how to reproduce it

**Comment by lpatiny** [comment]
I can not reproduce it neither. Strange.
