### ISSUE TITLE
Trying to add line broadening

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2260]
If you drag / drop this file:

[lineshape_raw.jdf.zip](https://github.com/cheminfo/nmrium/files/11047902/lineshape_raw.jdf.zip)

Then in processing select the level of Zero Filling and try to add apodization, the apodization is done after FT rather than at the level of FID and yields to weird results (and preview).

![2023-03-23 08 24 36](https://user-images.githubusercontent.com/1484241/227132629-b96a2198-7436-4295-a8b4-a98c28c4600c.gif)

This is a bug but I don't know how to solve it. If we are sure there should be only one time the different filter and they should be applied always in the same order we can display the spectrum just before the 'future' new filter. In this case it would be directly at the level of the FID.

This is also related to:
- https://github.com/cheminfo/nmrium/issues/2238

**Comment by jobo322** [comment]
Seems it is working now.

**Comment by jobo322** [comment]
@hamed-musallam  did you make any change for it?. Only thing I catch is that is needed a double click over `apply` to close the apodization tool

**Comment by jobo322** [comment]
https://github.com/cheminfo/nmrium/assets/12143935/e4285972-43ff-4ad1-b63b-868d82b50b1c

**Comment by hamed-musallam** [comment]
@jobo322 

Could you check this issue and see if there is still a purpose to keep it opened
