### ISSUE TITLE
2D zones picking - coordinates are listed as 0 when they are not

### ISSUE THREAD

**Issue by NRayya** [cheminfo/nmrium#2276]
For some zones, I am getting the coordinates as 0 even that they are not with manual picking. Those zones are not picked in the auto picking. For instance, in the attached dataset, I got the following when trying the pick the zone in the bottom right (3 were picked)
![image](https://user-images.githubusercontent.com/82588017/228227270-1d6bb668-149a-4e89-a940-93f0e2b4470d.png)
[5.zip](https://github.com/cheminfo/nmrium/files/11088924/5.zip)

**Comment by jobo322** [comment]
yes, it seems to be working well in the current version and 0.33.0 too.

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/12143935/233142168-e6c248b1-2bdf-43dd-9370-ec12a60d4f99.png">
