### ISSUE TITLE
Drag drop molfile expands hydrogens

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2280]
When you drag and drop a molfile that do not contain hydrogens :

[cytisine.mol.zip](https://github.com/cheminfo/nmrium/files/11108672/cytisine.mol.zip)

The hydrogens are expanded by default and this should not be the case.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/1484241/228753829-e6b3e279-4723-400d-8f81-b498c5c4538c.png">

**Comment by jobo322** [comment]
the hydrogens appears expanded because we add the implicit hydrogens at the moment to load the molecule.

**Comment by lpatiny** [comment]
Why do we need to add them ?

**Comment by lpatiny** [comment]
In fact it is obviously me that asked for it:
- https://github.com/cheminfo/nmr-load-save/issues/120

But I don't know why or if it has any advantage. For prediction it would make sense because we should not have reordering of the proton but I don't think we should rely on it.

**Comment by jobo322** [comment]
it is done from 0.16.0 version of [nmr-load-save](https://github.com/cheminfo/nmr-load-save/releases)
