### ISSUE TITLE
Delay in phase correction

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#2286]
https://github.com/cheminfo/nmrium/blob/253589e53fa78d7e0eada3e6c0c5fccb771152ba/test-e2e/NmriumPage.ts#L98

It should not be necessary to wait before submitting the values. I understand that there is debouncing for the preview, but it shouldn't affect the submission of the values.

**Comment by hamed-musallam** [comment]
based on the current implementation and because we are debouncing (onChange call back will not be triggered immediately), I think it is not possible to remove the current waiting in the test.

we can change this behaviour by removing the debouncing if the live preview is disabled

**Comment by lpatiny** [comment]
But I think it make sense that when we validate we take anyway the current value and not the debounced value.

**Comment by hamed-musallam** [comment]
but in this case, the result will be wrong for the phase correction because by default the values for ph0 and ph1 are 0,0
