### ISSUE TITLE
Crash when trying to do zero filling

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#2289]
To reproduce:

- Go to https://dev.nmrium.org/#/SamplesDashboard/9csmjvkm1fb/Viewdatacytisinedatacytisine13CFIDjson
- Click "Fourier transform" tool
- Open "Processings" panel
- Click "Digital Filter" in the panel
- Click "Zero Filling" tool

<img width="733" alt="CleanShot 2023-04-08 at 10 45 22@2x" src="https://user-images.githubusercontent.com/2352663/230712534-85e75c87-47a3-4b98-b4a4-162278b63800.png">

**Comment by hamed-musallam** [comment]
This should be fixed in https://github.com/cheminfo/nmrium/pull/2278
