### ISSUE TITLE
first order phase correction differ from topspin

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#2298]
When we apply a first order (PHC1) phase correction, the values of the zero order (PHC0) phase correction change depending of the pivot selected, in the case of nmrium ensure an ascending order in the `x` axis but topspin use a descending order, so the results for phase correction differs

**Comment by jobo322** [comment]
@lpatiny some methods in mljs expect data in ascending order. The behavior of phase correction with respect to phase correction is a data in descending order,

I propose to refactor reimPhaseCorrection to start the phasing from the `length - 1` instead of 0. With this small refactor the values of phase correction after a manual correction are the same as topspin phase correction parameters and the parameter can be used bidirectionally

**Comment by lpatiny** [comment]
But this will still be specific to Topspin. What about other software ? Do they have the same rule to have the data in descending orders ?

**Comment by jobo322** [comment]
from the James Keeler book
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/12143935/232541571-412be413-23ba-4429-b7a6-92f5bac7f4e0.png">

so it is like that

<img width="526" alt="image" src="https://user-images.githubusercontent.com/12143935/232541753-930a62f4-7808-4e59-b58d-6c1ebf06e990.png">

nmrium is inverted with respect with it.

but, I test the behavior of manual phase correction in `chenomx`, `topspin` and `mestrenova` there is not a equal result

ph0 = 90; (mestrenova) === (chenomx) === -(topspin) === -(nmrium)

ph1 = 90; pivot = 0 ppm

mnova ph0 = -72.04
chenomx ph0 = -17.96
nmrium ph0 = -17.96
topspin ph0 = -72.04
