### ISSUE TITLE
Problem with missing  loggingLevel

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2299]
It seems that if you have some local workspace you may have this problem migrating to the last version

<img width="736" alt="image" src="https://user-images.githubusercontent.com/1484241/232158234-a0893ee9-795c-4963-8599-89a36978b65c.png">

**Comment by hamed-musallam** [comment]
@lpatiny 

We forgot to increase the version number of the local storage and by that, we automatically erase the local storage once NMRium loaded

**Comment by hamed-musallam** [comment]
- #2302

**Comment by hamed-musallam** [comment]
closed by #2323
