### ISSUE TITLE
Checmical structures panel - Structures serialisation number not incremented after drawn strucutres

### ISSUE THREAD

**Issue by NRayya** [cheminfo/nmrium#2303]
When adding several structures, some by drawing, the ones added after the drawn structures get the label "P1", even if the label is already used.

https://user-images.githubusercontent.com/82588017/232798358-dae2e188-2ea2-4b2c-9e3f-fc1d36f8fdef.mov

**Comment by NRayya** [comment]
I would like to add that the label should be checked for uniqueness here too. Thanks

**Comment by lpatiny** [comment]
I think nmr-load-save should never add the label because it is not aware of the state indeed. @hamed-musallam for me you can change nmr-load-save and ensure unicity and addition of the label at the level of nmrium.
