### ISSUE TITLE
export and reimport 1D fid

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2306]
https://export-spectrum-as-jcamp.nmrium.pages.dev/#/SamplesDashboard/7laqv57uuwg/Viewdatacytisinedatacytisine13CFIDjson

If we export the 13C fid and reimport we have some issues with the baseline

<img width="558" alt="image" src="https://user-images.githubusercontent.com/1484241/233137772-d3dbb390-0958-415f-b697-4d6b0ba35a29.png">

While the digital filter is still applied

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/1484241/233138087-d44b0272-1114-4f2b-94bc-6130798c4802.png">

@jobo322 could you check what is the issue ?

**Comment by jobo322** [comment]
the problem is the `digital filtering` applied is exported in the FID, so at the moment to re-import the FID we move more points that the needed.

I propose to change the digital filter parameter if the digital filter is applied. so the result would be ok with respect to mestrenova and nmrium.
