### ISSUE TITLE
Can open preferences only once

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2309]
When you open the preferences and then press 'ESC' you can not open the preferences any more.

![2023-04-20 20 21 53](https://user-images.githubusercontent.com/1484241/233454241-6b98ca68-d72f-439e-9930-2ae171eaeebb.gif)

**Comment by targos** [comment]
Fixed in the latest version of react-science.

**Comment by targos** [comment]
Fixed by https://github.com/cheminfo/nmrium/commit/fde906ee3233b736b24e9c7eb6b52af13b1e1c19
