### ISSUE TITLE
Crash with full cytisine and Assignment summary

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2310]
If you activate the assignment summary

![image](https://user-images.githubusercontent.com/1484241/233455075-0a38a089-8c4c-42a3-ba2f-ecd3e9c260b2.png)

And load the full cytisine

Then automatic range picking in 1H and then in 13C there is a crash

![2023-04-20 20 26 59](https://user-images.githubusercontent.com/1484241/233455523-5ab14189-06b6-4d04-8c29-702641cf1eff.gif)

**Comment by hamed-musallam** [comment]
close #2331
