### ISSUE TITLE
Databases panel not working

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#2330]
![CleanShot 2023-05-02 at 10 04 02](https://user-images.githubusercontent.com/2352663/235612524-6f7dd5d9-9e32-40d7-b4b3-96b569c3b918.png)

**Comment by hamed-musallam** [comment]
This is the normal behaviour if no spectra there

**Comment by targos** [comment]
Well, something needs to be done because the lack of feedback (totally empty panel) made me think there was a bug.

**Comment by targos** [comment]
Thank you @hamed-musallam.
