### ISSUE TITLE
New demo with external nmr-load-save

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2335]
Currently when the data are loaded from a source the files are loaded twice.

It would be nice to have a demo in the project in order to solve this problem.

In Worspaces

![image](https://user-images.githubusercontent.com/1484241/236162963-a10a1274-c7ea-4599-bf6f-ae4c084a2b5b.png)

Please add a new menu 'NMR Load Save' that would load from outside the component and set the property with the result.

**Comment by hamed-musallam** [comment]
closed by #2337
