### ISSUE TITLE
Malformed Mac OS X resource fork artifacts prevent NMRium import

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmrium#2391]
ZIP archives created on Mac OS X seem to cause problems with ZIP import because of resource fork artifacts.

Steps to reproduce:
 - Download attached ZIP [cyclosporin.zip](https://github.com/cheminfo/nmrium/files/11653413/cyclosporin.zip) and upload to NMRium. Error message: `Error: Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html`

Workaround:
 - Remove `./__MACOSX/cyclosporin/._cyclosporin_cosy.zip` from the archive and re-upload -> works.

Suggestion:
 - Have paths like `/__MACOSX/` (and possibly `/.*/`) ignored.

@evaziegler

**Comment by targos** [comment]
This is fixed in the latest version.
