### ISSUE TITLE
Resetting projections scaling and zoom  

### ISSUE THREAD

**Issue by tomlebl** [cheminfo/nmrium#2395]
I have got couple of enhancement suggestions. 

Would it be possible to keep projection scaling when you zoom out from 2D spectrum? Current behavior makes inspecting spectra with large peak in 1H projection (for example solvent) rather tedious. Example data is attached.    
[Problem4.zip](https://github.com/cheminfo/nmrium/files/11677498/Problem4.zip)

Having an option to keep zoom upon changing between spectra tabs could also improve users experience.

**Comment by lpatiny** [comment]
You can zoom out the 2D by 'double click' and it would keep the vertical scale of projections.

You can also 'save' the current status. The first time you press a number (1->9) it save the current zoom information, the second time it recalls the zoom information. Very practical to switch from one part of a spectrum to another.

**Comment by tomlebl** [comment]
Fantastic. That's absolutely brilliant! 
Thanks
