### ISSUE TITLE
Should we add property 'state'

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2410]
Currently we can not send the version to the data prop and this leads to issue.

We could allow the property `state` that would allow a partial state (version could be mandatory ?)

- data
- view
- settings
- version

@targos WDYT ?

**Comment by targos** [comment]
In principle I'm ok with that, but we need to discuss various cases to handle when the state prop is changed by the parent.

**Comment by lpatiny** [comment]
Duplicate of https://github.com/cheminfo/nmrium/issues/2274
