### ISSUE TITLE
Automatic zone detection crashes on 2D raw data

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmrium#2411]
If applied to 2D raw data, automatic zone detection crashes.

Methods to reproduce:
a)
 - Open NMRium Demo
 - Select Full cytisine
 - Click `Automatic Ranges/Zones picking for all spectra` in spectra panel
 - NMRium crashes

b)
 - Open NMRium Demo
 - Select Full cytisine
 - Select COSY spectrum from 1H,1H tab
 - Click `Zone tool`
 - Select COSY raw data
 - Click `Auto Zones Picking`
 - NMRium crashes

Workaround:
- Delete all 2D raw data

Suggestion:
- Catch zones picking if spectrum is raw data

@evaziegler

**Comment by jliermann** [comment]
On dev, I can still reproduce the bug when including 2D raw data?

**Comment by lpatiny** [comment]
Actually it crash when there is a 2D FID. @hamed-musallam could you check that no zone picking is done on the raw data.

We have a test case here:

https://dev.nmrium.org/#/SamplesDashboard/m9p3oa8cnxg/Viewcytisine2ddatacytisine2dHMBC_HN_Cytisinjson


![2023-06-15 17 25 27](https://github.com/cheminfo/nmrium/assets/1484241/0aa801e7-7389-4e09-9df0-869517a068e1)

**Comment by hamed-musallam** [comment]
fixed in https://github.com/cheminfo/nmrium/pull/2472
