### ISSUE TITLE
unhandled error in database action

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#2430]
```
Cannot read properties of null (reading 'ranges')

{
  source: 'webpack://_N_E/node_modules/nmrium/lib/component/reducer/Reducer.js',
  line: 402,
  column: 67,
  name: 'draft'
}
{
  source: 'webpack://_N_E/node_modules/nmrium/lib/component/reducer/actions/DatabaseActions.js',
  line: 9,
  column: 18,
  name: 'ranges'
}
```

**Comment by hamed-musallam** [comment]
@jobo322 

Resurrect spectrum from ranges failed,  `rangesToXY` give me this error only in the negatives values
![image](https://github.com/cheminfo/nmrium/assets/35760236/fcb8e5fb-cd05-4384-96a3-2a643a6ddb96)

**Comment by jobo322** [comment]
> @jobo322
> 
> Resurrect spectrum from ranges failed, `rangesToXY` give me this error only in the negatives values ![image](https://user-images.githubusercontent.com/35760236/248252851-fcb8e5fb-cd05-4384-96a3-2a643a6ddb96.png)

yes, it is a problem in the simulation of the spectrum, I am working on it

**Comment by jobo322** [comment]
> Cannot read properties of null (reading 'ranges')
> 
> {
>   source: 'webpack://_N_E/node_modules/nmrium/lib/component/reducer/Reducer.js',
>   line: 402,
>   column: 67,
>   name: 'draft'
> }
> {
>   source: 'webpack://_N_E/node_modules/nmrium/lib/component/reducer/actions/DatabaseActions.js',
>   line: 9,
>   column: 18,
>   name: 'ranges'
> }

seems it fixed, currently if there is not ranges in the element database it is excluded from the list presented to the user.
