### ISSUE TITLE
unhandled error in ZonesActions

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#2466]
```
Cannot read properties of undefined (reading 'maxX') / l is undefined

{
  source: 'webpack://_N_E/node_modules/nmrium/lib/component/reducer/Reducer.js',
  line: 348,
  column: 63,
  name: 'draft'
}
{
  source: 'webpack://_N_E/node_modules/nmrium/lib/component/reducer/actions/ZonesActions.js',
  line: 64,
  column: 38,
  name: null
}
{
  source: 'webpack://_N_E/node_modules/nmrium/lib/data/data2d/Spectrum2D/zones/detectZones.js',
  line: 4,
  column: 35,
  name: 'datum'
}
{
  source: 'webpack://_N_E/node_modules/nmrium/lib/data/data2d/Spectrum2D/zones/getDetectionZones.js',
  line: 18,
  column: 0,
  name: 'spectrum'
}
{
  source: 'webpack://_N_E/node_modules/nmrium/lib/data/data2d/Spectrum2D/zones/getDetectionZones.js',
  line: 47,
  column: 0,
  name: 'data'
}
```

**Comment by hamed-musallam** [comment]
this bug happen because the user visualize 2d FT spectra and then select the zone detection tool then switch to 2d Fid so the zone detection options panel still opened and he try to make zone detection which should not work.

in this case, what do we have to do?

hide the panel if the selected 2d spectrum is not FT or check before making the zone detection and display a message if it is not FT

**Comment by lpatiny** [comment]
If it is easy to implement, I think when changing the spectrum we could systematically reset the tool to zoom (this means changing the spectrum for the same nucleus or changing the nucleus).

**Comment by targos** [comment]
I'm able to reproduce without using the zone detection tool.

Just go to https://dev.nmrium.org/#/SamplesDashboard/d3ubedj4/Viewcytisine2ddatacytisine2dHMBC_HN_Cytisinjson and click this button in the spectra list:
![CleanShot 2023-06-26 at 14 57 41](https://github.com/cheminfo/nmrium/assets/2352663/31e9c143-08aa-4e6a-bd2c-f4cf2bd02eb8)

**Comment by targos** [comment]
I think this was actually a duplicate of https://github.com/cheminfo/nmrium/issues/2411 ?
