### ISSUE TITLE
unhandled error in integrals actions

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#2470]
```
Cannot set properties of undefined (setting 'values')

{
  source: 'webpack://_N_E/node_modules/nmrium/lib/component/reducer/Reducer.js',
  line: 153,
  column: 56,
  name: 'draft'
}
{
  source: 'webpack://_N_E/node_modules/nmrium/lib/component/reducer/actions/IntegralsActions.js',
  line: 55,
  column: 0,
  name: null
}
```

**Comment by hamed-musallam** [comment]
i do not have any idea how to reproduce it

**Comment by targos** [comment]
- Open a 2D spectrum, for example https://dev.nmrium.org/#/SamplesDashboard/5ykrx8lvj9x/Viewcytisine2ddatacytisine2dcosyjson
- Click "Delete All Integrals" in the Integrals panel 
![CleanShot 2023-06-26 at 15 10 37](https://github.com/cheminfo/nmrium/assets/2352663/bc5f5bd0-569b-4fa3-a0f7-6026845609a5)
- Confirm
