### ISSUE TITLE
Frequency missing in simulated spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2526]
We can not make a auto range picking on the simulated spectra.

Very likely due to the fact that there is no frequency in the simulated spectrum

As name you could also set 'AB', 'ABC', ... so that in the list of spectra we know what it is.
As nucleus: 1H

<img width="1200" alt="image" src="https://github.com/cheminfo/nmrium/assets/1484241/ccb4f18a-d091-47ff-925d-ee1d2d3f2aaf">

**Comment by jobo322** [comment]
wrongly I push a partial fix to the main, c0c060df3d4ae25fd37745e44bbbef23214a4a19
