### ISSUE TITLE
Add simulation test workspace

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2527]
Like for prediction and a new option 'simulation'

<img width="368" alt="image" src="https://github.com/cheminfo/nmrium/assets/1484241/7739666e-d73d-4891-8e50-50ba2df50ecd">

The simulation will show:

- Spectra Panel
- Simulation Panel

The spectra panel should display:
- info.name
- the nucleus
- the frequency

**Comment by hamed-musallam** [comment]
you specify the panels, What about the tools ?, you asked in another issue to add the frequency to the simulated spectrum information because of the range picking tool?
