### ISSUE TITLE
Drag drop molfile and expanded hydrogens

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2537]
When I drag / drop a molfile the hydrogens are always expanded.

[structure.mol.zip](https://github.com/cheminfo/nmrium/files/12130114/structure.mol.zip)

This should not be the case because it looks quite complex:

<img width="568" alt="image" src="https://github.com/cheminfo/nmrium/assets/1484241/4d89b828-3eb8-4e54-8eb0-b4c1514ac826">

@jobo322 Why did we do this ? I don't remember.

**Comment by jobo322** [comment]
it is duplicated, 

- https://github.com/cheminfo/nmrium/issues/2280
