### ISSUE TITLE
Still issues with database

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2561]
We can reach some state in which the filtering is not working.

In this video when I remove the range filtering other results than when I don't have it and this can never be the case.

It was done on dev.nmrium.org

![2023-08-01 09 36 12](https://github.com/cheminfo/nmrium/assets/1484241/407f3e78-e075-4da0-a17e-dfc59ac42f59)

Here is the query that was used:

<img width="217" alt="image" src="https://github.com/cheminfo/nmrium/assets/1484241/e22b15b9-e1b6-4d24-ae87-fc1f02c6de90">

And I had to add / remove range filtetering.

**Comment by hamed-musallam** [comment]
It appears that the issue has been resolved in another commit, so I will close it for now.
