### ISSUE TITLE
Multiple spectra analysis error when range doesn't cover all spectra

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#2566]
Reproduction:
- https://dev.nmrium.org/#/SamplesDashboard/zmzru8vcz7/ViewdatacoffeedatacoffeeCoffeejson
- MSA
- Spectra calibration
- From: -4, To: -3
- Done

![CleanShot 2023-08-03 at 17 44 46](https://github.com/cheminfo/nmrium/assets/2352663/7fc69da9-5691-458e-82d2-55b0f55f88c1)

**Comment by lpatiny** [comment]
Ideally we should know that this problem will happen before validating the dialog box and give a message (preventing validation of the dialog box).

The following checks should be done:
- if from > to we switch the 2 values without asking the user
- if for any spectrum from < minX or to > maxX we provide an error message in the dialog without closing it: 'Some spectra do not have data in the selected range'
- if the number of points of any of the spectra between from and to is less than 10 we provide an error message 'The selected range is too small to provide accurate results'

For the last point practically you need to check for any of the spectra if
`Math.abs(xFindClosestIndex(x, from) - xFindClosestIndex(x, to)) < 10` and in this case we have the error
