### ISSUE TITLE
Cut integrals

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2569]
In some cases it is easier to make the integration of the full area and then cut the integral so that the end of one integral equals the beginning of the next one.

This could be achieved by shift + click. If there is an integral on this vertical line we would create 2 integrals.

In case there would cut 2 integrals we can just take the first one. This case should not happen.

**Comment by hamed-musallam** [comment]
@lpatiny 

Does this enhancement apply to ranges and integrals? Is there a minimum range limitation for cutting, or is there no restriction?

**Comment by lpatiny** [comment]
Yes to ranges as well but it is another issue. We need to think what to do after cutting ranges.
- https://github.com/cheminfo/nmrium/issues/2581
