### ISSUE TITLE
Smart multiplet analysis

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2571]
when doing manual range picking the number of points may be to big and this prevents the smart multiplet analysis.

![2023-08-03 22 35 15](https://github.com/cheminfo/nmrium/assets/1484241/e40b1c42-a310-4d72-b7f5-cce5da9699a9)

Could we in this case just have a fallback to the non smart multiplet analysis like we do when we analyse globally the spectrum ?

@jobo322 I think you could help Hamed to implement this fix or tell me if there are some issues.

**Comment by jobo322** [comment]
I think the limitation in the number of points is due the optimization of shape parameters.

**Comment by hamed-musallam** [comment]
@jobo322 

what is the status of this issue, can you check this with Luc ?

**Comment by lpatiny** [comment]
When we have too many points we can not apply https://github.com/cheminfo/multiplet-analysis but we can still use the normal method. This is not related to optimization of shape parameters I think.

**Comment by jobo322** [comment]
There is a PR migrating from multiplet-analysis to normal range picking. so it could be closed at the moment to merge this PR
