### ISSUE TITLE
Baseline correction is buggy

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2573]
Toggle preview during baseline correction is not working 

![2023-08-04 13 50 59](https://github.com/cheminfo/nmrium/assets/1484241/ec6e8d05-0b72-4846-aaaa-92ef83fbc471)

Mouse over a selected range and 'backspace' should remove this zone

**Comment by hamed-musallam** [comment]
turn off the live preview is not resetting the spectrum to before change the options
