### ISSUE TITLE
Cut ranges

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2581]
This issue is related to:
- https://github.com/cheminfo/nmrium/issues/2569
- https://github.com/cheminfo/nmrium/issues/2571

But should be done in another PR after solving the 2 other issues.

The idea is to be able to cut ranges as well but this will imply to calculate the multiplicity of the 2 new ranges.

**Comment by hamed-musallam** [comment]
@lpatiny 

should we close this issue ?

**Comment by lpatiny** [comment]
Ok didn't know it was already implement. Thanks Hamed.

**Comment by hamed-musallam** [comment]
closed as completed in https://github.com/cheminfo/nmrium/pull/2603
