### ISSUE TITLE
Import of 2D Bruker Data and Processing of FID

### ISSUE THREAD

**Issue by jschneidewind** [cheminfo/nmrium#2582]
# Description and Reproduction

When loading this Bruker file ([AE-105-7-10.zip](https://github.com/cheminfo/nmrium/files/12274767/AE-105-7-10.zip) , containing 1H, 13C-APT, 31P, 1H-13C HSQC and 1H-31P HMBC), the FID is displayed initially for both the 1H-13C HSQC and 1H-31P HMBC (here showing the 1H-31P HMBC):

<img width="1108" alt="Screenshot 2023-08-07 at 11 38 04" src="https://github.com/cheminfo/nmrium/assets/41544471/7c5db5cf-cd81-42d8-9886-680ef8b2fe6c">

When clicking on the spectrum it is converted to the spectral view (again showing the 1H-31P HMBC):

<img width="1115" alt="Screenshot 2023-08-07 at 11 38 23" src="https://github.com/cheminfo/nmrium/assets/41544471/392e7648-7f6c-47e0-be67-4015747d1f4c">

However, the 2D spectrum and the F1 trace (1H) are not displayed correctly (it is not possible to zoom into the 2D region to see any data). The NMRium logs do not show any error messages.

# Additional Information

This was tested in the regular nmrium.org as well as in dev.nmrium.org. I have also tested this with some of our older 2D data (which were measured in a different Bruker Instrument), where the issue did not occur. Loading the file AE-105-7-10.zip with TopSpin displayed the data as expected, although TopSin did show a warning message for the 1H-31P HMBC that the spectrum did not contain an imaginary part ("Spectrum has no imaginary part: MC2[F1]=QF, PH_mod[F1]=mc. Could not phase real spectrum") but the processing was completed. 

Thus, it might be the case that this specific file or format from this NMR instrument is tripping up NMRium, but I was not able to see at which stage the problem occurs.

Thank you very much for your support!

**Comment by lpatiny** [comment]
Thanks for your feedback. Currently NMRium does not process 2D spectra but only 1D spectra. In your dataset for the 1D you have the 'pdata' '1r' '1i' and we will load it

![image](https://github.com/cheminfo/nmrium/assets/1484241/c28a7962-f540-4579-bc8a-7da3d56c33a8)

However for 2D you don't have the processed data (2rr, 2ri, 2ir and 2ii) and therefore we can currently only display the FID

![image](https://github.com/cheminfo/nmrium/assets/1484241/94de2781-2af7-4baf-8767-3eb796203fdf)

**Comment by jschneidewind** [comment]
Thanks a lot for your your reply @lpatiny , this explains it! Is 2D processing something that is planned for NMRium down the line?

**Comment by lpatiny** [comment]
Yes 2D spectra processing is planned (and actually the FT works behind the experimental flag) but it will still take a while to have an intuitive interface to make the full processing.

But for sure we are working on it.
