### ISSUE TITLE
Floating Molecule label options

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#2588]
I think the molecule panel could have his own settings with:
- show / hide label
- labelFontSize
- labelColor

https://github.com/cheminfo/nmrium/blob/649d0afda5ad7b7bfdb7b9eb335cadc1d20b2e25/src/component/1d-2d/components/FloatMoleculeStructures/DraggableStructure.tsx#L134-L136

_Originally posted by @lpatiny in https://github.com/cheminfo/nmrium/issues/2554#issuecomment-1666816590_

**Comment by lpatiny** [comment]
Closed by https://github.com/cheminfo/nmrium/commit/ce9c7b983cce6b76563aafddd0ba152a478e0ef5
