### ISSUE TITLE
Upgrade `openchemlib-utils` to v5

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#2596]
Needs to be done in a bunch of dependencies first:

![CleanShot 2023-08-09 at 08 55 15](https://github.com/cheminfo/nmrium/assets/2352663/6d5e3633-8a4d-4eb1-9c7a-f2839540458a)

**Comment by targos** [comment]
@jobo322 Is it something that you could do? You can see the breaking changes in https://github.com/cheminfo/openchemlib-utils/releases

**Comment by jobo322** [comment]
nmr-processing, nmr-load-save and nmredata are gonna soon use the lastest version of openchemlib-utils

**Comment by hamed-musallam** [comment]
@jobo322 

can you close this issue if you update packages.

**Comment by lpatiny** [comment]
For the openchemlib-utils that are in react-science it is not important. I will take care of them later (after holidays)
