### ISSUE TITLE
integrals does not changes with table values

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#2636]
- the values in the spectrum does not changes. with respect to the values in the table.
- the values of integration for a spectrum from a fid is set to 0.0

you can reproduce in [pull request](https://github.com/cheminfo/nmrium/pull/2635) with the sample test `various format -> FileCollection with bruker folder`
![bug_integrals_fid](https://github.com/cheminfo/nmrium/assets/12143935/57d90231-0eef-4ef5-af11-985fd8965162)

**Comment by hamed-musallam** [comment]
the important question for me why we have the same integrals for the both spectra Fid and FT?  
[aspirinFiles_1 (1).nmrium.zip](https://github.com/cheminfo/nmrium/files/12396515/aspirinFiles_1.1.nmrium.zip)

**Comment by jobo322** [comment]
Do you mean at the level of nmrium state, right? It is a good question because the integration over an FID does not make sense, but having the integration zones is a good idea, so the integrals should be hidden before FFT or only recalculate the integration if `info.isFft` is `true`. @lpatiny WTD?

**Comment by lpatiny** [comment]
I guess there was already some work in the PR because it looks ok to me. EXCEPT that the values under the scale are not changing. 

![2023-08-24 11 48 53](https://github.com/cheminfo/nmrium/assets/1484241/ec3fb2af-2a96-4e75-aaf3-d6397c486ac8)

The fact that the integral table is displayed event if it is a FID is not chocking to me.

**Comment by lpatiny** [comment]
@hamed-musallam The integrals are extracted from the Bruker file 'integrals.txt'. For both FID and FT we extract those integrals. The 'from' and 'to' are for the spectrum after FT and the sumValue can also be extracted from the file. However the relativeValue (relativeH) should be recalculated based on the sumValue.

Also if I click on the sum I get an error:

<img width="742" alt="image" src="https://github.com/cheminfo/nmrium/assets/1484241/d8790a74-6035-426c-9696-3b247c4bcca5">

**Comment by hamed-musallam** [comment]
fixed by [2ad0863](https://github.com/cheminfo/nmrium/pull/2635/commits/2ad08635d3b050c11b5ad32929470da363e65841)
