### ISSUE TITLE
Phase correction and baseline correction do not force integration recalculation

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2637]
When changing the spectrum (add / remove filter) the relative integration and absolute integration should be recalculate.

This is true for ranges and integrals (also for 2D).

**Comment by hamed-musallam** [comment]
this issue is fixed in nmr-processing  https://github.com/cheminfo/nmr-processing/pull/318 and waiting for the PR to be merege and have a new release of mmr-processing
