### ISSUE TITLE
Mouse out highlighted zones

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2638]
Why when we are hover a rectangle that is highlighted and we press the key 'f' (full out) the highlight do not disappear.

![2023-08-19 07 53 43](https://github.com/cheminfo/nmrium/assets/1484241/bb526ca4-9f51-4a62-abbe-5c0d6959e0da)

This looks like an implementation issue.

**Comment by hamed-musallam** [comment]
as i can see, the `onMouseLeave` event will only trigger when the mouse pointer leaves an element and because in our case we refresh x domain the mouse become outside the element's boundaries so the onMouseLeave will not trigger.

one of the solution that i could think is to erase highlighted state once the domain is updated

**Comment by lpatiny** [comment]
@targos Could you advice on this issue ?

**Comment by targos** [comment]
Changing the domain is just one way to trigger this issue. We need to find a more general solution.

**Comment by hamed-musallam** [comment]
as far as I know, the primary way to trigger this issue is by changing the domain (what are the other ways?). In response, we could clear the highlight state when the domain changes.

**Comment by targos** [comment]
> as i can see, the onMouseLeave event will only trigger when the mouse pointer leaves an element and because in our case we refresh x domain the mouse become outside the element's boundaries so the onMouseLeave will not trigger.

I am trying to reproduce it to confirm this hypothesis but so far I'm not able to. `onMouseLeave` is triggered when the shape goes away and the mouse is not moving: https://codesandbox.io/p/sandbox/highlight-9pf9rj

**Comment by hamed-musallam** [comment]
Could you please review this brief video? I attempted to hover the mouse over the element and then pressed 's' to change the position of the elements. As you can observe, the onMouseLeave event did not trigger.

https://github.com/cheminfo/nmrium/assets/35760236/ba0a92dc-382b-484e-a14f-dfd87331f938

**Comment by targos** [comment]
What? Here I'm doing exactly the same: 

![CleanShot 2023-10-24 at 09 43 34](https://github.com/cheminfo/nmrium/assets/2352663/168375fa-1872-4d3f-a4fe-9edfabf0d618)

**Comment by hamed-musallam** [comment]
it seems it depends on the browser, I'm using Safari. take a look

https://github.com/cheminfo/nmrium/assets/35760236/441e662a-ab27-4592-8360-2858b78af451

**Comment by targos** [comment]
I think it shows that we should be able to find a correct solution. The `onMouseLeave` callback is not ignored by design.

**Comment by targos** [comment]
I had a look with Luc. There are several things to note:

- The Safari behavior is a small bug, but not the problem of this issue. If you move the mouse by just 1 pixel, the callback is correctly called.
- The real issue in the `Range` component of NMRium, is that the rectangle on which the mouse entered is removed from the DOM and replaced by another rectangle after the zoom out, so there is no mouse leave event to send (the element is no longer here). You should make sure that this rectangle stays in sync with the group (`<g>`) on which you listen to the events.

**Comment by targos** [comment]
This seems to be related to the implementation of `Resizer`, which forces you to change the key prop. But the key prop should not be changed here.

**Comment by targos** [comment]
https://react.dev/learn/rendering-lists#rules-of-keys

**Comment by hamed-musallam** [comment]
I know the rules of the keys, I was using the key to force rendering the Resizer component for a reason I do not remember now, but it seems it has a side effect, I will check the implementation of the resizer and try to fix it.
