### ISSUE TITLE
Full out domain not correct.

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2639]
After FT and phase correction the full out domain is not correct. We can not see the full spectrum after pressing 'ff' or the icon for full out.

![2023-08-19 22 40 59](https://github.com/cheminfo/nmrium/assets/1484241/a5e95060-c2a6-4c8b-aa8f-ebf09aa1121f)

**Comment by hamed-musallam** [comment]
This raises another concern I hadn't considered: once you zoom in on Fid and then we process the spectrum, we should reset the zoom history.

**Comment by hamed-musallam** [comment]
@lpatiny 

WDT ? should we clear the zoom history when switching between FT and FID.

**Comment by lpatiny** [comment]
Yes sure it does not make sense to keep the history.
