### ISSUE TITLE
Disable / hide buttons (ideally through config) on NMRium

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#2642]
- https://github.com/NFDI4Chem/nmrium-react-wrapper/issues/122

**Comment by lpatiny** [comment]
@CS76 Please open issues related to NMRium component in the NMRium project.

**Comment by lpatiny** [comment]
Need to check how it works in the exercise workspace: https://dev.nmrium.org/#/SamplesDashboard/dlq362dcqef/Exerciseexercisesethylvinyletherexercisesethylvinylether1hjson

Today we have:
- hideGeneralSettings
- hideLogs

We could add:
- hideWorkspaces
- hideHelp
- hideMaximize
