### ISSUE TITLE
Manual range picking would not calculate peaks

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2665]
The current version of NMRium displays peaks even when doing a range picking. This may help prevent users from doing peak picking + range picking.

However, because we are using a different algorithm for manual range picking, we don't have the peaks.

@jobo322, I would suggest that we also do a normal peak picking in the range so that we can display the peaks in this case.

**Comment by jobo322** [comment]
I could suggest to display the peaks of the pattern found by multiplet-analysis package. What do you think?
The peak would simulated
