### ISSUE TITLE
General preferences not used to generate ACS string

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2676]
<img width="674" alt="image" src="https://github.com/cheminfo/nmrium/assets/1484241/d8ae04e8-3482-4a61-a64c-0132e408f100">

<img width="574" alt="image" src="https://github.com/cheminfo/nmrium/assets/1484241/aa986e20-4c60-4e06-971a-8338188ccc4e">

You can use numeral in nmr-processing. Would make probably sense.

https://github.com/cheminfo/nmr-processing/blob/2c64c30fef1754f044222dbd0308f958ddb06f32/src/ranges/rangesToACS.ts#L17-L22

**Comment by jobo322** [comment]
the formatting preferences differ from ranges preferences.

**Comment by jobo322** [comment]
also we should refactor the name of formatting preferences 
<img width="440" alt="image" src="https://github.com/cheminfo/nmrium/assets/12143935/cc042915-7914-4a26-8331-4711ff8e9ad6">

ppm make sense but Hz for couplings is not clear
