### ISSUE TITLE
Nmrium with blueprintjs

### ISSUE THREAD

**Issue by stropitek** [cheminfo/nmrium#2704]
@hamed-musallam I recently made a move to use https://blueprintjs.com/ in react-science so that we can use a lot of nice UI components for free.

It will be required to add global css stylesheets to anywhere those components are used in addition to the `preflight.css`

Can you make the update, import the global styles and let us know if there are any issues related to them in all the environments in which you use Nmrium?

This is how to import the new styles:

https://github.com/zakodium-oss/react-science/blob/db366208ec8a85fe7060a0acd0011eb637113431/src/pages/demo/App.tsx#L8-L9

AFAIK you run nmrium in an iframe so it shouldn't be an issue.

I made a pre-release for you to use: https://www.npmjs.com/package/react-science/v/0.27.1-pre.1696432898

**Comment by hamed-musallam** [comment]
I think it is better to not  import the styles file inside the react-science and it could be listed in the instructions for using the package, for these reasons: 

1. the files will be loaded twice (unnecessary repeats) which could have an impact on the performance (in case the styles file sizes are big).
2. we could have style conflicts if we use different versions of blueprintjs.

**Comment by hamed-musallam** [comment]
For the NMRium component's styling integration, should we embed the CSS files directly within the NMRium component itself, or should they be referenced at the higher level where the NMRium component is invoked? i think the second option should be the way that I have to follow because their a chance that the blueprintjs could be used where we include the NMRium? WDT?

**Comment by hamed-musallam** [comment]
right now i embed the CSS files directly within the NMRium component and it works well but i think the CSS importation should be at a higher level where the NMRium is embedded

**Comment by stropitek** [comment]
> For the NMRium component's styling integration, should we embed the CSS files directly within the NMRium component itself, or should they be referenced at the higher level where the NMRium component is invoked? i think the second option should be the way that I have to follow because their a chance that the blueprintjs could be used where we include the NMRium? WDT?

I think both react-science and NMRium should include instructions on what css stylesheets must be loaded for them to work. It's up to the user to decide how / where they want to load the stylesheets.

> I think it is better to not import the style file inside the react-science and it could be listed in the instructions for using the package, for these reasons:

It is not imported when loading react-science. The link I gave you is in the demo, not in the library.

Blueprintjs is a dependency of react-science so it will be installed with it. We have to decide if it should be a peer dependency instead.

making it a direct dependency means that we use react-science as a proxy for what and how we want to expose from blueprintjs. It gives use better control and I personally prefer this option. If a project which depends on NMRium wants to use blueprintjs as well, it should be possible to install it there as well but taking care that they use the same version range so that they can be deduplicated.

@targos WDYT?

**Comment by targos** [comment]
I agree it should be a peer dependency (but still a normal dependency at the same time, since it's always used). The peer dependency will make sure that the correct version range is installed by the user.

**Comment by stropitek** [comment]
> I agree it should be a peer dependency (but still a normal dependency at the same time, since it's always used). The peer dependency will make sure that the correct version range is installed by the user.

Ok seems good to me. We also need it as a direct dependency so that we can import the stylesheets from blueprintjs.

**Comment by targos** [comment]
Oh right, so the user will always have to install it for that anyway.

**Comment by stropitek** [comment]
> I agree it should be a peer dependency (but still a normal dependency at the same time, since it's always used). The peer dependency will make sure that the correct version range is installed by the user.

If I make it both a prod and peer dependency, then it removes the peer dependency when I update the component:

![CleanShot 2023-10-05 at 14 14 04](https://github.com/cheminfo/nmrium/assets/4118690/96c3a29d-5b5a-4657-ab1b-aac0300c91c1)

So I think we have to make it a dev dep in react-science. The peer deps are updated automatically that way.

**Comment by stropitek** [comment]
react-science@0.27.1-pre.1696510245

New version with blueprintjs as peer depedency published

**Comment by hamed-musallam** [comment]
So the NMRium should also add the blueprintjs as a peer dependency?

**Comment by stropitek** [comment]
I'm not 100% sure but I think peer dependencies are resolved deeply so having it in react-science should be enough.

**Comment by targos** [comment]
> I'm not 100% sure but I think peer dependencies are resolved deeply so having it in react-science should be enough.

That should be true. NMRium should have it as devDependency

**Comment by hamed-musallam** [comment]
even in the case we want to use some of the UI components from blueprintjs?

**Comment by targos** [comment]
In that case it would be a dependency

**Comment by stropitek** [comment]
> even in the case we want to use some of the UI components from blueprintjs in NMRium?

You can do that, but should remember that if you create UI components that use blueprintjs components, you have to consider adding them to react-science.

**Comment by hamed-musallam** [comment]
I would prefer to keep it as dependency

**Comment by targos** [comment]
Yes, you can keep it as a dependency. We just ask that we discuss together before using it directly in NMRium, to see if it makes more sense to add components to react-science for the use case.
