### ISSUE TITLE
the properties of filters does not change correctly

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#2724]
When the filter can not be applied, the properties cell display a message, this message does not disappear when the filter can be applied. a brief video could explain better

https://github.com/cheminfo/nmrium/assets/12143935/18ba6bfe-60b0-476e-9732-728c1aaab881

**Comment by hamed-musallam** [comment]
waiting for a new release of nmr-processing 

- https://github.com/cheminfo/nmr-processing/pull/354
