### ISSUE TITLE
Jeol file not loaded ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2736]
[jeol.dx.zip](https://github.com/cheminfo/nmrium/files/13259078/jeol.dx.zip)

**Comment by jobo322** [comment]
currently we are not able to compute the `spectralWidth` from this file, but the spectrum is loaded now. Only think is waiting for minor release of nmr-load-save

**Comment by jobo322** [comment]
It is fixed by 0.23.2 of nmr-load-save
