### ISSUE TITLE
link JCAMP files are not loading

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#2757]
We identified an additional issue in the JCAMP parser, specifically, the proton and carbon JCAMP files are not loading

https://s3.uni-jena.de/nmrxiv/production/archive/a9d8c2a7-fc95-4eb6-84dd-107548aa0c48/12c_HEE296.zip

![image](https://github.com/cheminfo/nmrium/assets/35760236/f4afa2b9-fbb4-42f0-86a5-0686083c8d8f)

**Comment by lpatiny** [comment]
The JCAMP-DX contains many spectra and it is normal LINK is not loaded.

However on the page: https://my.cheminfo.org/?dataURL=https%3A%2F%2Fmyviews.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F7d3d52c930d0c4f381df1524593b3af3%2Fdata.json&viewURL=https%3A%2F%2Fmyviews.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F7d3d52c930d0c4f381df1524593b3af3%2Fview.json

I can see a NMR spectrum

![image](https://github.com/cheminfo/nmrium/assets/1484241/45bb667f-bd2d-4787-8191-a69c690f9064)

So it seems that the parser works correctly (but the view could contain an old version).
