### ISSUE TITLE
NMRium component v0.45.0 style reset 

### ISSUE THREAD

**Issue by tomlebl** [cheminfo/nmrium#2769]
I have imported preflight.css into global styles of my application which allows for correct rendering of NMRium component. Unfortunately, it also results in some conflicts with styles used in my app.  I had to slightly amend preflight.css file and some of my styles and eventually got both NMRium and my app to render OK which does not seem to be the ideal solution. 
So, I wonder if importing preflight.css into global styles is the right solution or I miss something and there is a way to reset styles for NMRium component only.

**Comment by targos** [comment]
`preflight.css` is one way to make the rendering of NMRium work, but you're free to use another style reset library or do your own version. Unfortunately there is no perfect solution. We were having too many issues blocking further developments with the shadow DOM that was used before.

**Comment by tomlebl** [comment]
That's fine. I just wanted to double check if I don't do anything wrong or missing something. 
Luckily, in my case I just had to customize the preflight.css by removing couple of selectors which had no adverse effect on NMRium rendering. So, all good so far. I should be able to carry on.
