### ISSUE TITLE
Phase correction correction is not correct in auto-processing

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#2775]
To reproduce use this test sample 

![Screenshot 2023-11-29 at 19 50 07](https://github.com/cheminfo/nmrium/assets/35760236/7792d015-c844-4cc5-af68-f6207dceedb3)
![Screenshot 2023-11-29 at 19 49 53](https://github.com/cheminfo/nmrium/assets/35760236/0edcfadd-0d00-405d-b658-ac0e769d885e)

**Comment by lpatiny** [comment]
For the carbon it was always like that AFAIK

[carbon.zip](https://github.com/cheminfo/nmrium/files/13512712/carbon.zip)

![image](https://github.com/cheminfo/nmrium/assets/1484241/dcbf36d4-e4cd-4827-85f2-aef3828cae0d)

Concerning the proton it seems however that it is worse than before. 


[proton.zip](https://github.com/cheminfo/nmrium/files/13512710/proton.zip)

![image](https://github.com/cheminfo/nmrium/assets/1484241/fa083baa-c79e-49bd-a131-b91c436a5612)

The spectrum should be loaded by topspin to check if we just don't load correctly the applied PH0 and PH1

**Comment by jobo322** [comment]
This problem is related with the last edition of ph0 -> 180 added as a compensation of the removal digital filter. So, it is better to check why the automatic phase correction is not able to find the correct values.

**Comment by jobo322** [comment]
This spectrum has a group delay of 67.98 (odd number of points moved)
