### ISSUE TITLE
General Settings / Title block can't be edited

### ISSUE THREAD

**Issue by tomlebl** [cheminfo/nmrium#2778]
The input drop down menu for Field in General Settings / Title Block offers only values from meta and display objects. 
Only values from the menu can be selected. Typing any input  seems to be disabled. 

For example I can't add a new field info.title which is possible in similar table in Spectra panel preferences.

**Comment by lpatiny** [comment]
Indeed typing in the input text does not filter the allowed values. There is a bug that prevents to add other fields.

![2023-12-14 09 26 07](https://github.com/cheminfo/nmrium/assets/1484241/eb38d228-5c46-48c2-9581-190adb39edba)
