### ISSUE TITLE
New react-science do not have DropdownMenu

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2791]
What is the idea ? 

Should we go to native Drop down menu or to blueprint ?

https://blueprintjs.com/docs/#select/select-component

**Comment by targos** [comment]
It's in the changelog: https://github.com/zakodium-oss/react-science/blob/main/CHANGELOG.md
There's an example in the storybook: https://react-science.pages.dev/stories/?path=/story/components-dropdownmenu--dropdown
