### ISSUE TITLE
Add toggle button to remove integration

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2797]
Could you add an option that allows to remove the integration value under the spectrum ? I would need in some case (preparing exams) to display the integration on the spectrum but not the value.

![image](https://github.com/cheminfo/nmrium/assets/1484241/67fe96ac-1085-46d1-b2c4-65b6246336f5)

**Comment by hamed-musallam** [comment]
@lpatiny 

You only need to remove the value without removing the line below?. Would you like to implement this on a per-spectrum basis like show/hide peaks ... etc (toggle button in the ranges and integrals panel header), or is it a general option in the general settings?

![image](https://github.com/cheminfo/nmrium/assets/35760236/4392ebb3-cf07-417e-a53a-fae3b3b0aea1)

**Comment by lpatiny** [comment]
Both line + value should be removed.
