### ISSUE TITLE
React component v0.46 has broken styling of toolbars

### ISSUE THREAD

**Issue by tomlebl** [cheminfo/nmrium#2815]
React component v0.46 seems to have broken styles for both vertical and horizontal toolbars. 
I have uploaded two screenshots from v0.46.1 and 0.45.0 in a very basic project that has only react, react-dom and nmrium as dependencies to avoid conflict with other libraries.
 
![NMRium-v0 46 1](https://github.com/cheminfo/nmrium/assets/38917582/673772a1-67e2-4682-84f9-a129ea262633)
![NMRium-v0 45 0](https://github.com/cheminfo/nmrium/assets/38917582/c6f3c32a-54c9-4af5-91bd-4eb48400d23f)

**Comment by hamed-musallam** [comment]
Hello @tomlebl 

We start using components from the blueprints at https://blueprintjs.com/docs/. Starting from version 0.46, it is necessary to import the blueprint styles in addition to `preflight.css`

```ts
import '@blueprintjs/core/lib/css/blueprint.css';
import '@blueprintjs/icons/lib/css/blueprint-icons.css';
```
