### ISSUE TITLE
Soritng ranges

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2866]
Would be nice to be able to sort ranges by chemical shifts (delta). In order to sort you should use the `range.from` value.

![2024-01-30 08 07 08](https://github.com/cheminfo/nmrium/assets/1484241/1664e4f1-8905-412b-a5a5-d202b373224e)

This was a request from Michel Gravel.

**Comment by michelgravel** [comment]
Thank you! That's a nice feature.
