### ISSUE TITLE
Fix .svg formatting of metadata for Word

### ISSUE THREAD

**Issue by rabatkri** [cheminfo/nmrium#2881]
# Current Behaviour

It is possible to export the spectra as .svg file from NMRium. But there is a formatting problem with the metadata when importing the .svg into Microsoft Word.

When importing the .svg file into a Microsoft Word (tested with Version 16.81 MacBook Air 2017) the formatting of the metadata (top left corner) is wrong. For this a .pdf file obtained from Microsoft word is attached. 
When opening the same file in Google Chrome the formatting is not a problem or here as well. This problem also does not appear when using exported .png file. 

.svg file
![KRA-064-A_10](https://github.com/cheminfo/nmrium/assets/158492972/d021c848-784a-4950-af19-7e16bcf6f84c)

.png file
![KRA-064-A_10](https://github.com/cheminfo/nmrium/assets/158492972/c1d821ad-a503-4e63-96b5-a30106811b76)

# Obtained .pdf from Microsoft Word

[svg_vs_png_file.pdf](https://github.com/cheminfo/nmrium/files/14127737/svg_vs_png_file.pdf)

# Original data for possible reproduction

[KRA-064-A.zip](https://github.com/cheminfo/nmrium/files/14127753/KRA-064-A.zip)

Thanks! I'm happy to provide additional information.

**Comment by lpatiny** [comment]
@rabatkri thanks for reporting this issue. We have identified the problem and it should be fixed in the next version.

You can already test it here: https://svg.nmrium.pages.dev/

**Comment by rabatkri** [comment]
Thanks it works well and thanks for the quick fix @lpatiny

**Comment by lpatiny** [comment]
@rabatkri the new version is now in production on www.nmrium.org

Could you register on https://www.nmrium.org/contact so that we can keep you informed about the new features ?

**Comment by rabatkri** [comment]
@lpatiny thank you!
