### ISSUE TITLE
Improve formatting of exported file for stacked spectra

### ISSUE THREAD

**Issue by rabatkri** [cheminfo/nmrium#2901]
# Current behaviour

Hello, I noticed further possible improvement when exporting file of stacked spectra from NMRium. When stacking two (or more) 1H NMR spectra and then exporting the file as .svg or .png the spectra are cut (see below).

exported .svg file
![KRA-085-1-A_10 (6)](https://github.com/cheminfo/nmrium/assets/158492972/ebb05327-bcfb-4f62-9701-b877995ca7fd)

exported .png file
![KRA-085-1-A_10 (1)](https://github.com/cheminfo/nmrium/assets/158492972/13116d27-6b8a-4a57-abf2-17fb5c94a459)

original data for possible reproduction
[KRA-085-1-A (2).zip](https://github.com/cheminfo/nmrium/files/14232614/KRA-085-1-A.2.zip)
[KRA-085-2-A (2).zip](https://github.com/cheminfo/nmrium/files/14232615/KRA-085-2-A.2.zip)
NMRium file of the stacked spectra
[KRA-085_stackedspectra.nmrium.zip](https://github.com/cheminfo/nmrium/files/14232613/KRA-085_stackedspectra.nmrium.zip)

Thank you in advance! And I'm happy to provide any additional information.

**Comment by hamed-musallam** [comment]
@rabatkri  

Thank you for reporting this issue. We resolved the issue and it should be fixed in the coming version 

You can test it here: https://fix-export-spectra-as-svg.nmrium.pages.dev/

**Comment by rabatkri** [comment]
@hamed-musallam thanks!
