### ISSUE TITLE
Should we have larger icons in panels

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2921]
With the new version the panel font and panel icons increased quite a lot. Do we want this ?

<img width="380" alt="image" src="https://github.com/cheminfo/nmrium/assets/1484241/5a91266a-0926-41ed-aa6b-47f7bcbb0cc5">

<img width="422" alt="image" src="https://github.com/cheminfo/nmrium/assets/1484241/fef3180a-3f94-42d6-9cef-23d9df2c7a8a">

**Comment by hamed-musallam** [comment]
https://github.com/zakodium-oss/react-science/issues/614#issuecomment-1859982201

**Comment by lpatiny** [comment]
We will change this in react-science:
- https://github.com/zakodium-oss/react-science/issues/new
