### ISSUE TITLE
Improve peak picking

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2933]
Currently we have 2 parameters to make peak picking but we don't really now what they do. There is no preview on the spectrum about the range that will be used to make the peak picking.

While changing the parameters we should preview 2 rectangles that hides (semi transparent) the zone that will not be picked.

Those 2 rectangles will also depend on the option Positive, Negative, Both. If positive is selected the rectangle will go down to the horizontal axis.

@jobo322 Noise should be sent to GSD. Can we use the noise calculated by the sanplot ? Maybe currently we calculate the noise only when opening the color selector to display the sanplot. This should probably be cached somewhere.

![image](https://github.com/cheminfo/nmrium/assets/1484241/23aa37e6-29b1-45f1-9eaf-3b54a8feb701)

**Comment by jobo322** [comment]
checking in global, we should need to have access to: 
- the noise of the spectrum (sanplot) and
- maxValue absolute value of the second derivative.

the second requirement will be used at the moment to apply a peak picking in a small region.
