### ISSUE TITLE
Small improvements on multiple spectra analysis

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2940]
## Tool availability

Multiple spectra analysis tool is useful even if there is only one spectrum ... 

Please make the icon available even in this case (currently it is not there if there is not more than one 1D spectrum).

![image](https://github.com/cheminfo/nmrium/assets/1484241/6c6271d9-864d-4adb-8e1d-0490ccbbb754)

## Hide behind developer flag part of the preferences

Those options and quite advanced (and currently useless) and could be hidden behind the developer flag:

![image](https://github.com/cheminfo/nmrium/assets/1484241/316d8f07-2a6f-404d-b27e-ebaadec6fc9f)

## Resort spectra ?

Not sure what is this checkbox:

![image](https://github.com/cheminfo/nmrium/assets/1484241/3a251ba7-0ca4-4ea2-81cc-c615916cc8d4)

## Relative intensity ?

Not obvious to me how we calculate relative intensity:

![image](https://github.com/cheminfo/nmrium/assets/1484241/9409a45b-7a92-4db5-9716-2d5afad76694)

**Comment by hamed-musallam** [comment]
> Not sure what is this checkbox:
>![image](https://github.com/cheminfo/nmrium/assets/35760236/366cf6af-652c-4d3c-86a8-2fe6146141d5)

It's an option that toggles the ordering of the spectra you requested a while back. By default, it's set to true, Do you want to remove it?

>Not obvious to me how we calculate relative intensity:
> ![image](https://github.com/cheminfo/nmrium/assets/35760236/74652f25-5a23-4bf9-83b9-403a6642630b)

It's relative to 100, but currently, we do not have the option to change the sum but the object structure is designed to take care of this

**Comment by lpatiny** [comment]
We should discuss about this spectra ordering because I'm not sure what it does.

I activate it and it seems that we reorder spectra from time to time. I could not find the logic.

![2024-03-05 21 52 58](https://github.com/cheminfo/nmrium/assets/1484241/06537619-dd54-43e8-b603-6e1ec6e02144)
