### ISSUE TITLE
Zooming in and out with the mouse wheel

### ISSUE THREAD

**Issue by michelgravel** [cheminfo/nmrium#2962]
I suggest adding a functionality to zoom in and out of the spectrum in a gradual fashion rather than by selecting a zone. Some commercial software have this functionality and it is very useful when we want to increase or decrease the zoom window. Less annoying than double clicking to a previous zoom window. For example, one could hold the right mouse button and scroll the mouse wheel at the same time.

**Comment by lpatiny** [comment]
@michelgravel you can test the new features here: https://github.com/cheminfo/nmrium

We did shift + scroll wheel.

**Comment by michelgravel** [comment]
Fantastique!

Merci,

Michel

Michel Gravel
Dept of Chemistry
University of Saskatchewan
110 Science Place
Saskatoon, SK  S7N 5C9
306-966-7785
https://research-groups.usask.ca/gravel/index.php
