### ISSUE TITLE
Recolor spectra on 2D

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2990]
Would be nice that recolor spectra also works on 2D. For now we can only recolor the positive part of the 2D.

![image](https://github.com/cheminfo/nmrium/assets/1484241/4868d930-9301-4ca3-8f46-aa6b00e9d11c)

**Comment by hamed-musallam** [comment]
The recoloring functionality is working but it takes into account the constant colors which we defined in the past based on the experiment value.

https://github.com/cheminfo/nmrium/blob/bc28413e2b82ea62cee7600addb2a4b1e5738058/src/data/utilities/generateColor.ts#L26-L33

**Comment by lpatiny** [comment]
Ok I see. I would then have 2 buttons, one for 'Set predefined colors' and the current one for 'Recolor'

With the current behavior, is it normal that even if I delete all the predefined colors

![image](https://github.com/cheminfo/nmrium/assets/1484241/b18c1b1f-e48b-4bec-89ab-2dd7b754eb72)

recolor does nothing ?


![2024-03-25 11 53 25](https://github.com/cheminfo/nmrium/assets/1484241/aff700c8-5e9e-48e6-8d28-0c20206c9630)

**Comment by hamed-musallam** [comment]
As you know we recently added the feature of predefined colors which differs from what you're currently observing. 

https://github.com/cheminfo/nmrium/blob/bc28413e2b82ea62cee7600addb2a4b1e5738058/src/data/utilities/generateColor.ts#L26-L33 


 Within the color function, we initially search for predefined custom colors. If none are found, we then check for constant colors. If neither exists, we generate a random color

**Comment by hamed-musallam** [comment]
I suggest updating the constant colors to align with the latest schema we agreed upon. Additionally, we can have two buttons: one to apply the color preferences and the other to generate colors randomly

**Comment by hamed-musallam** [comment]
> So I think the 2 buttons approach (default and distinct) is the way to go.
> 
> I also get strange results when I try to recolor using the contextual menu.
> 
> ![2024-03-25 12 08 55](https://private-user-images.githubusercontent.com/1484241/316479877-95ea320d-ff6b-40e0-806e-46b701d7c33a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjUzMjIsIm5iZiI6MTcxMTM2NTAyMiwicGF0aCI6Ii8xNDg0MjQxLzMxNjQ3OTg3Ny05NWVhMzIwZC1mZjZiLTQwZTAtODA2ZS00NmI3MDFkN2MzM2EuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMTExMDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQyYmVlMDNlMjFiZTE2NzIyYWU5NzkyNmRlMTM1NmUzYzFhMDI5ZTJmM2JkYzE3ZWQ5M2U3NGYxM2NkMTQzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TSkfYPAY3UbC07OC2Y-Dg_yKDwesTGFapwce9JiaPhI) [ ![2024-03-25 12 08 55](https://private-user-images.githubusercontent.com/1484241/316479877-95ea320d-ff6b-40e0-806e-46b701d7c33a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjUzMjIsIm5iZiI6MTcxMTM2NTAyMiwicGF0aCI6Ii8xNDg0MjQxLzMxNjQ3OTg3Ny05NWVhMzIwZC1mZjZiLTQwZTAtODA2ZS00NmI3MDFkN2MzM2EuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMTExMDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQyYmVlMDNlMjFiZTE2NzIyYWU5NzkyNmRlMTM1NmUzYzFhMDI5ZTJmM2JkYzE3ZWQ5M2U3NGYxM2NkMTQzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TSkfYPAY3UbC07OC2Y-Dg_yKDwesTGFapwce9JiaPhI) ](https://private-user-images.githubusercontent.com/1484241/316479877-95ea320d-ff6b-40e0-806e-46b701d7c33a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjUzMjIsIm5iZiI6MTcxMTM2NTAyMiwicGF0aCI6Ii8xNDg0MjQxLzMxNjQ3OTg3Ny05NWVhMzIwZC1mZjZiLTQwZTAtODA2ZS00NmI3MDFkN2MzM2EuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMTExMDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQyYmVlMDNlMjFiZTE2NzIyYWU5NzkyNmRlMTM1NmUzYzFhMDI5ZTJmM2JkYzE3ZWQ5M2U3NGYxM2NkMTQzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TSkfYPAY3UbC07OC2Y-Dg_yKDwesTGFapwce9JiaPhI) [ ](https://private-user-images.githubusercontent.com/1484241/316479877-95ea320d-ff6b-40e0-806e-46b701d7c33a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjUzMjIsIm5iZiI6MTcxMTM2NTAyMiwicGF0aCI6Ii8xNDg0MjQxLzMxNjQ3OTg3Ny05NWVhMzIwZC1mZjZiLTQwZTAtODA2ZS00NmI3MDFkN2MzM2EuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMTExMDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQyYmVlMDNlMjFiZTE2NzIyYWU5NzkyNmRlMTM1NmUzYzFhMDI5ZTJmM2JkYzE3ZWQ5M2U3NGYxM2NkMTQzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TSkfYPAY3UbC07OC2Y-Dg_yKDwesTGFapwce9JiaPhI)


This may not be an issue in 1D but it is in 2. It should rely on column (experiment) values to generate the colors but it seems is not, I will check why this not working but the question should we generate a random color in this case or we should keep relying on `experiment` to  ensure consistency

**Comment by lpatiny** [comment]
Yes it should be a random color in this case. Same is true in 1D. If we recolor by distinct value (contextual menu) we should have one color per distinct value.

**Comment by hamed-musallam** [comment]
This applies to all other information except for the experiment column. For the experiment column, should it be a random color too, or based on the predefined colors?

**Comment by lpatiny** [comment]
If we have the button to reset the experiment colors I think the contextual menu should always make the random color.
