### ISSUE TITLE
195Pt NMR spectrum incorrectly displayed

### ISSUE THREAD

**Issue by schatzsc** [cheminfo/nmrium#2999]
As already mentioned in the Chemotion repository as issue https://github.com/ComPlat/chemotion_ELN/issues/1685 195Pt NMR spectrum is not correctly displayed:

NMRium running inside Chemotion v1.8.0 shows an **incorrect x-axis** - chemical shift -27.5 to -33 instead of the correct range of -2450 to -2850 ppm as shown in TopSpin.

Furthermore, although the spectrometer frequency is correctly read as 85 MHz, the **spectrum is classified as 1H instead of 195Pt** (.OBSERVENUCLEUS)

NMRium/Chemotion

![Screenshot 2024-03-27 at 16-11-21 Chemotion](https://github.com/cheminfo/nmrium/assets/88166560/d33d421e-cf04-47d8-82cd-238eaca5cfbf)

Bruker TopSpin

![Screenshot 2024-03-27 162331](https://github.com/cheminfo/nmrium/assets/88166560/fd45c29f-a4af-4336-8c85-b414869effcc)

Original folder

[32.zip](https://github.com/cheminfo/nmrium/files/14776078/32.zip)

*.dx file export from TopSpin

[nmr.zip](https://github.com/cheminfo/nmrium/files/14776081/nmr.zip)

**Comment by lpatiny** [comment]
@schatzsc We currently don't have a precise value of the gyromagnetic radio for 195Pt. Could you provide it with a reference (DOI) ? We need to add the value here: https://github.com/cheminfo/gyromagnetic-ratio/blob/main/src/index.ts#L40-L43

**Comment by lpatiny** [comment]
Could you also check on https://www.nmrium.org/nmrium because it seems that the spectrum is loading but I'm not sure about the exact top of the peak.

**Comment by schatzsc** [comment]
Interestingly, in the NMRium online instance that was linked above, the spectrum displays correctly, regardless of how I import it (Bruker zipped folder, *.dx file or zipped *.dx file - only one example shown):

![Screenshot 2024-03-28 at 18-45-44 NMRium](https://github.com/cheminfo/nmrium/assets/88166560/7e8020c7-9205-4bb6-8dd0-f90504a8349a)

**Comment by schatzsc** [comment]
Doing exactly the same with the Chemotion-internal NMRium the scale is now correct but no peak shown and the spectrum indicated as "13C" although from the ontology I selected "195Pt NMR"

![Screenshot 2024-03-28 at 18-52-00 Chemotion](https://github.com/cheminfo/nmrium/assets/88166560/9481cce9-1556-4aed-949a-fe89eac2ea50)

**Comment by schatzsc** [comment]
@lpatiny Could it be that the NMRium versions in the online application and inside Chemotion are different?!?

**Comment by schatzsc** [comment]
@lpatiny Gyromagnetic ratio of some common NMR nuclei are reported in [Pure Appl. Chem. 2001, 73, 1795-1818](https://dx.doi.org/10.1351/pac200173111795) however they are off by a factor of 10 from what is used in your source code as the unit is 10^7 rad s^-1 T^-1

The value for 195Pt there is 21.496784 * 10^7

Not sure if the values are regularly updated or why your table has slightly different values?!?

![gyromagnetic_ratio](https://github.com/cheminfo/nmrium/assets/88166560/f43f0c35-5569-46b9-afc6-bd3e34c78aa3)

**Comment by lpatiny** [comment]
@jobo322 please update the list https://github.com/cheminfo/gyromagnetic-ratio/blob/main/src/index.ts#L40-L43 and add as many gyromagnetic ratio as possible. Please also the reference in JsDOC.

**Comment by schatzsc** [comment]
@jobo322 If you don't have the full reference, please let me know here with an email to send the full paper to - there is also a 2nd page with the gyromagnetic ratio of the I > 1/2 nuclei. And keep in mind the differences due multiplicator 10^7 in the paper.

**Comment by jobo322** [comment]
@schatzsc could you have a look to: 
- https://c9894558.nmrium.pages.dev/

I add more gyromagnetic ratio constants, could you check if the behavior is the expected, please.

**Comment by schatzsc** [comment]
As far as I can tell, the result in the online NMRium instance now looks exactly like the TopSpin one but I have no data at the moment to check for other nuclei (although we do generally have, for example, 11B, 19F, 31P, and 77Se NMR spectra, but I need to get them from the coworkers first).

**How to get this new version integrated into Chemotion now?!?**

![Screenshot 2024-04-03 202023](https://github.com/cheminfo/nmrium/assets/88166560/942377ea-33bb-4462-8b23-46e8bd027557)

**Comment by lpatiny** [comment]
Thanks for testing the new version and confirming the issue is fixed. If you have question about chemotion please open issues in their repository.
