### ISSUE TITLE
Cannot pick multiplets in 19F NMR spectrum

### ISSUE THREAD

**Issue by schatzsc** [cheminfo/nmrium#3000]
When typing to select the doublet peak in the 19F NMR of hexafluorophosphate [PF6]- due to coupling with the I = 1/2 31P nucleus, NMRium does not allow one to select the peaks with an error message "Advanced peak picking only available for area up to 2048 points" although such large coupling constants (here 711 Hz) are very common in heteronuclear NMR (and there are even larger ones, see link below, like a 1253 Hz 2JHg,F coupling in Hg(CF3)2)

![Screenshot 2024-03-27 at 18-23-22 Chemotion](https://github.com/cheminfo/nmrium/assets/88166560/a242d2bc-972b-4d9f-97b3-e72b133fe8e2)

https://fluorine.ch.man.ac.uk/research/nmr_terms.php?n_nuclei=6&I_nuclei=0.5

**Comment by lpatiny** [comment]
@schatzsc Could you upload a public JCAMP-DX file that has this coupling ? You can add it in an issue zipped.

**Comment by schatzsc** [comment]
At the moment I only have the file that I can export from our Chemotion NMRium instance using "Export as -> Save data as" but since there is also an import function I hope it can be re-imported in another NMRium system.

[19FNMR.zip](https://github.com/cheminfo/nmrium/files/14793550/19FNMR.zip)

**Comment by schatzsc** [comment]
Still not working, when I try to select the two peaks between -71 and -74 ppm which form a dublet with a very large 1J(F-P) coupling, I get the following error message:

Not sure what the "windowSize" referes to?!? I have a very large LCD screen of something like 32" Philips 328P6VU with 3840x2160 resolution which also caused problems with earlier versions of Chemotion, so maybe it is a display-specific issue?

![Screenshot 2024-04-03 202606](https://github.com/cheminfo/nmrium/assets/88166560/8b2e1b2e-839e-4770-85fa-659b7f7e26a7)

**Comment by lpatiny** [comment]
windowSize is related to peak picking algorithm and not the computer screen.

**Comment by schatzsc** [comment]
Ok, then maybe the peak picking algorithm uses a too small window to look for associated signals of a multiplet pattern.

The 1J(F-P) coupling in hexafluorophosphate is 711 Hz:

`https://fluorine.ch.man.ac.uk/research/nmr_terms.php`

**Comment by schatzsc** [comment]
Another issue that will likely cause problems for example with 13C-19F coupling is due to the fact that multiplets are overlapping. 

For example, there can be two 13C NMR signals which are both split to a rather large dublet that show up as follows:

A1 B1 A2 B2

Where A is 1st dublet and B is 2nd dublet. An automated peak picking will then likely combine A1 and B1 as well as A2 and B2 - for such instances manual selection would be essential.

Furthermore, we also very often have complicated multiplets like ddd or dt or td

**Comment by jobo322** [comment]
Currently, the range picking use a default value of 16 Hz to merge peaks into a signal. So we should expose those options in order to manage this case of use.

- another issue is related with the nmrium file shared on this ticket, there is not a frequency data on `info`, on `meta` there is .OBSERVEFREQUENCY but I don't understand why if there is `data` in the file, the info object is not complete

**Comment by schatzsc** [comment]
Maybe part of the information was lost when the spectrum was exported from Chemotion?!?

Please find attached below another 19F NMR showing the same large splitting of around 700 Hz due to 1J(F-P) coupling in hexafluorophosphate (Standard Bruker format from approx. 2018):

[19F NMR.zip](https://github.com/user-attachments/files/15567257/19F.NMR.zip)

**Comment by jobo322** [comment]
Could you try to export the same nmrium file from chemotion to test it please. With the shared jcamp file and manually range picking I got it.

<img width="939" alt="image" src="https://github.com/cheminfo/nmrium/assets/12143935/af6594ae-73c6-413f-ae64-79858cf0a93b">

**Comment by jobo322** [comment]
@lpatiny should we export more xyAutoRangePicking options for those case of use or adapt the frequency clustering by nucleus.

**Comment by schatzsc** [comment]
@jobo322 Here is the above 19F NMR after the "round trip" upload to Chemotion (now version 1.9.3) -> open in internal NMRium (version included unclear to me) -> export from internal NMRium together with the options used. I don't remember which options were used the previous time - maybe that is the reason for missing data that not all options were checked?!?

[19F-NMR-from_chemotion.zip](https://github.com/user-attachments/files/15593599/19F-NMR-from_chemotion.zip)
<img width="261" alt="nmrium save file options" src="https://github.com/cheminfo/nmrium/assets/88166560/473b805e-8d2e-4bd1-95ce-7c3dcf440923">
