### ISSUE TITLE
Hardcoded axis values

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3024]
I had a request to be able to manually enter the values from/to of the axis in order to consistently generate spectra with the same scale. This makes sense, but I don't know how to do this in an intuitive way so that if we set the values and zoom 'full out', we don't loose those settings.

We could consider the possibility in the General preferences to have a predefined 'from' / 'to' for each nucleus, but I don't know how we could apply / recall those settings when manipulating the spectrum. Maybe it could be an alternate shortcut of the full out like SHIFT + click or SHIFT + 'f'.

**Comment by hamed-musallam** [comment]
It is a good idea to specify these settings in the general preferences. The question arises: should we continue to use the original domain, or will the newly defined "from/to" always replace the original unless the domain constraint is removed from the general settings? Alternatively, we might consider implementing a dedicated shortcut for full zooming out to the "from/to" value

**Comment by schatzsc** [comment]
I like the idea to specific the x axis limits by input of specific values (like 10 to -5 ppm) a lot, as it will indeed help much to overlay spectra for comparison. Please don't forget that for many nuclei the chemical shift can also be negative, either just one value or both.

**Comment by hamed-musallam** [comment]
@lpatiny 

Should we include these axis constraints in the `General` tab of the general settings, or should we create a new tab specifically for `Axis Constraints`? these preferences will be part of the workspace

**Comment by lpatiny** [comment]
Because it is related to the nucleus / nuclei like in the tabs of the spectra panels it could be 

![image](https://github.com/cheminfo/nmrium/assets/1484241/23495d44-412b-45ee-8a71-71da1dc5294e)

Under each section where we select the columns 

![image](https://github.com/cheminfo/nmrium/assets/1484241/af0be305-c058-43c9-bab1-b1fc622448bf)

we can add X axis: from / to (if 1D)

or

X axis : from / to
Y axis : from / to

For now I would just provide the `Shift + double-click`

**Comment by lpatiny** [comment]
Double click is not a good because we use it already.

Forcing from / to is optional so if we set them we are expected to know what we are doing...

If those values are there, and we press SHFIT + `f` it takes those values.
