### ISSUE TITLE
Integration bug ?!

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3027]
Here is a simulated spectrum:

[1h.jdx.zip](https://github.com/cheminfo/nmrium/files/15052137/1h.jdx.zip)

When we try to integrate it we have something very weird

![image](https://github.com/cheminfo/nmrium/assets/1484241/fec7c9d5-09a5-471d-ab8b-df7c3b9c8943)

**Comment by jobo322** [comment]
@hamed-musallam seems the integration tool is receiving the spectrum with a reduced number of points instead of the original, that is possibly the reason that the integration draw change depending of the zoom on X

**Comment by lpatiny** [comment]
I guess it is then displaying the result. The integral is not recalculated when zoom in.
