### ISSUE TITLE
Multiple spectra analysis sorting option

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3036]
Not sure what is this option:

![image](https://github.com/cheminfo/nmrium/assets/1484241/86238e5d-541c-472f-b02b-348fde50c34a)

Maybe it can be related to sorting the spectra in the state ?

Seems this option is not saved if you change it and even if unchecked the spectra in the state are not change.

I would change the description to `Sort spectra when sorting columns`

**Comment by hamed-musallam** [comment]
@lpatiny 

When you activate this option and rearrange the multiple spectra analysis, it also rearranges the spectra.

**Comment by lpatiny** [comment]
But this preferences is not saved.

![2024-05-10 09 52 11](https://github.com/cheminfo/nmrium/assets/1484241/8c6f7a0d-886d-4d79-8a50-f32a2710dca2)
