### ISSUE TITLE
Errors in the console

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3051]
@hamed-musallam Could you have a look at the errors that appears in the console ?

![image](https://github.com/cheminfo/nmrium/assets/1484241/07c9dca5-2c99-49a9-bb91-94b8b58d4c20)

**Comment by hamed-musallam** [comment]
I fixed the issues related to react-table. The remaining warnings are from the BlueprintJS table component used in the information panel, which is an issue in the blueprints itself.
![image](https://github.com/cheminfo/nmrium/assets/35760236/e75bb227-ed52-4aa8-9751-cf255479f7e2)
