### ISSUE TITLE
Assignment highlighting color customization

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmrium#3057]
We received feedback that the assignment highlight color lacks contrast and could be customized.

![grafik](https://github.com/cheminfo/nmrium/assets/40795855/d8708fe8-472d-41b8-989d-12b22459641b)

@evaziegler

**Comment by lpatiny** [comment]
In general preferences we could rename the tab 'Spectra colors' to 'Colors' and add the highlight color property there.

![image](https://github.com/cheminfo/nmrium/assets/1484241/36aed011-7d18-47c0-9b8b-e7d47772730a)
