### ISSUE TITLE
Replace Formik by useForm

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3060]
Hamed would like to replace Formik by useForm. Is this the right choice @targos @stropitek ?

**Comment by targos** [comment]
Can you link to what you mean by `useForm`? There are many libraries that export a hook by that name.

**Comment by hamed-musallam** [comment]
We want to use this library https://react-hook-form.com/docs/useform

**Comment by stropitek** [comment]
`react-hook-form` is what we use as well in our projects.

There is an alternative that I find interesting but which I have never used and is not stable yet: https://tanstack.com/form/latest/docs/overview
