### ISSUE TITLE
Add possibility to move the 'title block'

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3061]
when hover the title block the little move icon could appear like in the zones label in order to move the block.

![image](https://github.com/cheminfo/nmrium/assets/1484241/9a24f5e4-f924-464c-95de-6d4c98474b7c)

**Comment by hamed-musallam** [comment]
@lpatiny 

should we save the location in the settings per workspace?

**Comment by lpatiny** [comment]
Yes this is a good idea !
