### ISSUE TITLE
Chemical structures not displayed in Database panel

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3068]
![image](https://github.com/cheminfo/nmrium/assets/1484241/897c1ff8-a963-4f1e-9901-9d905c41d8ef)

Hamed told me:

> The issue is from ResponsiveChart component, with out specifying the minimum value for the width and height it is not render the content.

@stropitek @targos any idea ?

**Comment by stropitek** [comment]
How is the issue with ResponsiveChart related to the screenshot?

**Comment by lpatiny** [comment]
@hamed-musallam This component was not changed recently so I guess the bug is somewhere else.

**Comment by lpatiny** [comment]
Closed by 4ce0d2b363b73d561a0ba2e5810c84d28bedf341
