### ISSUE TITLE
Prediction, name and frequencies

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3080]
![image](https://github.com/cheminfo/nmrium/assets/1484241/c6dfa44a-6626-4c83-9d29-2ac6ff623356)

When predicting a spectrum the name is pretty ugly.

Frequency is also not correct because we display for 2D the 2 frequencies.

![image](https://github.com/cheminfo/nmrium/assets/1484241/cbe27b37-18ba-407c-ad49-acec8211fb89)

**Comment by hamed-musallam** [comment]
@lpatiny 

I checked the `frequency` in the information panel and it seems correct to me, doesn't it?
![image](https://github.com/cheminfo/nmrium/assets/35760236/1dcf425c-2798-451d-be58-2a0908057993)

**Comment by lpatiny** [comment]
In the spectrum name for the 2D we should only keep the first frequency see (element 0 of the array) because the other one can anyway be calculated.

For the frequency column

![image](https://github.com/cheminfo/nmrium/assets/1484241/15cd6b03-592e-4a71-8461-26bde9e1a822)

We need a specific renderer so that we also only display the first frequency.
