### ISSUE TITLE
Import multiplet

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3088]
`1H NMR (CDCl3, 400MHz) δ 1 (s, 1H), 2 (d, 1H, J=7), 3 (t, 1H, J=7), 4 (q, 1H, J=7), 5 (quint, 1H, J=7), 6 (hex, 1H, J=7), 7 (hept, 1H, J=7), 8 (dd, 1H, J=7, J=4)`

Currently hex, hept, quint, ... are not recognized correctly.

**Comment by targos** [comment]
@jobo322 Is anything blocking this?
