### ISSUE TITLE
Add possibility to vertical move the peaks

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3112]
When peaks are at the top, we should be able to determine the position from the top of the screen. This could be achieved either with a vertical move of the entire block or, if problematic, by changing a preference.

This is applicable when displaying the peaks in the range, as well as in the case of peak picking. It might be better to have two different preferences.

**Comment by hamed-musallam** [comment]
Hello Luc, should these preferences be set per Nucleus or spectrum? in the ranges and peaks preferences

**Comment by lpatiny** [comment]
This could be done globally. No need to do it by nucleus.

**Comment by hamed-musallam** [comment]
- https://github.com/cheminfo/nmr-load-save/pull/450
