### ISSUE TITLE
Baseline corrections and precalculated zone

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3113]
When we try to calculate baseline correction the default algorithm is polynomial. Before it used to preselect the zones containing the baseline but it is not the case anymore.

We now need to do it manually.

Are we sure that we call this preselection algorithm and it returns no range or we don't call this method ?

![image](https://github.com/cheminfo/nmrium/assets/1484241/cdbf7e0a-9caa-4f24-89ce-7831635d36a9)

**Comment by hamed-musallam** [comment]
Which version are you using and having this issue in? This is what I get when testing on the dev site

![image](https://github.com/cheminfo/nmrium/assets/35760236/7a1cae3d-fff1-472f-aea5-e72afd4434f5)

**Comment by lpatiny** [comment]
This problem only appears when we don't do apodization on the carbon FID spectrum:

https://dev.nmrium.org/#/SamplesDashboard/ewhnjh72q95/Viewdatacytisinedatacytisine13CFIDjson

@jobo322 when you are back from holiday please have a look at this issue.
