### ISSUE TITLE
Button to edit metadata should not be shown if clicking on it does nothing

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#3115]
![CleanShot 2024-07-06 at 14 05 32@2x](https://github.com/cheminfo/nmrium/assets/2352663/53c3944c-2ec1-4f91-be77-c470bccf766a)

**Comment by hamed-musallam** [comment]
maybe better to disable the button rather than hide it which for the end user means the action is currently unavailable, rather than thinking the option doesn't exist and to activate the option he should meet a certain condition ( in our case, select a spectrum from the spectra panel).
