### ISSUE TITLE
Resize baseline zone crash

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3123]
We have the following crash:

<img width="743" alt="image" src="https://github.com/cheminfo/nmrium/assets/1484241/ddfc3c50-e38d-4455-994e-d59a79d6520e">

If we try to resize a baseline range.

<img width="754" alt="image" src="https://github.com/cheminfo/nmrium/assets/1484241/d7aef29d-8daf-4c94-9374-819a3317fa03">

**Comment by targos** [comment]
Was introduced by https://github.com/cheminfo/nmrium/commit/1c007382de62c0a949e28fb729e5858fcb73716e

It is very concerning that we have so many regressions after the forms refactorings.
