### ISSUE TITLE
Error when selecting a spectrum after recalling configuration with deleted spectrum

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#3125]
To reproduce:

- Open multiple spectra
- Select a spectrum
- Press 1
- Delete the selected spectrum
- Press 1 again
- Select another spectrum

https://github.com/cheminfo/nmrium/assets/2352663/b909c8b8-08e6-4010-b83c-256f408ea706

**Comment by hamed-musallam** [comment]
This issue needs some discussion before I start resolving it, The question is whether we should revert the spectrum if we save the preferences before the spectrum deletion, or if we should ignore all objects in the view state and domain ...etc that are related to the deleted spectrum
