### ISSUE TITLE
Error "fft not applicable on this data" after removing previous processings

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#3132]
- Drag and drop: [aspirin-1h.zip](https://github.com/user-attachments/files/16261103/aspirin-1h.zip)
- Delete all 3 filters that are before the FFT.
- Select the FFT

**Comment by hamed-musallam** [comment]
related to https://github.com/cheminfo/nmrium/issues/3152

**Comment by hamed-musallam** [comment]
it should no longer crash as the issue was caused by the digital filter, which should not have been allowed to be deleted.

**Comment by hamed-musallam** [comment]
Could you please test and close the issue if it is resolved? https://dev.nmrium.org/

**Comment by targos** [comment]
Looks ok, thanks.
