### ISSUE TITLE
Invalid DOM nesting

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#3133]
Can be reproduced just by opening any spectrum in the component

![CleanShot 2024-07-18 at 11 29 31](https://github.com/user-attachments/assets/a6414dae-a3e6-48a7-bff4-42736a32b252)

@hamed-musallam I recommend to always work with the developer tools open, in order to see console warnings and errors as soon as possible during development.

**Comment by hamed-musallam** [comment]
- https://github.com/zakodium-oss/react-science/pull/749
