### ISSUE TITLE
Crash with large molecules

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3134]
Some users have very large molecules, and currently, if we have more than 250 heavy atoms, we throw an error in order to prevent the program from becoming unresponsive.

This is okay as long as the error is caught and a simple error message is displayed to the end user.

Currently this error is not cached everywhere and leads to application crash with lost of all the work in progress.

In order to repeat one of the cases just drag / drop this molfile.

[large.mol.zip](https://github.com/user-attachments/files/16282690/large.mol.zip)

and then try to make auto range picking. We get a crash

![2024-07-18 13 46 02](https://github.com/user-attachments/assets/92079b47-47f1-498b-a935-95c8cdb059ab)

This could happen from various places in NMRium so it should be catched everywhere.

**Comment by hamed-musallam** [comment]
We have the same issue with `react-ocl-nmr` when the mouse hovers over the atom

**Comment by lpatiny** [comment]
@hamed-musallam Could you check if the bug is still there ? Normally the library should return undefined and not throw but you can still send a logger to get the information about too large molecules.

**Comment by hamed-musallam** [comment]
@lpatiny it works well
![image](https://github.com/user-attachments/assets/d2896b5e-53d0-466e-8270-19f459e25663)
