### ISSUE TITLE
Vertical 2D scale triggers callback on data

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3141]
I think the vertical 2D scaling should not trigger a data change.

![2024-07-18 18 19 02](https://github.com/user-attachments/assets/eb8b7f52-ec1d-4601-b451-9721bfa65e16)

**Comment by hamed-musallam** [comment]
This can be achieved once we move the scale ratio and domain to the view object. For now, we can set it in the neglected actions as an easier solution and wait for the refactoring, which can be done late
