### ISSUE TITLE
shift click to change pivot not working anymore ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3202]
<img width="839" alt="image" src="https://github.com/user-attachments/assets/f14e50b0-9b37-443f-93fa-c901e05c53de">

**Comment by hamed-musallam** [comment]
produced in https://github.com/cheminfo/nmrium/commit/83ff53108a2c2555fafaf227fb632a8e8270adae#diff-39ffb160a0a169aae38aada9e9e2df04e24e80eb7791d6366c20e909180b1c3fL364-L369
