### ISSUE TITLE
Select DPI when copying / saving as PNG ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3228]
could we have a general preference that would allow to specifiy the DPI when copying to the clipboard and saving as PNG ?

No idea how difficult it is to do.

**Comment by hamed-musallam** [comment]
Yes it is something possible to be implement, As i know the default DPI for the web is 96

**Comment by hamed-musallam** [comment]
@lpatiny 

As you are aware, increasing the DPI directly increases the resolution and, consequently, the file size of the generated image. Should we consider imposing a limit on the DPI, or for now, allow users to specify any value they require?

**Comment by lpatiny** [comment]
You are right we could just allow 3 resolutions:
- 72 dpi
- 150
- 300

**Comment by hamed-musallam** [comment]
I would suggest to have those options 
![image](https://github.com/user-attachments/assets/d6353f74-b7bc-4335-b48e-df293ad402d9)

**Comment by lpatiny** [comment]
72 and 96 are pretty common so they should be there as well but we can add them to your list.
