### ISSUE TITLE
Tracking should display only the selected spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3231]
In tracking mode of multiple spectra analysis it would be better to display only the currently selected spectra.

This would allow to cherry pick some spectra and be able to find their corresponding reference.

<img width="1100" alt="image" src="https://github.com/user-attachments/assets/ee33fdaf-2593-4f9e-bd51-3d17b02e90cd">

**Comment by hamed-musallam** [comment]
@lpatiny 

in case none of the spectra is selected, should we have the same as now? I mean display all the spectra
