### ISSUE TITLE
Copy / Save as PNG - width / height

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3239]
When copying or saving as PNG we can now select the DPI:

- https://github.com/cheminfo/nmrium/issues/3228

But this makes only sense if we can as well specify width and height of the final image.

- Should we define somewhere if we use inch, mm or cm (general prefs of NMRium ?) or have a combined input with width / height + units (mm, cm, inch)
- We should have 2 fields for width and height
- We could have a drop down menu that fills width / height depending some predefined sizes like A4, A3, ... like for pdf exportation.

**Comment by targos** [comment]
As a reference, here's the interface to change the image size in Affinity Photo:
![CleanShot 2024-09-12 at 15 41 52](https://github.com/user-attachments/assets/2e5342be-1d1d-4a11-844a-709c76d36250)
![CleanShot 2024-09-12 at 15 42 22](https://github.com/user-attachments/assets/86cc8ec1-e3fc-4f00-9f3d-aa355546a026)
