### ISSUE TITLE
Add 1D slice in case of 2D FID display

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3253]
When we display an fid we should show the 'cut' by default.

<img width="898" alt="image" src="https://github.com/user-attachments/assets/6991dcfe-428b-4421-97ee-52ef15155726">

Similar to 
<img width="68" alt="image" src="https://github.com/user-attachments/assets/bc1d2ce4-7f09-4962-933d-d4be6120fa3b">

But without dimmed specdtrum. So we always need the cut on both axis when displaying a 2D FID.

**Comment by hamed-musallam** [comment]
It should be the default behavior when you select a 2D FID spectrum.

**Comment by hamed-musallam** [comment]
@lpatiny 

this is the behavior that we currently have in NMRium, if not, you can reopen the issue.
