### ISSUE TITLE
Go back in time and display traces

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3290]
In ethyl crotonate if we go back in time and we move the cursor on the spectrum we don't see the traces

![Image](https://github.com/user-attachments/assets/115b3599-48fa-4f5b-831d-e684f05f50e9)

**Comment by hamed-musallam** [comment]
the traces exist, it seems there is an issue in slicing the data
 ![Image](https://github.com/user-attachments/assets/fe79074b-2a13-4557-b49c-63f2fdf156c6)

**Comment by hamed-musallam** [comment]
the issue comes from the min/max for x and y are wrong in this sample 
```ts
{
maxX: 1.590024000000082,
maxY: 98555,
maxZ: 43910,
minX: 8,
minY: 3,
minZ: -34125,
noise: 243,
} 
```

**Comment by jobo322** [comment]
seems to me the problem is not in the minMax object, if you check is the picture when you go back to apodization, nmrium should use the axis scale for the FID but it keep the axis for the FFT. do you know what I mean, it is the reason seem stop me the you only see this small FID as the trace
