### ISSUE TITLE
Use concat (+=) rather than join

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3311]
https://github.com/cheminfo/nmrium/blob/b8d5bd7234878c61e00574d16ef90196f9291da5/src/component/utility/PathBuilder.ts#L1-L28

Today making += is faster than join

![Image](https://github.com/user-attachments/assets/e795240d-715d-4074-b6a9-20ce95e0eb88)

**Comment by hamed-musallam** [comment]
Indeed, string concatenation appears to perform better than using join
