### ISSUE TITLE
Processing bruker files

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#518]
Are we able to take the bruker parameters PH0 and PH1 and reapply it to a FID ?

This could somehow be the default parameter for phase correction if we load a FID.

**Comment by jobo322** [comment]
we could check if a `pdata` folder exists for a FID file, and add those values as a filter. What do you think

**Comment by jobo322** [comment]
Currenctly, the values phc0 n phc1 into info. so We could check it at the level of nmrium to add the filter.

**Comment by jobo322** [comment]
this could be related with:

-https://github.com/cheminfo/nmrium/issues/2282

currently, we have the phase correction values into `info` object but sometimes the result is not the expected as you can see in the ticket above

**Comment by jobo322** [comment]
it is done in the nmr-load-save v0.28.0
