### ISSUE TITLE
feature: load a spectra into the spectra display module using an url

### ISSUE THREAD

**Issue by jwist** [cheminfo/nmrium#522]
options in the url may allow to hide part of the displayer if not wanted

**Comment by hamed-musallam** [comment]
@lpatiny

**Comment by jobo322** [comment]
currently it is possible by click on the import icon.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/12143935/224033943-eb5291a2-2c0b-4e55-ad84-da4bb0bfb5d8.png">
