### ISSUE TITLE
Zones picking in HSQC depends on zoom region

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmrium#616]
If the HSQC (dataset 'cytisine' from General section) is selected for (manual) zone picking, the two crosspeaks of the diastereotopic H's @ 4.04 and 3.84 are 'recognized' as two peaks, if the zoom for picking is larger than at least the window 48-55 (in 13C) and 2.7-4.3 (in 1H). If you zoom in the latter area first and then do the picking, the right signal is not recognized. I could repeat this several tim
![zones_HSQC_1_062020](https://user-images.githubusercontent.com/47237343/95161304-13e88000-07a3-11eb-8b5a-bb4dc66f5be5.PNG)
![zones_HSQC_2_062020](https://user-images.githubusercontent.com/47237343/95161312-177c0700-07a3-11eb-9b31-1afc20f24931.PNG)

es.

**Comment by lpatiny** [comment]
We can not reproduce this problem. Can you upload an animated gif ?

**Comment by nes-cgn** [comment]
I took a movie, here you can see it (first step - zones with full view, second step - zones from expansion)
[bug_616.zip](https://github.com/cheminfo/nmr-displayer/files/5363123/bug_616.zip)

**Comment by nes-cgn** [comment]
It seems to me, that it does not appear any longer. What I noticed in the combined dataset (HSQC/HMBC Cytisine) is, that if I display only the HSQC and repeat the zone picking only on the HSQC, the dots to mark the zone frequencies/shifts are not visible
or the same happens (see screenshot
![zones_HSQC+HMBC_1](https://user-images.githubusercontent.com/47237343/99569972-9171f380-29d1-11eb-9ad7-fedf79e79c68.PNG)
):

**Comment by jobo322** [comment]
seems that the peak is not detected, I will have a look.
