### ISSUE TITLE
Zones picking in combined HSQC/HMBC without labels. Displayer crashed when zoomed HMBC is picked

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmrium#617]
(1) When the dataset 'HSQC/HMBC cytisine' (General section) ist chosen and only the HSQC is displayed, the zones tool does not show the dots for the defined crosspeaks, even though the zones table gets populated.
(2) When the HSQC is deselected and the HMBC is picked with the zones tool, this only works as long as the entire spectrum is visible. If you first zoom into a region to selectively pick the zones, the interface crashes.
![zones_HSQC_3_061020](https://user-images.githubusercontent.com/47237343/95161982-d127a780-07a4-11eb-8fd4-7dfe69fce56f.PNG)
![zones_HSQC_HMBC_1_061020](https://user-images.githubusercontent.com/47237343/95161995-da187900-07a4-11eb-8d21-12af6caed201.PNG)
![zones_HSQC_HMBC_2_061020](https://user-images.githubusercontent.com/47237343/95162004-e270b400-07a4-11eb-9611-84b2902a1bce.PNG)

**Comment by lpatiny** [comment]
Second point can not be reproduced but maybe fixed in the meantime.

**Comment by nes-cgn** [comment]
I made a movie for the second point (first, zones on entire spectrum - without the zone-centers being picked! - and then zoom-in and zones from expanded reagion - leads to crash (at least on my computers)
[bug_617.zip](https://github.com/cheminfo/nmr-displayer/files/5363163/bug_617.zip)

**Comment by hamed-musallam** [comment]
@nes-cgn 
I fixed it right now. To show the zones you have to set negative  or positive signal  visible by click on the eye icon, like what we have in below image 
![image](https://user-images.githubusercontent.com/35760236/96459709-b5031c00-1222-11eb-9a4e-749b27f047d5.png)

**Comment by nes-cgn** [comment]
Not so sure. At least for me, if I have the HMBC active (HSQC also deactivated by eye icons to avoid confusion), I can zoom in this region and then select 2-3 zones, but again, at some point it crashed
