### ISSUE TITLE
2D peak picking in HSQC does not yield to the top of the peak

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#642]
I expect the green top on the top of the peak but this does not seem the case

![image](https://user-images.githubusercontent.com/1484241/95547568-953e4d80-0a03-11eb-83a2-a50d0b559c7b.png)

**Comment by jobo322** [comment]
I did some changes in 2D peak picking, could you check if there is an improvement on it?
![image](https://user-images.githubusercontent.com/12143935/105625250-b3cf2580-5df5-11eb-833e-4f2d69d3c521.png)
