### ISSUE TITLE
how is the version number determined?

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#716]
![image](https://user-images.githubusercontent.com/2352663/100851849-05a69f80-3486-11eb-8399-923f481c21de.png)

My application is currently running on version 0.3.7, but it says 0.4.0 in the UI:

![image](https://user-images.githubusercontent.com/2352663/100851922-1c4cf680-3486-11eb-848d-c3d7ac48c0b2.png)

**Comment by hamed-musallam** [comment]
@targos 
I read the tags from GitHub tags API https://api.github.com/repos/cheminfo/nmr-displayer/tags  and they sort the data according to version number so the first element when I get the data  is v4

**Comment by lpatiny** [comment]
We can not really call an api because some companies have firewall and also don't want there are any external calls.
