### ISSUE TITLE
Set reference of 2D spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#758]
In 2D Zones allow edition of the delta

![image](https://user-images.githubusercontent.com/1484241/102102988-b456c280-3e2c-11eb-807f-3c85d5717544.png)

This will add a filter that shift the spectrum either on the horizontal or vertical axis. Actually it is the boundary that moves and not the matrix itself.

**Comment by lpatiny** [comment]
This could be achieved by clicking twice in the table on the value and editing directly the value in the cell.

**Comment by lpatiny** [comment]
Currently it is not correct

**Comment by hamed-musallam** [comment]
it's done
