### ISSUE TITLE
HMQC zones picking (manual) leads to crash

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmrium#785]
In the following example (HMQC from nmr-dataset1 case 2591-86-8), automatic zones picking does not allow a meaningful result. So, the picking needs to be done manually. And in that case, the three signals in the upper right corner of the correlation (see expansion 2 from attached files) always leads to a crash, if I try to select the three individual cross peaks for zone definition...
[hmqc-light.zip](https://github.com/cheminfo/nmr-displayer/files/5786432/hmqc-light.zip)
![hmqc_ausschnitt-1](https://user-images.githubusercontent.com/47237343/104000865-23f76d80-519f-11eb-968b-b52eb7853e9e.PNG)
![hmqc_ausschnitt-2](https://user-images.githubusercontent.com/47237343/104000869-24900400-519f-11eb-9668-35de5d5d9d6a.PNG)
![hmqc_gesamt](https://user-images.githubusercontent.com/47237343/104000871-25289a80-519f-11eb-82a6-f8f5d3e4fc89.PNG)

**Comment by hamed-musallam** [comment]
@nes-cgn 
can you try the last version....

**Comment by hamed-musallam** [comment]
@lpatiny 
Can you please test it from your side because I can't reproduce this problem?

**Comment by nes-cgn** [comment]
I tried the latest version, problem continues. The notebook is quite powerful, I do not think it is a processor issue.

**Comment by hamed-musallam** [comment]
@lpatiny @jobo322 
this bug related to nmr-processing package 
![image](https://user-images.githubusercontent.com/35760236/104014001-9a519b00-51b2-11eb-8c93-3a11b8719f4d.png)

**Comment by jobo322** [comment]
@nes-cgn could you check if this was improved?

**Comment by nes-cgn** [comment]
I tried, and what I see is that it does not immediately crash. This is  an advantage. However, when I try to do an automated picking, I get what you see in the file called "...-new":
![hmqc-270121-new](https://user-images.githubusercontent.com/47237343/106031338-71486a00-60cf-11eb-839c-5371b0a7b52d.PNG)

If I do remove the automatically picked peaks and define the zones manually, the frames for the zones are visible, as visible in the file "...-new2":
![hmqc-270121-new2](https://user-images.githubusercontent.com/47237343/106031930-211dd780-60d0-11eb-90bb-30f0c0bd22e6.PNG)

If I define the entire group of the three "difficult" cross peaks, it somehow finds the maxima, but I would prefer that I can select the region and then, only one (centered) peak is defined. As in the "all-in-one" approach, the three different signals fall into the same zone which I find less useful:
![hmqc-270121-new3](https://user-images.githubusercontent.com/47237343/106032647-0730c480-60d1-11eb-872a-d4ed2ed7ac48.PNG)

**Comment by jobo322** [comment]
I am looking for a solution. I found that we pass to the method all the intensity range. we could handle the problem with noiseFactor e.g for auto detection with noiseFactor equal to 5 I got the next picture

![image](https://user-images.githubusercontent.com/12143935/106322126-5a2a8900-6243-11eb-94f0-2065d4f602d4.png)

it is not still the best result but it is better, I am trying to understand why the method depends in this way of noiseFactor

**Comment by nes-cgn** [comment]
Well, as I mentioned - it is primitive, but if you look at the "-new2" picture three graphs above, in the worst of all cases, one could define an option that sets the centre of a (manually defined) region as the picked peak. That is by no means automatic recognition, but at least, like that you could add a value in critical cases where other attempts fail

**Comment by jobo322** [comment]
Apparently, this problem is fixed, could you have a look?
