### ISSUE TITLE
Peak picking and change of number of pixels

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#788]
In the processed 13C example if we change the size of zero filling we have a bug because labels are attached to a point and not to a value.

![image](https://user-images.githubusercontent.com/1484241/104285001-3fba8680-54b3-11eb-9a24-be41f7eb1795.png)

We need to define a strategy on how to deal with this problem that we also encounter in 2D.

**Comment by lpatiny** [comment]
Peaks should used the chemical shift and not the xIndex as 'anchor'.

Please rename `xIndex` to `delta` in Peak. I guess in Range the `from`and `to` properties are already in ppm units.

**Comment by hamed-musallam** [comment]
It's fixed.
