### ISSUE TITLE
order peaks in zones and ranges table by chemical shift

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmrium#805]
It would be useful if there was an option to order the entries of the zones and ranges tables according to decreasing/increasing chemical shift.

**Comment by hamed-musallam** [comment]
@nes-cgn 
We encounter another issue with the chemical shift so after we find a way I'm going to return back to this.

**Comment by nes-cgn** [comment]
Any news on the topic? @hamed-musallam
