### ISSUE TITLE
only pick displayed region

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmrium#806]
As for the currently available possibility to see the corresponding frequencies highlighted in zones/ranges tables, if a  section of the spectrum is expanded, there should be the possibility to apply the picking (peaks, integrals, ranges, zones) only for the window that is visible

**Comment by hamed-musallam** [comment]
@lpatiny 
@jobo322 

For auto peaks, integrals, ranges, zones, is it possible to pass the window domain as a parameter????

**Comment by lpatiny** [comment]
Certainly not for all the methods you should make an array.slice if it is a normal array before submitting to the method.

Now if it is a typed array there is a trick that allows to create a 'view' to the buffer of the original data. In this case you don't copy the array so it is much faster and less memory intensive. You can see more information here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays#buffers_and_views_typed_array_architecture or if you need I can help you for this.

**Comment by hamed-musallam** [comment]
@nes-cgn 
@lpatiny 
It's done for auto peaks, ranges, and zones detection.
