### ISSUE TITLE
Drag drop bruker file + phase correction bug

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#872]
If you drag and drop the following file and make an automatic phase correction the spectrum shifts ! (and the phase is really bad)

[1.zip](https://github.com/cheminfo/nmr-displayer/files/6091945/1.zip)

![image](https://user-images.githubusercontent.com/1484241/110146814-4e4e5b80-7ddb-11eb-9df5-8f92979088e5.png)

**Comment by jobo322** [comment]
There is a mixing of real and imaginary part of the spectrum, For sure there is some bug in brukerConverter

**Comment by lpatiny** [comment]
This bug was fixed. Thanks !
