### ISSUE TITLE
Highlight from spectrum range to molecule does not work

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#879]
If you go over the range in the spectrum the atom in the molecule is not highlighted.

While if you go over the range it works correctly. Memo problem ???

[1.nmrium.zip](https://github.com/cheminfo/nmr-displayer/files/6101824/1.nmrium.zip)

![image](https://user-images.githubusercontent.com/1484241/110331354-4b43ad00-801f-11eb-8764-db95b1360ace.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
after I trace why it works like that, it's because Michael assigns a signal and not a range.

**Comment by lpatiny** [comment]
Ok then when you are over a 'range' in the spectrum it should highlight all the highlightIDs of the ranges AND included signals

On the other hand when you are on the little tree describe the multiplicity of a signal it should only highlight the corresponding signal.
