### ISSUE TITLE
Align can crash

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#890]
@hamed-musallam If the selected area is less than 9 points width it will crash. Are you able to easily check this and add a warning in the dialog box that the zone is too small ?

![image](https://user-images.githubusercontent.com/1484241/110671224-8d5f2100-81ce-11eb-9fe8-145ec1be39f8.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
Actually, it's not straightforward to check that the x array contains at least 9 values, I think I suppose to get "from" and "to" values and then get the closest value from the x array and check the range if it contains 9 values or not.

is that what you need?
