### ISSUE TITLE
Prediction of molecule with lots of connected atoms

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#905]
If you try to predict a molecule like

![image](https://user-images.githubusercontent.com/1484241/111020046-703f7380-83c3-11eb-924f-37569c463e2d.png)

There is a crash

![image](https://user-images.githubusercontent.com/1484241/111020023-4b4b0080-83c3-11eb-965a-7fbab32fd11b.png)

@jobo322 Please add this testcase in nmr-processing package and try to debug this new problem due to the code migration.

**Comment by lpatiny** [comment]
Actually you can simply take the butane example.

This problem is related to https://github.com/cheminfo/nmr-processing/issues/46

**Comment by jobo322** [comment]
Seems that the problem was fixed with the new version of the prediction code.
