### ISSUE TITLE
Add prop to define the message

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#951]
For exercises it does not make sense to have the current text message

![image](https://user-images.githubusercontent.com/1484241/113382167-240f9f80-9381-11eb-826d-6ad3f74445d6.png)

Add a new prop to the component that allows to customise this message. The prop is called `dragDropText`

**Comment by targos** [comment]
maybe "emptyText" ?

**Comment by lpatiny** [comment]
Indeed much better.
