### ISSUE TITLE
Add about button

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#956]
On the top left of the component add a button that will open a dialog box.

![image](https://user-images.githubusercontent.com/1484241/113435466-2acefe80-93e3-11eb-9c1c-c1512f1dd50b.png)

The icon of this button should be

![image](https://user-images.githubusercontent.com/1484241/113435656-9022ef80-93e3-11eb-8430-471c3c7a335c.png)

@targos could you give us a SVG of this icon ?

@hamed-musallam Could you add this SVG in cheminfo-font (/nmr/nmrium.svg). It could be in black / white in cheminfo-font but should have his right orange color in the nmr-displayer.

If possible display the current release version of the component @targos How can this be done ?

Add a link to www.nmrium.org

We will add some more text in this 'about' dialog box later.

**Comment by hamed-musallam** [comment]
@lpatiny 
But we have ِ" About " tab inside the general preferences
![image](https://user-images.githubusercontent.com/35760236/113567772-81b91b80-960f-11eb-8814-e94802bfa69a.png)

**Comment by hamed-musallam** [comment]
@lpatiny 
what do you decide about this ticket?

**Comment by lpatiny** [comment]
Please move the About from the General Settings to this new icon that will be top left of NMRium. The icon is now in cheminfo/font (logo/nmrium.svg)

You should also change the logo that will be in the new dialog box and use (currently it is react logo) by the following one: [nmrium-loco.svg.zip](https://github.com/cheminfo/nmrium/files/6410014/nmrium-loco.svg.zip)

In the about dialog box you should keep the current information.

You could also add a link towards: https://www.nmrium.org

There should be new 2 sections as well:

About us:

This project is developed by Zakodium Sàrl (Switzerland), the University of Cologne (Germany), Johannes Gutenberg University Mainz (Germany) and Universidad del Valle (Colombia)

Funding is provided by:
  - IDNMR grant, which part of the Scientific Library Services and Information Systems (LIS) initiative of the DFG.
  - Zakodium Sàrl (Switzerland)
  - Universidad del Valle (Cali, Colombia)

A layout that would fit without scrolling would be nice.
