### ISSUE TITLE
delete all atom assignments break nmrium

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#963]
nmrium is breaking when you try to remove all the assignments of the ranges.

**Comment by lpatiny** [comment]
Clicking on the button crash the system:

![image](https://user-images.githubusercontent.com/1484241/115986364-162ff180-a5b0-11eb-9927-d512f771cb98.png)

![image](https://user-images.githubusercontent.com/1484241/115986293-cd783880-a5af-11eb-8090-f61a4ac3b52a.png)
