### ISSUE TITLE
No click possible anymore to add a link manually  

### ISSUE THREAD

**Issue by michaelwenk** [cheminfo/nmrium#979]
@hamed-musallam 
When we want to add a new link in the correlation table (right click on a cell) then the button appears but it does not allow a click on it anymore (picture 1). 
Also when we want to set sum molecular formula in the modal then the correlation table header is over the modal (picture 2). 
And if we hover over a cell which causes highlighting then the header background shows some table cell values (picture 3). 

Maybe, this exists since the table header became fixed? 

![picture1](https://user-images.githubusercontent.com/30418272/115027283-ce301100-9ec3-11eb-9ae3-d8674609cdf9.png)
<img width="937" alt="picture2" src="https://user-images.githubusercontent.com/30418272/115027301-d38d5b80-9ec3-11eb-9f1a-f25603311dd1.png">
![picture3](https://user-images.githubusercontent.com/30418272/115027319-d9833c80-9ec3-11eb-8fb2-e07d3b01a2d7.png)

**Comment by nes-cgn** [comment]
Yes, I agree. It would be nice to have this active again.
