### ISSUE TITLE
Keep .nmrium extension even if zipped

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#983]
This is related to https://github.com/cheminfo/nmrium/issues/950

As describe in the ticket please keep the '.nmrium' extension even if it is zipped !

When loading the file we need to check the 4 first bytes of the buffer so see if it matches: hexadecimal code 50 4b 03 04 (file signature, https://en.wikipedia.org/wiki/List_of_file_signatures)

Based on this you know if it is zipped or not.

**Comment by targos** [comment]
Why did you choose to create a zip ( an archive) instead of just using some compression algorithm?

**Comment by hamed-musallam** [comment]
@lpatiny 
the problem in this way that we have to make refactoring and not relies on the extension anymore and always look at the first 4 bytes to detect the kind of files.

**Comment by lpatiny** [comment]
> Why did you choose to create a zip ( an archive) instead of just using some compression algorithm?

Indeed we could have use another compression but we will need zip anyway to support NMRedata

**Comment by lpatiny** [comment]
> @lpatiny
> the problem in this way that we have to make refactoring and not relies on the extension anymore and always look at the first 4 bytes to detect the kind of files.

We can rely on the extension .nmrium.

It is the part that will parse the .nmrium extension that needs to check the 4 bytes and decompress if required. So it seems easier actually to me.
