### ISSUE TITLE
cdn.nmrium.org crashes when deleting FID or spectrum

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmrium#988]
When I import the attached ZIP and try to delete the FID, the cdn.nmrium.org instance crashes. This is the console output:

![grafik](https://user-images.githubusercontent.com/40795855/115424527-13737c00-a1ff-11eb-95c5-2eda0f05b55a.png)
[1-brombutan_109-65-9.zip](https://github.com/cheminfo/nmrium/files/6344791/1-brombutan_109-65-9.zip)

**Comment by lpatiny** [comment]
Please try with version v0.9.0: https://cdn.nmrium.org/v0.9.0/
