### ISSUE TITLE
Indicate signal as solvent signal (only in Firefox)

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmrium#991]
If I try to define a signal in the ranges/zones table as a solvent signal, this is not possible in firefox. Only there, in chrome it works.
![define_solvent_firefox](https://user-images.githubusercontent.com/47237343/115905534-84689d00-a466-11eb-822b-89423dc0d480.PNG)

**Comment by lpatiny** [comment]
@hamed-musallam I can confirm that it does not work with the last version of Firefox.
