### ISSUE TITLE
Assignment of alkyne protons not visible (in firefox and chrome)

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmrium#993]
When an alkyne proton is assigned, the atom does not get any colour-label (yellow circle). However, the assignment is kept as can be seen from the zone/range table and when hovering over the structure

**Comment by lpatiny** [comment]
You are speaking about a H on a triple bond ?

I can not reproduce this bug

![image](https://user-images.githubusercontent.com/1484241/115986009-a0775600-a5ae-11eb-96e2-4522d0b2296a.png)

**Comment by nes-cgn** [comment]
Hello Luc, for example 623-47-2, if you pick the H,C correlation, the assignment of the 1H with the structure does not leave a yellow circle
![Luc_260421i](https://user-images.githubusercontent.com/47237343/116030284-8182cd80-a65b-11eb-8ad9-fae51a2b6b7e.PNG)

**Comment by nes-cgn** [comment]
It does not matter if you do it in the 1D or 2D
![Luc_260421ii](https://user-images.githubusercontent.com/47237343/116030380-b7c04d00-a65b-11eb-9c3e-4729af73e71c.PNG)

**Comment by lpatiny** [comment]
@michaelwenk Could you have a look to this problem ?

**Comment by michaelwenk** [comment]
@nes-cgn @lpatiny It seems to be a bug in the structure view component. After assigning that H and expanding it in the structure (shift + click) we see that it has a yellow circle. Also the highlighting when hovering over a signal in table or chart view is working well. 

<img width="1437" alt="Bildschirmfoto 2021-05-03 um 16 19 57" src="https://user-images.githubusercontent.com/30418272/116889280-aa432e00-ac2c-11eb-8ef6-06b0163a5521.png">
<img width="1437" alt="Bildschirmfoto 2021-05-03 um 16 20 07" src="https://user-images.githubusercontent.com/30418272/116889293-ae6f4b80-ac2c-11eb-9bd2-5411472419dc.png">

**Comment by lpatiny** [comment]
@jobo322 If you check the react-ocl-nmr component (for the atom number) you may also have a look to reproduce this bug.

**Comment by jobo322** [comment]
It seems to be solved
