### ISSUE TITLE
Rebase branch levels

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#994]
@hamed-musallam Please could you rebase branch `levels` ? I should finalize this branch and put it in production.

**Comment by hamed-musallam** [comment]
@targos 
how can I use the git rebase command without losing the changes that I did on the levels branch, for example when I rebase I always losing the changes that we did in Contours.jsx  on the levels branch, what is the best strategy to deal with this issue?

**Comment by targos** [comment]
You can use git merge if rebase introduces issue

**Comment by hamed-musallam** [comment]
@targos 
Thanks for the advice.

**Comment by hamed-musallam** [comment]
@lpatiny 
Right now you have the last version of the code from the master branch plus the changes that we already did in the levels branch.
