### ISSUE TITLE
program crashes with NOESY

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmrium#996]
When attempting to import the following NOESY (jcamp) by drag and drop, there is a crash:
[noesy.zip](https://github.com/cheminfo/nmrium/files/6371286/noesy.zip)
the report function that pops up in nmrium does not work, neither (I cannot copy the error message)

**Comment by lpatiny** [comment]
@nes-cgn The nucleus 2 is not specified.

We have NUC1 that is 1H but we don't have NUC2.

Is this normal ?

**Comment by lpatiny** [comment]
In fact in general I have no idea from the jcamp how to determine the 2 nucleus used in the 2D. I can not find this information in all the parameters. @djeanner do you know how to reliably now what are the 2 nucleus of the 2D from the jcamp ? You may have a look at the example given by Nils in this ticket.

**Comment by djeanner** [comment]
I'm no expert of jcamp, in particular 2D, but just searching for "1H" in the file for NOESY I found what I suppose to be the info about the nuclei more than twice:
##.OBSERVE NUCLEUS= ^**1H**
...
##$AXNAME= <F2>
##$AXNUC= <**1H**>
...
$$ Bruker specific parameters for F1
$$ ---------------------------------
##$ACQT0= 0
##$BF1= 600.2
##$FnMODE= 5
##$NUC1= <**1H**>
...
##$AXNAME= <F1>
##$AXNUC= <**1H**>
...

##NTUPLES= nD NMR SPECTRUM
##VAR_NAME=  FREQUENCY1,    FREQUENCY2,      SPECTRUM
##SYMBOL=    F1,            F2,              Y
##.NUCLEUS=  ,              **1H**
##VAR_TYPE=  INDEPENDENT,   INDEPENDENT,     DEPENDENT
##VAR_FORM=  AFFN,          AFFN,            ASDF
##VAR_DIM=   512,           1024,            1024
##UNITS=     HZ,            HZ,              ARBITRARY UNITS
##FACTOR=    11.3553215728855, 5.67768895348837, 1
##FIRST=     5727.90220241547, 5808.2757994186, 575
##LAST=      -74.6671213290483, 0,           595
##MIN=       -74.6671213290483, 0,           -341566861
##MAX=       5727.90220241547, 5808.2757994186, 15804978

**Comment by lpatiny** [comment]
@djeanner If you have a 13C / 13C cosy kind experiment and you irradiate the 1H during the experiment.

Which parameters in the Bruker ACQUS would tell you that on both axis it is 13C ?

The problem in this noesy file:
```
##SYMBOL= F1, F2, Y
##.NUCLEUS= , 1H
```
Is that for F2 we know it is 1H but the nucleus for F1 has not been specified. It should be `##.NUCLEUS=1H , 1H`

**Comment by djeanner** [comment]
I agree .nucleus should state all isotopes ! That’s the problem with redundancy we dint know where to read stuff. I would say use AXNUC. As for irradiation that is a difficult question!! During detection you can try to guess from pl12 pcpd etc. For F1 it is nearly impossible. I would guess from the pulseprogram name what category out of the classic!

**Comment by lpatiny** [comment]
@djeanner thanks for your answer. At least I didn't miss something obvious. The NOESY problem is solved but we may still find some files that will yield problems.
