### ISSUE TITLE
In case of errors copy report does not work

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#997]
![image](https://user-images.githubusercontent.com/1484241/115986317-e8e34380-a5af-11eb-973a-740dbca0b17e.png)

The clipboard is empty trying to copy report

**Comment by targos** [comment]
On what page did it happen?

**Comment by hamed-musallam** [comment]
@lpatiny 
Where is this? because i do not remember that i did something like that in the nmr-dislayer

**Comment by lpatiny** [comment]
How to reproduce:

1. https://www.nmrium.org/nmrium#?toc=https://cheminfo.github.io/nmr-dataset-demo/samples.json
2. Auto range picking
![image](https://user-images.githubusercontent.com/1484241/116088561-45bf2680-a6a2-11eb-8717-83603c7d7380.png)
3. In the ranges panel click on the unlink icon
![image](https://user-images.githubusercontent.com/1484241/116088693-638c8b80-a6a2-11eb-8024-d9e9bb7ae796.png)

There is currently a bug in NMRium  so it will crash ;)

**Comment by lpatiny** [comment]
@hamed-musallam You are right it does not seem to be related to NMRium component.
@targos I'm afraid I can not transfer this issue because it is not the same organization. Should I reopen one in nmrium.org ?

**Comment by targos** [comment]
> Should I reopen one in nmrium.org ?

Yes please

**Comment by hamed-musallam** [comment]
yes please.
