### ISSUE TITLE
Histogram and levels

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#998]
In the color select

![image](https://user-images.githubusercontent.com/1484241/115991552-564f9e00-a5c9-11eb-81a0-6facb2347d7c.png)

We need to display a histogram of the intensity of points. This can be calculated using the following methods from spectrum-processing

- xHistogram
- matrixHistogram

This histogram could be displayed using 'react-plot'

https://zakodium.github.io/react-plot/?path=/story/api-barseries--bar-control

Don't display Y axis, no legend on X axis.

We will improve the layout and calculation options later.

**Comment by hamed-musallam** [comment]
@lpatiny 
I looked for the library you mention above but I did not found one with exact same name, what I find this one https://github.com/cheminfo/spectra-processor and it's not containing the functions that you mention.

**Comment by hamed-musallam** [comment]
@lpatiny 
is the histogram of the intensity for 1d and 2d? and why you need to display in this panel?

**Comment by lpatiny** [comment]
Sorry I was wrong. It is in https://github.com/mljs/spectra-processing and already a dependency of nmrium

**Comment by hamed-musallam** [comment]
@lpatiny 
why I need xHistogram and this function already used by matrixHistogram?

**Comment by hamed-musallam** [comment]
it's done
